### ISSUE TITLE
Krishna Rao

### ISSUE THREAD

**Issue by kkraoj** [samapriya/awesome-gee-community-datasets#10]
### Vegetation dryness for western USA

This dataset shows how dry or wet the vegetation is in western US. The dataset is available at 15-day temporal resolution and 250 m spatial resolutio. It spans April 2016 to present. 

The variable contained in the maps is live fuel moisture content. It is defined as the mass of water per unit mass of live biomass (expressed as a percentage quantity). For e.g., if a pixel value = 150, it means that the vegetation in that pixel has 1.5 Kg of water for every 1 Kg of live biomass. Live fuel moisture content was estimated from a deep learning model trained using Sentinel-1 C-band backscatter, Landsat-8 optical reflectance, and various other land surface characteristics like canopy height, soil texture, etc. 

Associated paper:
Rao, K., Williams, A.P., Flefil, J.F. & Konings, A.G. (2020). SAR-enhanced mapping of live fuel moisture content. Remote Sensing of Environment, 245, 111797. DOI: 10.1016/j.rse.2020.111797

<p align="center">
  <img width="360" src="https://github.com/kkraoj/lfmc_from_sar/blob/master/figures/lfmc_2_panels_projected_annotated.gif?raw=true" alt="Seasonal variation of live fuel moisture content estimated by our deep learning model.">
</p>

#### Earth Engine Snippet

**Asset Link**

```js
var asset_name = ee.ImageCollection("users/kkraoj/lfm-mapper/lfmc_col_25_may_2021")
```

**Sample Code**

This script imports and visualizes average vegetation dryness for 2019

```js
var start_date = '2019-01-01';
var end_date =  '2019-12-31';

// Import LFMC collection
var collection = ee.ImageCollection('users/kkraoj/lfm-mapper/lfmc_col_25_may_2021')
  .filterDate(start_date,end_date)

var image = collection.mean(); //calculate mean for the selected date range
var palette_lfmc = ['#703103','#945629','#ce7e45', '#df923d', '#f1b555', '#fcd163', '#99b718', 
          '#74a901', '#66a000', '#529400', '#3e8601', '#207401', '#056201',
          '#004c00', '#023b01', '#012e01'
          , '#011d01', '#011301'];

Map.addLayer(image, {min: [50], max: [200], palette: palette_lfmc, opacity: 0.95}, 'LFMC mean');
Map.setCenter(-113.03, 38, 5);

```

#### Required
License Information: [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/)

Curated by: KrishnaRao, A. ParkWilliams, Jacqueline Fortin Flefil, Alexandra G.Konings

Keywords: vegetation, dryness, drought, wildfire, USA, live fuel moisture content

Last updated: 15-Jun-2021

**Comment by samapriya** [comment]
Thanks @kkraoj 
ND makes it a little more restrictive than just NC for people since no can build on top of it or from it  just my thought :) 

I will work on getting this uploaded today or tomorrow. Thank you for contributing I will update the ticket accordingly

**Comment by samapriya** [comment]
Hi @kkraoj 
This is now live, thank you for contributing :) you can find it here
https://samapriya.github.io/awesome-gee-community-datasets/projects/veg_dry/

**Comment by kkraoj** [comment]
Thanks! I did not know about the ND part. I will keep that in mind in the future. The journal offered only that non-commercial license, but I should have been more careful. I certainly don't want to restrict people from building on top of my work. In fact, I encourage. 

Thanks for building a compendium of datasets. I recently came across it and the moment I saw it, I wanted to contribute. This is going to be such a useful resource. Your efforts are going to help a lot of people, like me. Thank you!

**Comment by samapriya** [comment]
Hey @kkraoj 
That's perfectly fine I do want to tell you as the author of the dataset you do have the right to amend a license for data release or simply re-release the dataset with just NC if you would like. It does not change your paper guidelines but I do want to mention that similar to code datasets can be re released under any license the author wants :) 

thank you again for contributing and feel free to send me suggestions about any other datasets that either you create or you know about and that you think would be useful to the larger GEE community
