### ISSUE TITLE
Adaptwest CMIP6 downscaled 20-year mean ensemble predictions?

### ISSUE THREAD

**Issue by KWB4484** [samapriya/awesome-gee-community-datasets#100]
I've been using the 30-year ensemble mean bioclimatic variables. https://gee-community-catalog.org/projects/aogcm_cmip6/ Thanks to Samapriya Roy for curating these!

I just have a suggestion -- It would be nice if the 20-year mean ensemble predictions were also included.

**Comment by samapriya** [comment]
You are welcome @KWB4484 
Feel free to create a [dataset request](https://github.com/samapriya/awesome-gee-community-datasets/issues/new?assignees=samapriya%2C+valpasq%2C+edtrochim&labels=data+request&template=suggest-new-community-data-for-awesome--gee-catalog.md&title=Dataset+%26+Curator+Name). Happy to take a look
