### ISSUE TITLE
Ensemble mean of 13 CMIP6 AOGCMs (20 year periods) Bioclimatic Variables (33)

### ISSUE THREAD

**Issue by KWB4484** [samapriya/awesome-gee-community-datasets#101]
Thank you for considering this data request! Much of the climate data produced by AdaptWest are already in the catalogue: 30-year climate norms, 30-year future bioclimatic predictions from 13 CMIP6 AOGCMs, and 9 individual climate models. I'm suggesting that the 20-year future predicitons fron 13 CMIP6 AOGCMs also be added.

These data could be added to this image collection 
var aogcm_ensemble_bioclim = ee.ImageCollection("projects/sat-io/open-datasets/CMIP6-scenarios-NA/AOGCM-ensemble_bioclim");

Perhaps just another property that identifies 30- vs 20-year mean predictions?

### Ensemble mean of 13 CMIP6 AOGCMs (20 year periods) Bioclimatic Variables (33)
Dataset description and any detailed citation and DOI and license information.
The datasets on this page [https://adaptwest.databasin.org/pages/adaptwest-climatena/] have been developed by AdaptWest, a project funded by the Wilburforce Foundation to develop information resources for climate adaptation planning. The data were generated using the [ClimateNA](http://climatena.ca/) software. [ClimateNA](http://climatena.ca/) downscales gridded data from [PRISM](http://www.prism.oregonstate.edu/) and [WorldClim](http://www.worldclim.org/) for current climate, and downscales data from the Coupled Model Intercomparison Project phase 6 (CMIP6) database corresponding to the 6th IPCC Assessment Report for future projections. In addition to ensemble projections, data are also provided from 9 representative individual AOGCMs. The rasters provided via this [page](https://adaptwest.databasin.org/pages/adaptwest-climatenav71/) were generated using ClimateNA version 7.3, which fixed a bug that limited the dynamic local elevation adjustment from being fully implemented for monthly minimum temperature. In other words, the Tmin rasters generated from ClimateNA versions prior to v7.3 did not have the expected degree of adjustment based on elevation. For rasters generated previously using ClimateNA v7.1, see this page.
For more information on the emission scenarios (Shared Socioeconomic Pathways; SSPs) used in CMIP6, see this [primer](https://www.carbonbrief.org/cmip6-the-next-generation-of-climate-models-explained).

Please cite the datasets below as:

AdaptWest Project. 2022. Gridded current and projected climate data for North America at 1km resolution, generated using the ClimateNA v7.30 software (T. Wang et al., 2022). Available at adaptwest.databasin.org.

For further information and citation refer to:
Wang, T., A. Hamann, D. Spittlehouse, C. Carroll. 2016. Locally Downscaled and Spatially Customizable Climate Data for Historical and Future Periods for North America. PLoS One 11(6): e0156720 https://doi.org/10.1371/journal.pone.0156720
Mahony, C.R., T. Wang, A. Hamann, and A.J. Cannon. 2022. A global climate model ensemble for downscaled monthly climate normals over North America. International Journal of Climatology. 1-21. https://doi.org/10.1002/joc.7566
Thumbnail or Snapshot (Optional)

#### Earth Engine Snippet if dataset already in GEE
Not yet in GEE to my knowledge.

#### Required 
Most of these data are already included in the catalog, which has the following information...

License[¶](https://gee-community-catalog.org/projects/aogcm_cmip6/#license)
These datasets are made available under the CC BY 4.0 Attribution 4.0 International license. This license allows users to distribute, remix, adapt, and build upon the material in any medium or format, so long as attribution is given to the creator.

Data Website: You can download the [data and description here](https://adaptwest.databasin.org/pages/adaptwest-climatena/)

Explore the data in [R-Shiny apps here](https://bcgov-env.shinyapps.io/cmip6-NA/)

Created by: AdaptWest Project, Wang, T., A. Hamann, D. Spittlehouse, C. Carroll

Curated in GEE by: Samapriya Roy

Keywords: climate change, global circulation models, gridded climate data, north america,emission scenarios,climate variables

**Comment by samapriya** [comment]
Seems I might need to update all datasets to 7.3 compared to 7.1, so I am expanding this ticket to update all 30 year and 20 year ensembles. Might take a bit :)

**Comment by KWB4484** [comment]
Nice! And understandable. Thanks for adding these data!

**Comment by samapriya** [comment]
Hi @KWB4484 
This took a while and needed uploading and adding to all datasets. This has nearly been completed and will be included in next release.

**Comment by samapriya** [comment]
This will be released tomorrow, but you can access the new datasets; it now has a metadata called period, which can filter for 20 vs. 30-year periods. Closing this issue for now. This took a while and a lot of effort :) thanks for being patient

**Comment by KWB4484** [comment]
Hello again --

Sorry to bother you about this dataset again but I just wanted to make you
aware of something and see if you could confirm something for me about an
image collection. Adaptwest offers two mean future predictions based on an
ensemble of 8 or 13 global climate models for several pathways/periods. I
noticed that the documentation (
https://gee-community-catalog.org/projects/aogcm_cmip6/) indicates the
ensemble uploaded is the mean of 13 global climate models however all
images in the collection (var aogcm_ensemble_bioclim =
ee.ImageCollection("projects/sat-io/open-datasets/CMIP6-scenarios-NA/AOGCM-ensemble_bioclim"))
start with the prefix "ensemble_8GCMs_". I'm writing up a manuscript and
need to indicate what I used; do you know which ensemble predictions were
uploaded? Thank you!

Best,

Kevin Barnes

**Comment by samapriya** [comment]
I think the ensemble models uploaded are all 8 not 13, I can update the text to categorically mention that. In fact, you can actually get this information by using a metadata field called ```ensemble_model_count``` all ensemble collections have this metadata property. That being said I realized that some of the metadata fields specifically the model name need to be fixed for other collections for the example scripts to work. I should be able to run these soon. Hope that helps

**Comment by samapriya** [comment]
Hi @KWB4484 
I have updated the text to reflect the collection contains the 8 model count ensembles and I have reprocessed the metadata so example scripts can work as expected

**Comment by KWB4484** [comment]
Thanks for the metadata tip and clarification!! Really appreciate all of
your work curating these amazing datasets.

**Comment by KWB4484** [comment]
Hello again --

I noticed the model names changed. I updated my code to reflect the new
names and now it seems the bioclimatic variable MAT for MRI-ESM2-0 SSP3-7.0
2011-2040 is missing...
https://code.earthengine.google.com/e81716374a08be64b49f79f8a72f47e7

Thanks!
