### ISSUE TITLE
Add Code example for Landscan Global

### ISSUE THREAD

**Issue by spatialthoughts** [samapriya/awesome-gee-community-datasets#102]
Follow the underlying template when creating a code example for an existing dataset in the awesome-gee-community-catalog.

Please edit the markdown text below as needed

### Dataset Name and Catalog Page
[LandScan Population Data](https://gee-community-catalog.org/projects/landscan/#landscan-population-data)

### Code link
https://code.earthengine.google.com/580fe304e023625748b4f3e0ef34b2cf

#### Attribution
Ujaval Gandhi https://www.spatialthoughts.com

**Comment by samapriya** [comment]
Hey @spatialthoughts 
Would it be possible to write just a one or two line descriptor about the code I would love to save that as well as I get more code example it would really help highlight awesome things you and other can contribute with code

**Comment by spatialthoughts** [comment]
How about the following? Feel free to edit

*The code snippet shows how to use the Landscan Global population dataset to plot a time series chart comparing changes in the yearly population of two regions from 2000-2020.*

**Comment by samapriya** [comment]
Thank you for contributing, the page has now been updated to reflect your contribution code and the code snippet has been added to the general repo for the community catalog

**Comment by spatialthoughts** [comment]
Nice! Looks good. A separate user-contributed code section is a good idea.
