### ISSUE TITLE
USA Structures dataset missing NY and WI states

### ISSUE THREAD

**Issue by giswqs** [samapriya/awesome-gee-community-datasets#105]
The [USA Structures](https://gee-community-catalog.org/projects/usa_structures/?h=struc) datasets are missing New York and Wisconsin.  They are available through the original USA Structures. 

https://disasters.geoplatform.gov/publicdata/Partners/ORNL/USA_Structures/

**Comment by samapriya** [comment]
Thanks @giswqs 
will take a look

**Comment by samapriya** [comment]
Seems they are geodatabases and are large enough that they cannot directly be converted into shapefiles it will exceed the 2GB limit. I will try to split it up

**Comment by samapriya** [comment]
This has now been processed, split, and merged back. Completed at my end and the datasets made available for use for NY and WI let me know if there are any issues

**Comment by giswqs** [comment]
Thank you very much, Sam.
