### ISSUE TITLE
Digital Earth Africa Cropland Extent Maps

### ISSUE THREAD

**Issue by hannah-rae** [samapriya/awesome-gee-community-datasets#106]
### Dataset Name
From [website](https://docs.digitalearthafrica.org/en/latest/data_specs/Cropland_extent_specs.html): "Digital Earth Africa’s cropland extent map for Africa shows the estimated location of croplands ... for the period January to December 2019". 10m resolution map providing binary (0 = noncrop, 1 = crop) and probability (crop probability in [0, 1]) for African continent.

Data access: https://docs.digitalearthafrica.org/en/latest/data_specs/Cropland_extent_specs.html#Data-Access

#### Required
License Information: [CC BY Attribution 4.0 International License](https://docs.digitalearthafrica.org/en/latest/data_specs/Cropland_extent_specs.html#License)

Curated by: Digital Earth Africa team

Keywords: Agriculture, Regional Land Cover and Land Use

Last updated: March 2022 (last documentation update)

**Comment by samapriya** [comment]
Hi @hannah-rae 
This has been completed and will be released next week, you can find the [page link here for now](https://gee-community-catalog.org/projects/dea_croplands/). Datasets will be made public on release as well . Closing for now :)

**Comment by hannah-rae** [comment]
@samapriya For some reason, this dataset is no longer public on GEE but I don't see anything in the changelog to explain this. Was this asset made private..?

**Comment by samapriya** [comment]
Just replied to you on chat :) basically it is being updated
