### ISSUE TITLE
Global Food Security-support Analysis Data (GFSAD) Cropland Extent Maps

### ISSUE THREAD

**Issue by hannah-rae** [samapriya/awesome-gee-community-datasets#107]
### Dataset Name
Global Food Security-support Analysis Data (GFSAD) Cropland Extent Maps at 30m resolution for year 2015. Available by region (ordered by suggested priority for adding to catalog):
1. [Africa](https://lpdaac.usgs.gov/products/gfsad30afcev001/)
2. [South Asia, Afghanistan, Iran](https://lpdaac.usgs.gov/products/gfsad30saafgircev001/)
3. [Southeast and Northeast Asia](https://lpdaac.usgs.gov/products/gfsad30seacev001/)
4. [South America](https://lpdaac.usgs.gov/products/gfsad30sacev001/)
5. [Europe, Central Asia, Russia, Middle East](https://lpdaac.usgs.gov/products/gfsad30eucearumecev001/)
6. [Australia, New Zealand, China, Mongolia](https://lpdaac.usgs.gov/products/gfsad30aunzcnmocev001/) 
8. [North America](https://lpdaac.usgs.gov/products/gfsad30nacev001/)

DOI available for each region, e.g., for Africa: 10.5067/MEaSUREs/GFSAD/GFSAD30AFCE.001
See [this article](https://lpdaac.usgs.gov/news/release-of-gfsad-30-meter-cropland-extent-products/) for more info.

Data access: Multiple options via LPDAAC (see [here](https://lpdaac.usgs.gov/products/gfsad30afcev001/#tools))

#### Required
License Information: The dataset does not come with an explicit license, however it is made publicly accessible and various sources can be attributed to show that this is permissive. When I asked the PI about a license, he referred me to quote sources from the following websites:
https://lpdaac.usgs.gov/news/release-of-gfsad-30-meter-cropland-extent-products/ 
https://earthdata.nasa.gov/learn/articles/gfsad
https://lpdaac.usgs.gov/products/gfsad1kcdv001/
https://lpdaac.usgs.gov/products/gfsad1kcmv001/
[www.usgs.gov/wgsc/gfsad30](http://www.usgs.gov/wgsc/gfsad30)
[www.croplands.org](http://www.croplands.org/) 
[www.usgs.gov/WGSC/GHISA](http://www.usgs.gov/WGSC/GHISA) 
https://lpdaac.usgs.gov/news/release-global-hyperspectral-imaging-spectral-library-agricultural-crops-conterminous-united-states/

Curated by: Prasad S. Thenkabail (PI) and team.

Keywords: Agriculture, Global Land Cover and Land Use

Last updated: 2016

**Comment by samapriya** [comment]
This has been completed along with the newly released LGRIP30 Crop extent layer you can [find links to them in the changelog](https://gee-community-catalog.org/changelog/)

**Comment by hannah-rae** [comment]
you are awesome @samapriya !!
