### ISSUE TITLE
ESA CCI Land Cover Africa 20m

### ISSUE THREAD

**Issue by hannah-rae** [samapriya/awesome-gee-community-datasets#111]
### ESA CCI Land Cover Africa 20m
CCI LAND COVER - S2 PROTOTYPE LAND COVER 20M MAP OF AFRICA 2016 - prototype high resolution LC map at 20m over Africa based on 1 year of Sentinel-2A observations from December 2015 to December 2016

DOI: None AFAIK

Data access: Download via https://2016africalandcover20m.esrin.esa.int/download.php

#### Required
License Information: None AFAIK

Curated by: ESA, IIASA

Keywords: Agriculture, Regional Land Cover and Land Use

Last updated: Website last updated 2021, but dataset last updated 2017?

**Comment by samapriya** [comment]
This has been completed, link in changelog
