### ISSUE TITLE
GlobCover 2009 (Global Land Cover Map), ESA

### ISSUE THREAD

**Issue by hannah-rae** [samapriya/awesome-gee-community-datasets#112]
### GlobCover 2009 (Global Land Cover Map)
GlobCover is an ESA initiative which began in 2005 in partnership with JRC, EEA, FAO, UNEP, GOFC-GOLD and IGBP. The aim of the project was to develop a service capable of delivering global composites and land cover maps using as input observations from the 300m MERIS sensor on board the ENVISAT satellite mission. ESA makes available the land cover maps, which cover 2 periods: December 2004 - June 2006 and January - December 2009.

DOI: None AFAIK

Data access: via download on [website](http://due.esrin.esa.int/page_globcover.php) 

#### Required
License Information: No explicit license, but see following data policy.

> Data policy
> The GlobCover products have been processed by ESA and by the Université Catholique de Louvain. They are made available to the public by ESA. You may use the GlobCover land cover map for educational and/or scientific purposes, without any fee on the condition that you credit ESA and the Université Catholique de Louvain as the source of the GlobCover products:
> Copyright notice: © ESA 2010 and UCLouvain
> Accompanied by a link to our ESA DUE GlobCover website: http://due.esrin.esa.int/page_globcover.php
> 
> Should you write any scientific publication on the results of research activities that use GlobCover products as input, you shall acknowledge the ESA GlobCover 2009 Project in the text of the publication and provide ESA with an electronic copy of the publication (due@esa.int).
> If you wish to use the GlobCover 2009 products in advertising or in any commercial promotion, you shall acknowledge the ESA GlobCover 2009 Project and you must submit the layout to ESA for approval beforehand (due@esa.int).

Curated by: ESA and the Université Catholique de Louvain

Keywords: Global Land Cover and Land Use

Last updated: 2009

**Comment by samapriya** [comment]
This has been completed and will be made available in changelog in 1 day
