### ISSUE TITLE
Global human modification v1 (300 m)

### ISSUE THREAD

**Issue by gotEXP** [samapriya/awesome-gee-community-datasets#117]
### Dataset Name
Global Human Modification v1

A paper describing the data and subsequent analyses is available [here](https://essd.copernicus.org/articles/12/1953/2020/essd-12-1953-2020.html), and the data are available in TIFF from [repository](https://zenodo.org/record/5338803#.ZBiglOzMLUI).  

![Screen Shot 2023-03-20 at 12 44 50 PM](https://user-images.githubusercontent.com/94803611/226436874-bb4c868a-b55c-4710-8f3a-665b3e258241.jpg)

#### Earth Engine Snippet if dataset already in GEE
```js
var waterMask = ee.Image("users/DavidTheobald8/gHM/landLakeResOcean300m")
var H2017static = ee.Image("users/DavidTheobald8/gHM/gHMv1_2015_300_60s").multiply(waterMask.remap([1,3],[1,1]))
var H2015change = ee.Image("users/DavidTheobald8/gHM/v1_4/gHMv1_4_2015_300_60cland")
var H2010change = ee.Image("users/DavidTheobald8/gHM/v1_4/gHMv1_4_2010_300_60cland")
var H2000change = ee.Image("users/DavidTheobald8/gHM/v1_4/gHMv1_4_2000_300_60cland")
var H1990change = ee.Image("users/DavidTheobald8/gHM/v1_4/gHMv1_4_1990_300_60cland")

Map.addLayer(H2017static,{}, 'Human Modification v1: 2017 static',true)
Map.addLayer(H2015change,{}, 'Human Modification v1: 2015 change',false)
Map.addLayer(H2010change,{}, 'Human Modification v1: 2010 change',false)
Map.addLayer(H2000change,{}, 'Human Modification v1: 2000 change',false)
Map.addLayer(H1990change,{}, 'Human Modification v1: 1990 change',false)

```
[Sample Code for code editor](https://code.earthengine.google.com/b1e5efb1013c7a9887588aecdf369a7f)

EEApp: 
https://davidtheobald8.users.earthengine.app/view/global-human-modification-change

#### Required
License Information: CC-BY-SA-4.0.

Curated by: David M. Theobald, davidtheobald8@gmail.com

Keywords: Global human modification, land use, human pressures, biodiversity

Last updated: Sept 21, 2021

**Comment by samapriya** [comment]
Hey @gotEXP 
I copied over the assets into a single folder GHM for ease of reference in catalog JSON. Let me know if this looks okay. I also copied your palette from the app script

https://code.earthengine.google.com/?scriptPath=users/sat-io/awesome-gee-catalog-examples:population-socioeconomics/GLOBAL-HUMAN-MODIFICATION

Hoping to include this in today's release

**Comment by samapriya** [comment]
This has been completed and will be released tomorrow
