### ISSUE TITLE
FAO Harmonized World Soil Database V2.0

### ISSUE THREAD

**Issue by wouellette** [samapriya/awesome-gee-community-datasets#118]
A multiband image containing all the attributes of the FAO Harmonized World Soil Database v2.0 Soil Mapping Units (SMUs).
https://data.isric.org/geonetwork/srv/all/catalog.search#/metadata/54aebf11-ec73-4ff8-bf6c-ecff4b0725ea

The band order is the following:
- `HWSD2_ID` (numeric)
- `WISE30s_ID` (string converted to numeric in ascending alphanumeric order)
- `COVERAGE` (numeric)
- `SHARE` (numeric) - unit: `%`
- `WRB4` (string converted to numeric in ascending alphanumeric order)
- `WRB_PHASES` (string converted to numeric in ascending alphanumeric order)
- `WRB2_CODE` (numeric) -- WRB2 is skipped, as it is redundant with WRB2_CODE
- `FAO90` (string converted to numeric in ascending alphanumeric order)
- `KOPPEN` (string converted to numeric in ascending alphanumeric order)
- `TEXTURE_USDA` (numeric)
- `REF_BULK_DENSITY` (numeric) - unit: `g/cm³`
- `BULK_DENSITY` (numeric) - unit: `g/cm³`
- `DRAINAGE` (numeric)
- `ROOT_DEPTH` (numeric)
- `AWC` (numeric) - unit: `mm/m`
- `PHASE1` (numeric)
- `PHASE2` (numeric)
- `ROOTS` (numeric) 
- `IL` (numeric)
- `ADD_PROP` (numeric)

You have an explanation of the attributes page 8-14 of the [product description report](https://www.fao.org/3/cc3823en/cc3823en.pdf).

![image](https://user-images.githubusercontent.com/20474036/227291951-2fcaa1f9-81c3-45f7-b04b-e19a47d11a17.png)

Citation: FAO & IIASA. 2023. Harmonized World Soil Database version 2.0. Rome and Laxenburg. https://doi.org/10.4060/cc3823en

#### Earth Engine Snippet if dataset already in GEE
```js
var hwsd2 = ee.Image('users/soilwatchtech/soil/HWSD2_SMU');

Map.addLayer(hwsd2.select('HWSD2_ID').randomVisualizer(), {}, 'HSWD2 ID');
Map.addLayer(hwsd2.select('WISE30s_ID').randomVisualizer(), {}, 'WISE30s ID');
Map.addLayer(hwsd2.select('COVERAGE').randomVisualizer(), {}, 'COVERAGE');
Map.addLayer(hwsd2.select('SHARE').randomVisualizer(), {}, 'SHARE');
Map.addLayer(hwsd2.select('WRB4').randomVisualizer(), {}, 'WRB4');
Map.addLayer(hwsd2.select('WRB_PHASES').randomVisualizer(), {}, 'WRB_PHASES');
Map.addLayer(hwsd2.select('WRB2_CODE').randomVisualizer(), {}, 'WRB2_CODE');
Map.addLayer(hwsd2.select('FAO90').randomVisualizer(), {}, 'FAO90');
Map.addLayer(hwsd2.select('KOPPEN').randomVisualizer(), {}, 'KOPPEN');
Map.addLayer(hwsd2.select('TEXTURE_USDA').randomVisualizer(), {}, 'TEXTURE_USDA');
Map.addLayer(hwsd2.select('REF_BULK_DENSITY').randomVisualizer(), {}, 'REF_BULK_DENSITY');
Map.addLayer(hwsd2.select('BULK_DENSITY').randomVisualizer(), {}, 'BULK_DENSITY');
Map.addLayer(hwsd2.select('DRAINAGE').randomVisualizer(), {}, 'DRAINAGE');
Map.addLayer(hwsd2.select('ROOT_DEPTH').randomVisualizer(), {}, 'ROOT_DEPTH');
Map.addLayer(hwsd2.select('AWC').randomVisualizer(), {}, 'AWC');
Map.addLayer(hwsd2.select('PHASE1').randomVisualizer(), {}, 'PHASE1');
Map.addLayer(hwsd2.select('PHASE2').randomVisualizer(), {}, 'PHASE2');
Map.addLayer(hwsd2.select('ROOTS').randomVisualizer(), {}, 'ROOTS');
Map.addLayer(hwsd2.select('IL').randomVisualizer(), {}, 'IL');
Map.addLayer(hwsd2.select('ADD_PROP').randomVisualizer(), {}, 'ADD_PROP');
```
GEE code link: [https://code.earthengine.google.com/15b96ef8050b49655222eb2aaa8be136](https://code.earthengine.google.com/15b96ef8050b49655222eb2aaa8be136)

#### Required
License: Attribution-NonCommercial-ShareAlike 3.0 International (CC BY-NC-SA 3.0), https://creativecommons.org/licenses/by-nc-sa/4.0/

Curated by: William Ouellette

Keywords: Soil

Last updated: 23/03/2023

Ticket will be updated with the HWSD2_Layers `ee.Image` once available.

**Comment by samapriya** [comment]
I have no idea how I missed this for so long, releasing this tomorrow. Thanks you as always @wouellette  :)
