### ISSUE TITLE
geeSEBAL-MODIS: Continental scale evapotranspiration based on the surface energy balance for South America

### ISSUE THREAD

**Issue by bcomini** [samapriya/awesome-gee-community-datasets#119]
### geeSEBAL-MODIS: Continental scale evapotranspiration based on the surface energy balance for South America

The geeSEBAL-MODIS Version 0-02 Evapotranspiration (ET) product is an 8-day product produced at 500 meter pixel resolution. The algorithm for ET calculation is based on the SEBAL model and the FAO Penman-Monteith equation, which includes inputs of daily meteorological reanalysis data along with MODIS remotely sensed data products such as vegetation property dynamics, albedo, land cover and land surface temperature (LST).

The pixel values for the layers are the average of all eight days within the period, multiplied by 1000. Images must be multiplied by 0.001 for the actual values. Note that the last 8-day period of each year is a 5 or 6-day composite period, depending on the year.

To visualize the dataset in Google Earth Engine, click the link:

https://code.earthengine.google.com/67cb9bd0e82adb2db1127c024034d5d4

![SA ET](https://user-images.githubusercontent.com/78499248/228029290-75010570-c825-4c09-b448-dbb1f024cbba.jpeg)

#### Code Snippet
```js
var asset_name = ee.ImageCollection("projects/et-brasil/assets/geesebal/myd11a2/sa/v0-02")

```

#### License 
CC-BY-4.0

Curated by: Bruno Comini de Andrade, Anderson Ruhoff, Leonardo Laipelt

Keywords: evapotranspiration, South America, water resources

Last updated: 2023-03-26

**Comment by bcomini** [comment]
Hello! I'd like to publish the dataset I created in GEE awesome community datasets. It is part of my PhD research, and a paper related to it is currently under review at Earth System Science Data.

Thank you

**Comment by samapriya** [comment]
Thank you @bcomini 
I am sure we can include it in our next release sometime the first week of April . Thank you for contributing I will tag you if I have more questions

**Comment by bcomini** [comment]
Thank you, @samapriya!

**Comment by samapriya** [comment]
Hi @bcomini 
I am finally working on this, can you give me more details like units of data, date range of data and so on, it would be great. Usually we wait for research to be published before including in the catalog so let me know if you have a pre print as well

**Comment by bcomini** [comment]
Hi @samapriya,

Here is the info on the dataset:

- date range:
    start: 2002-07-01
    end:  2022-12-31 

- The paper is still under review, but here is the DOI to pre-print:
    DOI: 10.13140/RG.2.2.17579.11041

And this is a table with information about each band in the images of the collection:

[geeSEBAL-MODIS - description.csv](https://github.com/samapriya/awesome-gee-community-datasets/files/11202110/geeSEBAL-MODIS.-.description.csv)

Thank you

**Comment by samapriya** [comment]
This has now been completed and will be released this coming week, I will send you the changelog link when it is live. Thank you for being so patient. Please let me know when this is published and good luck :)

**Comment by samapriya** [comment]
You should be able to visit the unlisted page for now here
https://gee-community-catalog.org/projects/gee_sebal

**Comment by bcomini** [comment]
Thank you so much Samapriya!

I'll let you know once the paper is published.

Best,

Bruno Comini

Engenheiro Ambiental, Ph.D. Recursos Hídricos
*Environmental Engineer, Ph.D.Water Resources*
