### ISSUE TITLE
Missing asset for Global 1-km Cloud Cover 

### ISSUE THREAD

**Issue by jrfep** [samapriya/awesome-gee-community-datasets#12]
Awesome project!

Not sure if this is a good place to put this issue but the links for the Global Cloud Cover dataset are either wrong or outdated. Trying to use the assets in _earthengine_ results in the following error:
```
Image (Error)
Image.load: Image asset 'projects/sat-io/open-datasets/gcc/MODCF_CloudForestPrediction' not found.
```
Same error for the other layers.

**Comment by samapriya** [comment]
Try now, just fixed it, thanks for reporting
