### ISSUE TITLE
Geomorpho90m Geomorphometric Layers

### ISSUE THREAD

**Issue by LuisaAzevedo** [samapriya/awesome-gee-community-datasets#122]
### Dataset Name and Catalog Page
Geomorpho90m Geomorphometric Layers
https://gee-community-catalog.org/projects/geomorpho90/
https://raw.githubusercontent.com/samapriya/awesome-gee-community-datasets/master/docs/projects/geomorpho90.md

### Dataset update, version, and release date
Amatulli, Giuseppe, Daniel McInerney, Tushar Sethi, Peter Strobl, and Sami Domisch. "Geomorpho90m, empirical evaluation and accuracy assessment of global high-resolution geomorphometric layers." Scientific Data 7, no. 1 (2020): 1-18.

### Earth Engine Snippet

```js
var cti = ee.ImageCollection("projects/sat-io/open-datasets/Geomorpho90m/cti");
var tri = ee.ImageCollection("projects/sat-io/open-datasets/Geomorpho90m/tri");
var slope = ee.ImageCollection("projects/sat-io/open-datasets/Geomorpho90m/slope");
```

Sample Code: https://code.earthengine.google.com/?scriptPath=users/sat-io/awesome-gee-catalog-examples:geophysical-biological-biogeochemical/GEOMORPHO90-INDICES

```js
var vrm = ee.ImageCollection("projects/sat-io/open-datasets/Geomorpho90m/vrm");
var roughness = ee.ImageCollection("projects/sat-io/open-datasets/Geomorpho90m/roughness");
var tpi = ee.ImageCollection("projects/sat-io/open-datasets/Geomorpho90m/tpi");
var spi = ee.ImageCollection("projects/sat-io/open-datasets/Geomorpho90m/spi");
```
Sample Code: https://code.earthengine.google.com/?scriptPath=users/sat-io/awesome-gee-catalog-examples:geophysical-biological-biogeochemical/GEOMORPHO90

### Reason for update
I want to use all the 26 variables from the Geomorpho90m in my research but in the dataset available in the GEE there are only 7 variables. Could you please add the ones that are missing in the GEE?

### Updated License
N/A

### Relationship to Dataset
I am a user of the dataset

Sample Code: 
(https://code.earthengine.google.com/?scriptPath=users/sat-io/awesome-gee-catalog-examples:geophysical-biological-biogeochemical/GEOMORPHO90)

Last updated:  2021-04-04

**Comment by samapriya** [comment]
Hi @LuisaAzevedo 
Thanks for creating the ticket. This page has been updated now with all 26 collections
https://gee-community-catalog.org/projects/geomorpho90/

This will be released on our next release, but you can use these datasets now. Hope this helps
