### ISSUE TITLE
MOD10A2 Terra Snow Cover 8-day Global 500m snow cover 2000-2022

### ISSUE THREAD

**Issue by lefsky** [samapriya/awesome-gee-community-datasets#125]
Follow the underlying template when creating a new dataset request for new datasets. This is then submitted for evaluation and inclusion into the community catalog.  

Please edit the markdown text below as needed.

### Dataset Name
Title: MODIS/Terra Snow Cover 8-Day L3 Global 500m SIN Grid
Author: Hall, D. K. and G. A. Riggs.
Publisher: NASA NSIDC DAAC: NASA National Snow and Ice Data Center Distributed Active Archive Center
Publication date: 2021-03-30T12:00:00Z
Publication place: Boulder, Colorado USA
Series: MOD10A2
Edition: 61
DOI:  10.5067/MODIS/MOD10A2.061
URL: https://doi.org/10.5067/MODIS/MOD10A2.061

#### Earth Engine Snippet if dataset already in GEE

var asset_name = ee.ImageCollection("projects/ee-lefskynonprofit/assets/MOD10A2")

Sample Code: Add a sample code, maybe just adding your datasets in the code editor
====================================================================
var eq200=function(i){
  return i.eq(200)}

var mod10a2 = ee.ImageCollection("projects/ee-lefskynonprofit/assets/MOD10A2");

var mod10a2_2001=mod10a2.filterDate("2001-1-1","2001-12-13")
var mod10a2_2001_sum=mod10a2.select(["snowmax"]).map(eq200).
    reduce(ee.Reducer.sum())

var palette=['f7fbff','deebf7','c6dbef','9ecae1','6baed6',
  '4292c6','2171b5','08519c','08306b']

// NOTE: This code only produces the number of days with 
//       detected snow. To produce an index of the fraction
//       of observations that are detected snow, one must
//       calculate the number of days with valid non-snow
//       observations. See User Guide for the MOD10A2 Product

Map.addLayer(mod10a2_2001_sum,{min:0,max:42,palette:palette})
====================================================================
#### Required
License Information: Open
Dataset Provider: NASA NSIDC DAAC at CIRES

Curated by: Michael Lefsky

Keywords: albedo, eight-day, 8-day, geophysical, global, modis, nasa, nsidc, snow, terra, mod10a2

Last updated: Last date the dataset was updated (if known)

**Comment by samapriya** [comment]
Hey @lefsky 
Thanks for creating the issue seems the collection items do not have any metadata except start and end date and system:index. Since this is a non standard collection wondering if we should add any metadata at some point or do you consider this to be mostly used without the need for any additional metadata.

Also would you like me to make a copy and free up your collection space?

**Comment by samapriya** [comment]
This has been processed and will be made available in the next release. Thank you for being patient, check the changelog for links later
