### ISSUE TITLE
Global Forest Canopy Height, 2019 UMD GLAD

### ISSUE THREAD

**Issue by spatialthoughts** [samapriya/awesome-gee-community-datasets#127]
### Dataset Name
Global Forest Canopy Height, 2019

Thumbnail or Snapshot (Optional)
https://glad.umd.edu/dataset/gedi/
#### Earth Engine Snippet if dataset already in GEE
```js
var collection = ee.ImageCollection('users/potapovpeter/GEDI_V27')
```

Sample Code: Add a sample code, maybe just adding your datasets in the code editor
https://code.earthengine.google.co.in/0def37eac724de1bc5685e784dfd33af

#### Required
License is not explicitely mentioned. But as with other GLAD datasets, should be open. Another dataset from the same author mentioned CC-BY license https://glad.umd.edu/dataset/GLCLUC2020

Curated by: Uploaders and curators name(s) include all you think helped.

P. Potapov, X. Li, A. Hernandez-Serna, A. Tyukavina, M.C. Hansen, A. Kommareddy, A. Pickens, S. Turubanova, H. Tang, C.E. Silva, J. Armston, R. Dubayah, J. B. Blair, M. Hofton (2020) Mapping and monitoring global forest canopy height through integration of GEDI and Landsat data. Remote Sensing of Environment, 112165. https://doi.org/10.1016/j.rse.2020.112165

Keywords: GEDI, Canopy, Tree

Last updated: Last date the dataset was updated (if known)
2019

**Comment by samapriya** [comment]
This has been completed and will be made available this week. Thank you for contributing
