### ISSUE TITLE
Ingest MOD02QKM/MYD02QKM NRT MODIS with Metadata

### ISSUE THREAD

**Issue by madeleine-miller** [samapriya/awesome-gee-community-datasets#129]
We are currently looking to ingest a MODIS collection into Earth Engine from the MOD02QKM/MYD02QKM NRT datasets. We had originally been looking to translate and ingest the MOD09GQ collection, but have found that the MOD/MYD02QKM datasets suit our needs a bit better.

We have created a pipeline to scrape and translate the datasets from the LANCE NASA archive and a python script to upload the data to earth engine into an image collection using the ee.data.startIngestion() method. 

We would like to come up with a method of including the metadata for these files in the ingestion process. 

The metadata we would like to include is primarily the start time for each tif as well as the source (NASA LANCE). 

I have attached the script used in our cloud function to ingest data into the collection. The script currently loops through all files in a Google Cloud Bucket and ingests those tifs into an Earth Engine image collection. 

-Madeleine Miller,
 Cartographer, Arctic Eider Society
[ingestMOD02.zip](https://github.com/samapriya/awesome-gee-community-datasets/files/11464074/ingestMOD02.zip)

**Comment by samapriya** [comment]
Feel free to reopen this issue when the ingested collection  is ready to share :) looking forward to it
