### ISSUE TITLE
Global Urban Footprint (TC Chakraborty)

### ISSUE THREAD

**Issue by TC25** [samapriya/awesome-gee-community-datasets#13]
Follow the underlying template when creating new dataset issue entry

### Dataset Name
The objective of the “Global Urban Footprint” (GUF) project is the worldwide mapping of settlements with unprecedented spatial resolution of 0.4 arcsec (~12 m). A total of 180 000 TerraSAR-X and TanDEM-X scenes have been processed to create the GUF. The resulting map shows the Earth in three colors only: black for “urban areas”, white for “land surface” and grey for “water”. This reduction emphasizes the settlement patterns and allows for the analysis of urban structures, and hence the proportion of settled areas, the regional population distribution and the arrangement of rural and urban areas.

More information: https://www.dlr.de/eoc/en/desktopdefault.aspx/tabid-9628/16557_read-40454/
Citation: https://doi.org/10.1016/j.isprsjprs.2017.10.012

#### Earth Engine Snippet
```js
var GUF = ee.ImageCollection("users/tirthankar25/GUF_collection");
```

var GUF = ee.ImageCollection("users/tirthankar25/GUF_collection");

var GUF_mosaic=GUF.mosaic().updateMask(GUF.mosaic().eq(255))

Map.addLayer(GUF_mosaic,{palette:'red'},'Global Urban Footprint')

#### Required
License Information: Publicly available free of charge, but only for non-commercial and scientific purposes (more here: https://www.dlr.de/eoc/en/PortalData/60/Resources/dokumente/guf/DLR-GUF_LicenseAgreement-and-OrderForm.pdf)

Created by: Esch et al.

Curated by: TC Chakraborty

Keywords: Global, Urban, Land Cover, High-resolution

Last updated: 2018-10-30

**Comment by samapriya** [comment]
Hi @TC25 
Unfortunately, I see an issue here seems the use is limited only for the purpose stated in the order form as per their license, which makes open redistribution tricky 

```
Before downloading GUF the intended use (scientific or non-commercial) has to be stated in the order
form section of this document. The granted license is only valid for the purpose stated in the order form.
```

also further republication of the orginial data / in this case reshare and republication would be treated similarly

```
The use of GUF is only allowed for the purpose stated in the order form. The transfer of GUF to third
parties as well as publication of the original data is strictly forbidden
```

**Comment by TC25** [comment]
Thanks for pointing that out @samapriya . In that case, please cancel this request for now. I will contact DLR to check if there is a solution.
