### ISSUE TITLE
Santa Rita Experimental Range(SRER) Drone Imagery 2019

### ISSUE THREAD

**Issue by gponce-ars** [samapriya/awesome-gee-community-datasets#130]
### Santa Rita Experimental Range Drone Imagery 2019
This drone imagery data is used to support a research project investigating the ability to map ecological states across the Santa Rita Experimental Range (SRER) in southern Arizona. The imagery was collected in two campaigns: the first occurred in May 2019 and the second in Aug/Sept 2019. Imagery was collected using a DJI Phantom 4 RTK drone, flying 38 m above the ground and yielding ~1 cm ground sampling distance. The imagery is located at long-term transects and exclosures at SRER. The imagery was to be compared with field mapping of ecological states conducted by Dan Robbinett. The imagery and other data in this repository are connected with the 2021 Ecosphere publication 'Innovations to expand drone data collection and analysis for rangeland monitoring'. 

#### Earth Engine data location 
```js
var full_ortho_srer_may_2019_1cm = ee.Image("users/gponce/usda_ars/assets/images/aes/srer/suas/2019/full_ortho_srer_may_2019_1cm")

var full_ortho_srer_sept_2019_1cm = ee.Image("users/gponce/usda_ars/assets/images/aes/srer/suas/2019/full_ortho_srer_sept_2019_1cm")


```

[Sample code](https://code.earthengine.google.com/3c7279790ca269fc5ccf2fd8fd578856)

[Data visualization tool in GEE.  ](https://bit.ly/srer-drone-2019)

#### License
**GNU GENERAL PUBLIC LICENSE**

Version 3, 29 June 2007

Copyright © 2007 Free Software Foundation, Inc. <https://fsf.org/>

Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.

**Curated by**: Jeffrey K. Gillan, Guillermo E. Ponce Campos

**Keywords**: cloud computing, high-performance computing, monitor,real-time kinematic (RTK), unmanned aerial systems

Last updated: 11/21/2019

Citation: 
```
Gillan, Jeffrey K, Guillermo E Ponce-Campos, Tyson L Swetnam, Alessandra Gorlier, Philip Heilman, and Mitchel P McClaran. “Innovations to Expand Drone Data Collection and Analysis for Rangeland Monitoring.” Ecosphere 12, no. 7 (2021): e03649.
```
[Santa Rita Exprimental Range Website](https://cals.arizona.edu/srer/)

**Comment by samapriya** [comment]
This has now been completed and is [available here](https://gee-community-catalog.org/projects/srer_drone/)
