### ISSUE TITLE
30m African Cropland Layer for 2016 by Integrating Multiple Remote sensing, Crowdsource, and Auxiliary Datasets

### ISSUE THREAD

**Issue by hannah-rae** [samapriya/awesome-gee-community-datasets#131]
### A 30m African Cropland Layer for 2016 by Integrating Multiple Remote sensing, Crowdsource, and Auxiliary Datasets

Description: In order to produce the most accurate cropland layer at 30 m spatial resolution for Africa, the cropland layers extracted from four remote sensing land cover datasets were integrated. The four datasets covered the period 2015 to 2017. Hence, the constructed cropland layer was produced for the nominal year 2016. To build the final layer, the cropland mapping accuracies of the four cropland layers were firstly investigated at the units of Agro-ecological zones. Then, the best cropland layers for all zones were spatially joined. The resulted cropland layer is a binary mask with higher overall accuracy than individual layers and more consistent with FAO official statistics.

![Preview](https://www.scidb.cn/static/cover/journal/V1798574876305653760.jpg)

Map files can be downloaded at: https://figshare.com/articles/dataset/A_30m_African_Cropland_Layer_for_2016_by_Integrating_Multiple_Remote_sensing_Crowdsource_and_Auxiliary_Datasets_/13520141

DOI: https://doi.org/10.6084/m9.figshare.13520141.v1

#### Required
License Information: CC-BY 4.0

Curated by: Mohsen Nabil , Miao Zhang, Bingfang Wu, et al.

Keywords: Agriculture, Africa

Last updated: 2021 (based on [associated publication](https://www.tandfonline.com/doi/full/10.1080/20964471.2021.1914400))

**Comment by samapriya** [comment]
This will be included in the release tomorrow. Thank you for contributing @hannah-rae :)

**Comment by hannah-rae** [comment]
You are awesome @samapriya !!! Thank you.
