### ISSUE TITLE
Global extreme heat hazard 100 & 20 & 5 Year Return Period

### ISSUE THREAD

**Issue by pinkychow1010** [samapriya/awesome-gee-community-datasets#132]
### Global extreme heat hazard 100 & 20 & 5 Year Return Period

Download URL: https://datacatalog.worldbank.org/search/dataset/0040194/Global-extreme-heat-hazard

Published by the World Bank (2017), this is a global data layer for extreme heat hazard, which is classified based on an existing and widely accepted heat stress indicator, the Wet Bulb Globe Temperature (WBGT, in °C) – more specifically the daily maximum WGBT. The WBGT has an obvious relevance for human health, but it is relevant in all kinds of projects and sectors, including infrastructure related, as heat stress affects personnel and stakeholders, and therefore the design of buildings and infrastructure. Heat stress studies in the scientific literature that make use of the WBGT apply thresholds of 28°C and 32°C to categorise heat stress risk. The damaging intensity thresholds are applied following this definition of slight/low (<28°C), moderate/high (28-32°C) and severe/very high (>32°C) heat stress. This dataset is licensed under Creative Commons Attribution 4.0. Point of contact: sfraser@worldbank.org

![Thumbnail or Snapshot (Optional)](https://www.geonode-gfdrrlab.org/uploaded/thumbs/layer-70e21a5e-fe9d-11e6-9529-040146164b01-thumb.png)

Sample Code: 
```js
var dataset_100y_return = ee.ImageCollection('path/extreme-heat-hazard').select('100y-return').first();
var dataset_20y_return = ee.ImageCollection('path/extreme-heat-hazard').select('20y-return').first();
var dataset_5y_return = ee.ImageCollection('path/extreme-heat-hazard').select('5y-return').first();
```
Extra Info: There are three global GeoTIFF files in total, which can be combined into one dataset with 3 bands: 5 year, 20 year and 100 year return period.

Download Tool/Code snippets, if any: NA

#### Required
License Information: This dataset is classified as Public under the Access to Information Classification Policy. Users inside and outside the Bank can access this dataset. License: Creative Commons Attribution 4.0

Curated by: Koen De Ridder, Dirk Lauwaet, Hans Hooyberghs and Filip Lefebre from VITO (Author)
[VITO - Extreme heat Final_report_v2.pdf](https://github.com/samapriya/awesome-gee-community-datasets/files/11680662/VITO.-.Extreme.heat.Final_report_v2.pdf)

Keywords: Hazard Assessment, Extreme Heat, Climatology, Climate Change

Last updated: Mar 1, 2017

**Comment by samapriya** [comment]
This has been completed you can find the links in the changelog
