### ISSUE TITLE
Global human modification

### ISSUE THREAD

**Issue by gotEXP** [samapriya/awesome-gee-community-datasets#136]
Follow the underlying template when creating an update request for an existing dataset in the awesome-gee-community-catalog.

Please edit the markdown text below as needed

### Dataset Name and Catalog Page
Global human modification
https://gee-community-catalog.org/projects/ghm/

### Dataset update, version, and release date
Global human modification v1.5
This updates v1 to v1.5, which provides additional datasets on 6 major stressors at 300 m resolution and two additional time steps (1995 and 2005), as well as reflecting minor data update and processing refinements. Users are advised to use these data instead of "CSP gHM: Global Human Modification" (https://developers.google.com/earth-engine/datasets/catalog/CSP_HM_GlobalHumanModification). 
These data were updated June 17, 2023. The v1.5 datasets can also be accessed at: zenodo.org/deposit/7534895.

### Updated dataset link
See sample code below...

### Reason for update
This updates v1 to v1.5, which provides additional datasets on 6 major stressors at 300 m resolution and two additional time steps (1995 and 2005), as well as reflecting minor data updates and processing refinements. Specifically: 
1. Datasets are provided for each of the 6 stressor groups: built-up areas (BU), agricultural/timber harvest (AG), extractive energy and mining (EX), human intrusions (HI), natural system modifications (NS), and transportation & infrastructure (TI), available now at 300 m resolution for each of the time steps in the 1990-2015 time series.

2. It provides the addition datasets for the years 1995 and 2005, calculated using linear interpolation when stressor data do not provide data at the specific year.

3. The ESA 150 m water-mask dataset ([Lamarche et al. 2017](https://www.mdpi.com/2072-4292/9/1/36)) was used to provide better and more consistent alignment of datasets at the ocean-land-inland water interfaces.

4. The built-up stressor uses an updated version of the Global Human Settlement Layer (v2022A).

5. Values provided are 32-bit floating point values, with human modification values ranging from 0.0 to 1.0.

### Updated License
N/A

### Relationship to Dataset
Owner

Sample Code:
https://code.earthengine.google.com/7e2d479c6ef9f4ed9e6d29bf2ee09971

Last updated: June 17, 2023

**Comment by samapriya** [comment]
This has been updated you can find the new information at the same link

**Comment by gotEXP** [comment]
Thanks for your quick update!

**I noticed a problem, however.** It does look like the asset IDs you generated with:
""projects/sat-io/open-datasets/GHM..."
are not accessible or don't exist. Can you please double-check? I don't believe I have access to trouble-shoot this further -- apologies if I do.

Thanks!!!

**Comment by gotEXP** [comment]
All assets are all accessible now, beautiful, thanks!

**Comment by samapriya** [comment]
Perfect, stressors are in collections now
