### ISSUE TITLE
EE snippet for high resolution mining footprints points to gHM

### ISSUE THREAD

**Issue by gotEXP** [samapriya/awesome-gee-community-datasets#137]
Follow the underlying template when creating a bug request for an existing dataset in the the community catalog.  

Please edit the markdown text below as needed

#### Describe the bug
Looks like the recently released mining footprints ([URL](https://gee-community-catalog.org/projects/global-mining/)) has a link to the global human modification EEApp, ironically! (maybe the form was copied over from my previous page?).

That is, this is incorrect:
Earth Engine App: https://davidtheobald8.users.earthengine.app/view/global-human-modification-change

Thanks!

**Comment by samapriya** [comment]
Indeed it was a carry over, thank you for the catch. Fix has been pushed should update in few minutes automatically. Thank you for the catch :)
