### ISSUE TITLE
ESA's CCI Biomass 

### ISSUE THREAD

**Issue by BuddyVolly** [samapriya/awesome-gee-community-datasets#138]
Follow the underlying template when creating a new dataset request for new datasets. This is then submitted for evaluation and inclusion into the community catalog.  

Please edit the markdown text below as needed.

### Dataset Name
https://catalogue.ceda.ac.uk/uuid/af60720c1e404a9e9d2c145d2b2ead4e

ESA Biomass Climate Change Initiative: Global datasets of forest above-ground biomass for the years 2010, 2017, 2018, 2019 and 2020, v4

Santoro, M.; Cartus, O. (2023): ESA Biomass Climate Change Initiative (Biomass_cci): Global datasets of forest above-ground biomass for the years 2010, 2017, 2018, 2019 and 2020, v4. NERC EDS Centre for Environmental Data Analysis, 21 April 2023. doi:10.5285/af60720c1e404a9e9d2c145d2b2ead4e. https://dx.doi.org/10.5285/af60720c1e404a9e9d2c145d2b2ead4e

Sample Code: ee.ImageCollection('ESA_CCI_BIOMASS_v4/2010')

Extra Info: Feel free to add any optional details 

Download Tool/Code snippets, if any: from website https://catalogue.ceda.ac.uk/uuid/af60720c1e404a9e9d2c145d2b2ead4e

#### Required
License Information: 
https://artefacts.ceda.ac.uk/licences/specific_licences/esacci_biomass_terms_and_conditions.pdf

Curated by: Uploaders and curators name(s) include all you think helped.

Keywords: Global Biomass, ESA, CCI

Last updated: 21-04-2023

**Comment by samapriya** [comment]
Updated license information adding for more context and follow on

```
The CCI BIOMASS datasets have been processed by the CCI BIOMASS consortium led by the University
of Aberystwyth (U.K.). They are made available to the public by ESA and the consortium. You may use
one or several CCI BIOMASS products for educational and/or scientific purposes, without any fee on
the condition that you credit the ESA Climate Change Initiative and in particular its BIOMASS project
as the source of the data:
Copyright notice: © ESA Climate Change Initiative - BIOMASS project 2023.
Any scientific publication on the results of research activities based on CCI BIOMASS data products
should acknowledge the ESA CCI BIOMASS project in the text of the publication and provide the project
with an electronic copy of the publication (see https://climate.esa.int/en/projects/biomass/ for
contacts).
If CCI BIOMASS data products are to be used in advertising or commercial promotion, the ESA CCI
BIOMASS project should be acknowledged and the layout should be submitted to the project for
approval beforehand (see https://climate.esa.int/en/projects/biomass/ for contacts).
```

**Comment by samapriya** [comment]
This has been conditionally completed with some checks remaining and will be released later this week today. Thank you for contributing I will update the issue with the dataset link or you can find it in [the changelog in 2-3 days](https://gee-community-catalog.org/changelog/)

**Comment by BuddyVolly** [comment]
Awesome, thanks a lot!
