### ISSUE TITLE
Global 30m Landsat Tree Canopy Version 4

### ISSUE THREAD

**Issue by Yingjie4Science** [samapriya/awesome-gee-community-datasets#139]
This data is not available on GEE. I was wondering if you might be interested in adding it. 

### Dataset Name
Global 30m Landsat Tree Canopy Version 4
See this link for all the needed information
https://lcluc.umd.edu/metadata/global-30m-landsat-tree-canopy-version-4

**Comment by samapriya** [comment]
Hi @Yingjie4Science 
Can you help me find the license for using and redistributing data? Usually, I ask users to submit a description of dataset, citation, and license information at the bare minimum for me to assess. Let me know if you can add it to this Github issue and I am happy to look into bringing this dataset into GEE

**Comment by Yingjie4Science** [comment]
@samapriya Perhaps this statement relates to the license -- "This data is open to the public and browse images are freely available without
restriction.  Satellite data products may require a NASA Earthdata Login username
and password.  To obtain a NASA Earthdata Login account, please visit
https://urs.earthdata.nasa.gov/users/new." See https://e4ftl01.cr.usgs.gov/MEASURES/GFCC30TC.003/

**Comment by samapriya** [comment]
This has now been completed you can find the dataset here https://gee-community-catalog.org/projects/global_tcc/
