### ISSUE TITLE
Global monthly hydrology and water quality datasets (DynQual)

### ISSUE THREAD

**Issue by spatialthoughts** [samapriya/awesome-gee-community-datasets#143]
### Dataset description

Dynamical surface water quality model (DynQual) is a new model for simulating water temperature (Tw) and concentrations of total dissolved solids (TDS), biological oxygen demand (BOD) and fecal coliform (FC).

Global 10km output data from the dynamical surface water quality model (DynQual). Output data are provided at monthly temporal resolution from 1980-2019

Output data includes:
- Discharge (m3 s-1)
- Channel storage (m3)
- Water temperature (°C)
- Total dissolved solids (TDS) concentration (mg l-1)
- Biological oxygen demand (BOD) concentration (mg l-1)
- Fecal coliform (FC) concentration  (cfu 100ml-1)

Dataset Size: 18.9 GB

Download page: https://zenodo.org/record/7139222

### Earth Engine Snippet if dataset already in GEE

n/a

### Enter license information

License: Creative Commons Attribution 4.0 International Public License

### Keywords

water quality

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
Here is the pre-release [version](https://gee-community-catalog.org/projects/dynqual/). I will open the ACL for access tomorrow. I could not get Storage to work unfortunately but I have reached out to Michelle for help reprocess the NC file. Closing this issue for now feel free to add comments or reach out. This will be released tomorrow
