### ISSUE TITLE
[NPP-VIIRS]: Add data for 2021 and 2022

### ISSUE THREAD

**Issue by aamir-s18** [samapriya/awesome-gee-community-datasets#145]
### Provide Dataset Link

https://gee-community-catalog.org/projects/npp_viirs_ntl/

### Describe the update

Hey, it would be great if you could add the data for the [NPP-VIIRS](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/YGIVCD) for the years 2021 & 2022. Thank you!

### Relevant additional information

[Here](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/YGIVCD) the datacatalog. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
This has now been completed. I will add information on the page about updates to the dataset. Thank you for update suggestions
