### ISSUE TITLE
Brazilian daily weather gridded data (BR-DWGD)

### ISSUE THREAD

**Issue by AlexandreCandidoXavier** [samapriya/awesome-gee-community-datasets#146]
### Contact Details

alexandre.xavier@ufes.br

### Dataset description

These dataset presents  the daily meteorological gridded data set from Brazil (BR-DWGD). The variables are Precipitation (pr, mm); maximum and minimum temperature (Tmax, tmin, °C);  solar radiation (Rs, MJ/m2); relative humidity (RH, %); wind speed at 2 meters (u2, m/s) and evapotranspiration (ETo, mm). The temporal coverage is 1961/01/01-2020/07/31 (except precipitation: 1961/01/01-2022/12/31) and has the spatial resolution 0.1° x 0.1°, just for Brazil territory. 

Data citation:

Xavier, A. C., Scanlon, B. R., King, C. W., & Alves, A. I. (2022). New improved Brazilian daily weather gridded data (1961–2020). International Journal of Climatology, 42( 16), 8390– 8404. https://doi.org/10.1002/joc.7731

### Earth Engine Snippet if dataset already in GEE

for example
```js
var asset_name = ee.ImageCollection("path to your collection")
```
Sample Code: Add a sample code maybe just adding your datasets in the code editor

### Enter license information

The BR-DWGD datasets are provided for non-commercial use under the CC BY 4.0 Attribution 4.0 International license.

Data Website: [here](https://sites.google.com/site/alexandrecandidoxavierufes/brazilian-daily-weather-gridded-data)

Data: [here](https://drive.google.com/drive/u/1/folders/11-qnvwojirAtaQxSE03N0_SUrbcsz44N)

### Keywords

Brazil, maximum temperature, minimum temperature, precipitation, solar radiation, wind speed, relative humidity, evapotranspiration

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
So CC BY 4.0 Attribution 4.0 International license allows for commercial use did you mean to say [Attribution-NonCommercial 4.0 International](http://creativecommons.org/licenses/by-nc/4.0/). This would be the license type to prevent commercial use

**Comment by samapriya** [comment]
This is now completed and the page is located here http://gee-community-catalog.org/projects/br_dwgd/. Thank you for submitting the dataset request

**Comment by AlexandreCandidoXavier** [comment]
Thanks Samapriya, you did/do an amazing job!

Best regards.

Alexandre

Em qui., 24 de ago. de 2023 às 14:33, Samapriya Roy <
***@***.***> escreveu:
