### ISSUE TITLE
[Bug]: JRC-GHSL-2023 missing data in SMOD?

### ISSUE THREAD

**Issue by davidtheobald8** [samapriya/awesome-gee-community-datasets#147]
### Provide Dataset Link

http://gee-community-catalog.org/projects/ghsl/

### Describe the bug

Hi, I've been able to access the GHSL SMOD dataset for 2030 (per your example script), but I get non-access errors for the remainder of the years (1975-2025). 

Here's a [link](https://code.earthengine.google.com/78a81c0d706bf14296e92fc5b5affe62) to an example script.

Thanks!
Cheers,
Dave T.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
I have only ingested 2030 for SMOD. I might add the other years later, not really a bug but I can look into this

**Comment by samapriya** [comment]
There you go :) and updated the page to reflect the new collection
https://code.earthengine.google.com/74f5d33fba9bf7a4820a3ce8b08a5a39
