### ISSUE TITLE
ANUSPLIN Gridded Climate Dataset

### ISSUE THREAD

**Issue by EricRJensen** [samapriya/awesome-gee-community-datasets#149]
### Contact Details

ClimateEngine.org staff, climateengine@gmail.com

### Dataset description

**Description**
The ANUSPLIN Gridded Climate Dataset for Canada is a station based interpolated dataset produced using the Australian National University Spline (ANUSPLIN) model. It is produced by Agriculture and Agri-Food Canada and covers all of Canada. The dataset is available from 1950-2015 at daily and monthly timesteps for maximum temperature, minimum temperature, and total precipitation at 10km (0.1 degree) resolution.

**Spatial extent:** United States and Canada
**Spatial resolution:** 10-km (~0.1-deg)
**Temporal resolution:** Daily and monthly
**Time span:** 1950-01-01 to 2015-12-31
**Update frequency:** Static

**Variables**
Minimum temperature, 2m (‘maxt’)

- Units: Degrees Celsius
- Scale factor: 1.0

Maximum temperature, 2m (‘mint’)

- Units: Degrees Celsius
- Scale factor: 1.0

Precipitation (‘pcp’)

- Units: Millimeters
- Scale factor: 1.0

**External link**
Daily: https://cfs.nrcan.gc.ca/projects/3/4 
Monthly: https://cfs.nrcan.gc.ca/projects/3/3 

**Citation**
- Hutchinson, M. F., McKenney, D.W., Lawrence, K., Pedlar, J.H., Hopkinson, R.F., Milewska, E., Papadopol, P. (2009). "Development and testing of Canada-Wide Interpolated Spatial Models of Daily Minimum-Maximum Temperature and Precipitation for 1961-2003." American Meteorological Society(April): 725-741.
- McKenney, D. W., Hutchinson, M.F., Papadopol, P., Lawrence, K., Pedlar, J., Campbell, K., Milewska, E., Hopkinson, R., Price, D., Owen, T. (2011). "Customized spatial climate models for North America." Bulletin of American Meteorological Society-BAMS December: 1612-1622.

**Link to documentation**
https://support.climateengine.org/article/48-anusplin

### Earth Engine Snippet if dataset already in GEE

for example
```js
// Read in daily and monthly Image Collections and get single image from each collection
var anuspline_m_ic = ee.ImageCollection('projects/climate-engine-pro/assets/ce-anusplin-monthly')
var anuspline_m_i = anuspline_m_ic.first()
var anuspline_d_ic = ee.ImageCollection('projects/climate-engine-pro/assets/ce-anusplin-daily')
var anuspline_d_i = anuspline_d_ic.first()

// Print each single image to see bands 
print(anuspline_m_i)
print(anuspline_d_i)

// Visualize each band from each single image
var prec_palette = ["#ffffcc", "#c7e9b4", "#7fcdbb", "#41b6c4", "#1d91c0", "#225ea8", "#0c2c84"]
var temp_palette = ["#b2182b", "#ef8a62", "#fddbc7", "#f7f7f7", "#d1e5f0", "#67a9cf", "#2166ac"].reverse()
Map.addLayer(anuspline_m_i.select('pcp'), {min: 0, max: 200, palette: prec_palette}, 'pcp, monthly')
Map.addLayer(anuspline_m_i.select('mint'), {min: -30, max: 30, palette: temp_palette}, 'mint, monthly')
Map.addLayer(anuspline_m_i.select('maxt'), {min: -30, max: 30, palette: temp_palette}, 'maxt, monthly')

Map.addLayer(anuspline_d_i.select('pcp'), {min: 0, max: 10, palette: prec_palette}, 'pcp, daily')
Map.addLayer(anuspline_d_i.select('mint'), {min: -30, max: 30, palette: temp_palette}, 'mint, daily')
Map.addLayer(anuspline_d_i.select('maxt'), {min: -30, max: 30, palette: temp_palette}, 'maxt, daily')
```

### Enter license information

Data are subject to the Government of Canada Open Data Licence Agreement: https://open.canada.ca/en/open-government-licence-canada. The terms of this Agreement govern your use and reproduction of the data instead of the copyright reproduction statements found in Important Notices on the Agriculture and Agri-Food Canada website.

### Keywords

climate, precipitation, temperature, AAFC, daily, monthly, reanalysis

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
Check changelog on next release. This has now been conditionally completed

**Comment by samapriya** [comment]
Check changelog on next release. This has now been conditionally completed
