### ISSUE TITLE
US National Wetlands Inventory (NWI)

### ISSUE THREAD

**Issue by giswqs** [samapriya/awesome-gee-community-datasets#15]
The National Wetlands Inventory (NWI) would be a great addition to this awesome GEE community datasets. 

The US Fish and Wildlife Service (FWS) is the principal US Federal agency tasked with providing information to the public on the status and trends of our Nation's wetlands. The US FWS National Wetlands Inventory (NWI) is a publicly available resource that provides detailed information on the abundance, characteristics, and distribution of US wetlands. NWI data are used by natural resource managers, within the US FWS and throughout the Nation, to promote the understanding, conservation and restoration of wetlands.

Download: https://www.fws.gov/wetlands/data/data-download.html
Legend: https://www.fws.gov/wetlands/data/Mapper-Wetlands-Legend.html

I have created a spreadsheet with the links to download data by state
https://docs.google.com/spreadsheets/d/16jat_VLTXDVz0Gl8dnAJxwv48yZ-e-wmvockWSL0cAE

![](https://i.imgur.com/EdAkJ8R.jpg)
![](https://i.imgur.com/uXcdSCS.png)

**Comment by samapriya** [comment]
Seems the link for MT is broken (https://www.fws.gov/wetlands/data/State-Downloads/MT_shapefile_wetlands.zip)  but everything else seems to be working, thanks @giswqs anyway to get the MT shapefile? The geodatabase link seemed to work so I tried using ogr2ogr to make the conversion but getting quite a few errrors

**Comment by giswqs** [comment]
Let me contact the NWI program to get the data for MT. I will let you once I get it. Thanks.

**Comment by giswqs** [comment]
@samapriya The broken link has been fixed. Please try again. 
https://www.fws.gov/wetlands/data/State-Downloads/MT_shapefile_wetlands.zip

**Comment by samapriya** [comment]
Thanks @giswqs 
That seems to work, I might create a state-specific output from the wetlands files and the rest can remain as in subfolders , will keep you posted with updates. An interesting discovery I made was wetland files were mixed geometry (point and polygon)

**Comment by giswqs** [comment]
That's interesting to know. I thought they were all polygon geometry. If you find any issues with a specific file, you might post it here. We can provide feedback to the NWI team so that they improve the data in the future.

**Comment by samapriya** [comment]
This has been interesting but here is the latest, https://samapriya.github.io/awesome-gee-community-datasets/projects/nwi/. Going to keep this ticket open for review

**Comment by giswqs** [comment]
@samapriya Fantastic work!! Thank you for preprocessing this immense dataset and ingesting it to GEE so quickly. Very nice to see each state has one single FeatureCollection without multiple parts. I am sure the GEE community will greatly benefit from this dataset. I just tested the datasets, and it seems to work well.

**Comment by samapriya** [comment]
I am closing this issue, feel free to reopen as needed , looking forward to the next big one :)
