### ISSUE TITLE
Climate Hazards Group InfraRed Precipitation with Station data (CHIRPS)

### ISSUE THREAD

**Issue by EricRJensen** [samapriya/awesome-gee-community-datasets#151]
### Contact Details

ClimateEngine.org staff, climateengine@gmail.com

### Dataset description

**Description**
The Climate Hazards Center InfraRed Precipitation With Station Data-Prelim (CHIRPS-Prelim) is a blend of CHIRPS data with in situ precipitation data to unbias the data and enhance its accuracy. The process of generating CHIRPS- Prelim is similar to the CHIRPS process, with the main difference being its reliance on Global Telecommunication System (GTS) stations only, which are available in near-real time. Blending of CHIRP with GTS-only stations allows for the latency of CHIRPS- Prelim to be <5 days. Note that, in general, the differences in CHIRPS-Prelim and CHIRPS are within acceptable limits, as both data sets share the same climatological mean.

This dataset is to be used in conjunction with CHIRPS Pentad/Daily collections, which are Earth Engine assets at:

- UCSB-CHG/CHIRPS/PENTAD
- UCSB-CHG/CHIRPS/DAILY

**Spatial extent:** Global
**Spatial resolution:** 4.8-km grid (1/20 deg)
**Temporal resolution:** 5-day (pentad)
**Time span:** 2015 to present
**Update frequency:** Updated weekly

**Variables**
Precipitation (‘precipitation’)

- Units: Millimeters
- Scale factor: 1.0

**External link**
https://www.chc.ucsb.edu/data/chirps 

**Citation**
Funk, C.C., Peterson, P.J., Landsfeld, M.F., Pedreros, D.H., Verdin, J.P., Rowland, J.D., Romero, B.E., Husak, G.J., Michaelsen, J.C., and Verdin, A.P., 2014, A quasi-global precipitation time series for drought monitoring: U.S. Geological Survey Data Series 832, 4 p., http://dx.doi.org/10.3133/ds832

**Link to documentation**
https://support.climateengine.org/article/53-chirps

### Earth Engine Snippet if dataset already in GEE

```js
// Read in Image Collections and get single image
var chirps_ic = ee.ImageCollection('projects/climate-engine-pro/assets/ce-chirps-prelim-pentad')
var chirps_i = chirps_ic.first()

// Print single image to see bands 
print(chirps_i)

// Visualize precipitation for single image
var prec_palette = ["#ffffcc", "#c7e9b4", "#7fcdbb", "#41b6c4", "#1d91c0", "#225ea8", "#0c2c84"]
Map.addLayer(chirps_i.select('precipitation'), {min: 0, max: 200, palette: prec_palette}, 'precipitation')
```

### Enter license information

This datasets are in the public domain. To the extent possible under law, Pete Peterson has waived all copyright and related or neighboring rights to Climate Hazards Group Infrared Precipitation with Stations (CHIRPS).

### Keywords

precipitation, near real-time, climate, CHIRPS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
This will be made available in the next release check changelog for more
