### ISSUE TITLE
High Resolution Deterministic Prediction System (HRDPS)

### ISSUE THREAD

**Issue by EricRJensen** [samapriya/awesome-gee-community-datasets#155]
### Contact Details

ClimateEngine.org staff, climateengine@gmail.com

### Dataset description

**Description**
The High Resolution Deterministic Prediction System (HRDPS) provides useful numerical simulations of temperature over large areas. Climate Engine is ingesting only the band containing temperature at 2m above ground level, but HRDPS also produces bands for precipitation, cloud cover, wind speed and direction, humidity, and others. These numerical simulations can be used for air quality modeling and forecasting, climate and wildfire modeling, and extreme weather forecasting. Users who will benefit most from using these new data are those for whom a detailed forecast of surface temperatures and winds is important. The 2.5 km forecasts could add much value especially during the change of seasons and in wintertime when rapid changes in temperature and winds cause phase transitions of precipitation (freezing rain to snow to rain for example). HRDPS is the high resolution counterpart to the RDPS dataset.

**Spatial extent:** Canada
**Spatial resolution:** 2.5 km grid (1/24 deg)
T**emporal resolution:** Daily
**Time span:** 2015-04-23 to present
**Update frequency:** Updated daily with 1 day lag time

**Variables**
Mean temperature (‘Tavg’)

- Units: Degrees Celsius
- Scale factor: 1.0

**External link**
https://weather.gc.ca/grib/grib2_HRDPS_HR_e.html 

**Citation**
Milbrandt, J. A., Bélair, S., Faucher, M., Vallée, M., Carrera, M. L., & Glazer, A. (2016). The pan-Canadian high resolution (2.5 km) deterministic prediction system. Weather and Forecasting, 31(6), 1791-1816.

**Link to documentation**
https://support.climateengine.org/article/68-hrdps

### Earth Engine Snippet if dataset already in GEE

```js
// Read in Image Collection and get first image 
var hrdps_ic = ee.ImageCollection('projects/climate-engine-pro/assets/ce-hrdps-daily')
var hrdps_i = hrdps_ic.first()

// Print first image to see bands
print(hrdps_i)

// Visualize temperature from first image
var temp_palette = ["#b2182b", "#ef8a62", "#fddbc7", "#f7f7f7", "#d1e5f0", "#67a9cf", "#2166ac"].reverse()
Map.addLayer(hrdps_i.select('Tavg'), {min: -10, max: 20, palette: temp_palette}, 'Tavg')
```

### Enter license information

Data are subject to the Government of Canada Open Data Licence Agreement: https://open.canada.ca/en/open-government-licence-canada. The terms of this Agreement govern your use and reproduction of the data instead of the copyright reproduction statements found in Important Notices on the Agriculture and Agri-Food Canada website.

### Keywords

climate, temperature, daily, Canada, near real-time

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
Check changelog on next release. This has now been conditionally completed
