### ISSUE TITLE
MERRA2 Fire Weather Index (FWI)

### ISSUE THREAD

**Issue by EricRJensen** [samapriya/awesome-gee-community-datasets#156]
### Contact Details

ClimateEngine.org staff, climateengine@gmail.com

### Dataset description

**Description**
The Global Fire WEather Database (GFWED) integrates different weather factors influencing the likelihood of a vegetation fire starting and spreading at daily temporal resolution and a ~50-km (0.5-deg x 0.625-deg) spatial resolution from 1980-present. It is based on the Fire Weather Index (FWI) System, the most widely used fire weather system in the world. The FWI System was developed in Canada, and is composed of three moisture codes and three fire behavior indices. The moisture codes capture the moisture content of three generalized fuel classes and the behavior indices reflect the spread rate, fuel consumption and intensity of a fire if it were to start. Details on the development and testing of GFWED can be found in Field et al. (2015) and the evaluation of GFWED products in Field (2020a). Applications of the FWI System can be found in Taylor and Alexander (2006) and technical descriptions are provided by van Wagner (1987) and Dowdy et al. (2009).

**Spatial extent:** Global
**Spatial resolution:** ~50-km (0.5-deg x 0.625-deg)
**Temporal resolution:** Daily
**Time span:** 1980-04-02 to present
**Update frequency:** Updated daily with 5 month lag time

**Variables**
Fire Weather Index (‘FWI’)

- Units: Unitless
- Scale factor: 1.0

**External link**

- https://gmao.gsfc.nasa.gov/reanalysis/MERRA-2/ 
- https://data.giss.nasa.gov/impacts/gfwed/ 

**Citation**

- Field, R.D., A.C. Spessa, N.A. Aziz, A. Camia, A. Cantin, R. Carr, W.J. de Groot, A.J. Dowdy, M.D. Flannigan, K. Manomaiphiboon, F. Pappenberger, V. Tanpipat, and X. Wang, 2015: Development of a global fire weather database. Nat. Hazards Earth Syst. Sci., 15, 1407-1423, doi:10.5194/nhess-15-1407-2015.
- MERRA-2 Overview: The Modern-Era Retrospective Analysis for Research and Applications, Version 2 (MERRA-2), Ronald Gelaro, et al., 2017, J. Clim., doi: 10.1175/JCLI-D-16-0758.1

**Link to documentation**
https://support.climateengine.org/article/71-merra2-fwi

### Earth Engine Snippet if dataset already in GEE

```js
// Read in Image Collection and get first image
var merra2_ic = ee.ImageCollection('projects/climate-engine-pro/assets/ce-merra2_fwi-daily')
var merra2_i = merra2_ic.filterDate('2020-08-01', '2020-08-05').first()

// Print first image to see bands
print(merra2_i)

// Visualize select bands from first image — additional bands are present in the Image Collection
var fwi_palette = ["#b2182b", "#ef8a62", "#fddbc7", "#f7f7f7", "#d1e5f0", "#67a9cf", "#2166ac"].reverse()
Map.addLayer(merra2_i.select('FWI'), {min: 0, max: 100, palette: fwi_palette}, 'FWI')
```

### Enter license information

NASA promotes the full and open sharing of all data with research and applications communities, private industry, academia, and the general public.

### Keywords

climate, fire, wildfire, NASA, MERRA2, daily, global, GFWED

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
This has now been completed you can find links in the changelog here
https://gee-community-catalog.org/changelog/

Thank you for contributing :)
