### ISSUE TITLE
Regional Deterministic Precipitation Analysis (RDPA)

### ISSUE THREAD

**Issue by EricRJensen** [samapriya/awesome-gee-community-datasets#157]
### Contact Details

ClimateEngine.org staff, climateengine@gmail.com

### Dataset description

**Description**
The Regional Deterministic Precipitation Analysis (RDPA) based on the Canadian Precipitation Analysis (CaPA) system is on a domain that corresponds to that of the operational regional model, i.e. the Regional Deterministic Prediction System (RDPS-LAM3D) except for areas over the Pacific Ocean where the western limit of the RDPA domain is slightly shifted eastward with respect to the regional model domain. The resolution of the RDPA analysis is identical to the resolution of the operational regional system RDPS LAM3D. The fields in the RDPA GRIB2 dataset are on a polar-stereographic (PS) grid covering North America and adjacent waters with a 10 km resolution at 60 degrees north, 2003-present.

**Spatial extent:** United States and Canada
**Spatial resolution:** 10.0 km grid (1/11 deg)
**Temporal resolution:** Daily
**Time span:** 2003-01-01 to present
**Update frequency:** Updated daily with 5 month lag time

**Variables**
Precipitation (‘precip’)

- Units: Millimeters
- Scale factor: 1.0

**External link**
https://weather.gc.ca/grib/grib2_RDPA_ps10km_e.html 

**Citation**

- [Canadian Precipitation Analysis (CaPA)](https://collaboration.cmc.ec.gc.ca/cmc/cmoi/product_guide/docs/lib/capa_information_leaflet_20141118_en.pdf) Methodology system
- Fillion, L., Tanguay, M., Lapalme, E., Denis, B., Desgagne, M., Lee, V., ... & Pagé, C. (2010). The Canadian regional data assimilation and forecasting system. Weather and Forecasting, 25(6), 1645-1669.

**Link to Documentation**
https://support.climateengine.org/article/82-rdpa

### Earth Engine Snippet if dataset already in GEE

```js
// Read in Image Collections and get single image 
var rdpa_ic = ee.ImageCollection('projects/climate-engine-pro/assets/ce-rdpa-daily')
var rdpa_i = rdpa_ic.first()

// Print single image to see bands 
print(rdpa_i)

// Visualize precipitation for single image
var prec_palette = ["#ffffcc", "#c7e9b4", "#7fcdbb", "#41b6c4", "#1d91c0", "#225ea8", "#0c2c84"]
Map.addLayer(rdpa_i.select('precip'), {min: 0, max: 200, palette: prec_palette}, 'precip')
```

### Enter license information

Data are subject to the Government of Canada Open Data Licence Agreement: https://open.canada.ca/en/open-government-licence-canada. The terms of this Agreement govern your use and reproduction of the data instead of the copyright reproduction statements found in Important Notices on the Agriculture and Agri-Food Canada website.

### Keywords

climate, precipitation, Canada, United States, daily

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
Check changelog on next release. This has now been conditionally completed
