### ISSUE TITLE
United States Drought Outlook

### ISSUE THREAD

**Issue by EricRJensen** [samapriya/awesome-gee-community-datasets#159]
### Contact Details

ClimateEngine.org staff, climateengine@gmail.com

### Dataset description

**Description**
The United States Drought Outlook raster dataset is produced by the National Weather Service Climate Prediction Center. It is released on the last day of each month and provides information on the drought outlook for the following month.

Categorical dataset values are:

- NoData Value = -9999
- 0 = no drought
- 1 = drought removal likely
- 2 = drought remains but improves
- 3 = drought development likely
- 4 = drought persists

**Spatial extent:** United States
**Spatial resolution:** 500 m (1/48-deg)
**Temporal resolution:** Monthly
**Time span:** 2013-08-01 to present
**Update frequency:** Updated last day of each month

**Variables**
Drought category (‘drought_outlook_class’)

- Units: Drought outlook classification
- Scale factor: 1.0

**External link**
https://www.cpc.ncep.noaa.gov/products/expert_assessment/sdo_summary.php
https://ftp.cpc.ncep.noaa.gov/GIS/droughtlook/ 

**Link to Documentation**
https://support.climateengine.org/article/90-us-drought

### Earth Engine Snippet if dataset already in GEE

```js
// Read in Image Collection and get single image
var usdo_ic = ee.ImageCollection('projects/climate-engine-pro/assets/ce-cpc-usdo-monthly')
var usdo_i = usdo_ic.first()

// Print image to see bands
print(usdo_i)

// Visualize a single image
var usdo_palette = ["#ffffff", "#ABA362", "#DACBB5", "#FFD861", "#935743"]
Map.addLayer(usdo_i, {min:0, max:4, palette: usdo_palette}, 'usdo_i')
```

### Enter license information

NOAA data, information, and products, regardless of the method of delivery, are not subject to copyright and carry no restrictions on their subsequent use by the public. Once obtained, they may be put to any lawful use. The forgoing data is in the public domain and is being provided without restriction on use and distribution. For more information visit the NWS disclaimer site.

### Keywords

drought, United Stated, outlook, forecast, NOAA, NWS, CPC, monthly

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
This has been completed and will be made available in next release
