### ISSUE TITLE
Wildfire Risk to Communities (WRC)

### ISSUE THREAD

**Issue by EricRJensen** [samapriya/awesome-gee-community-datasets#162]
### Contact Details

ClimateEngine.org staff, climateengine@gmail.com

### Dataset description

**Description**
The Wildfire Risk to Communities dataset was created by USDA Forest Service to help assess risk to homes, businesses, and other valued resources. The dataset contains nationally-consistent information for the purpose of comparing relative wildfire risk among communities nationally or within a state or county. In situ risk (risk at the location where the adverse effects take place on the landscape) are modeled using the large fire simulation system (FSim) and LANDFIRE fuel loading datasets from 2014. The original data at 250m has been upsampled to 30m for this dataset on Climate Engine.

**Spatial extent:** United States
**Spatial resolution:** 30 m
**Temporal resolution:** Single point in time
**Time span:** 2014
**Update frequency:** Static

**Variables**
Burn probability (‘BP’)

- Units: Fractional probability
- Scale factor: 1.0

Conditional flame length (‘CFL’)

- Units: Feet
- Scale factor: 1.0

Conditional risk to potential structures (‘CRPS’)

- Units: Percentile
- Scale factor: 1.0

Exposure type (‘Exposure’)

- Units: Exposure type
- Scale factor: 1.0

Flame length exceedance probability - 4 ft (‘FLEP4’)

- Units: Fractional probability
- Scale factor: 1.0

Flame length exceedance probability - 8 ft (‘FLEP8’)

- Units: Fractional probability
- Scale factor: 1.0

Risk to potential structures (‘RPS’)

- Units: Percentiles
- Scale factor: 1.0

Wildfire hazard potential index (‘WHP’)

- Units: Unitless
- Scale factor: 1.0

**External link**
https://www.fs.usda.gov/rds/archive/catalog/RDS-2020-0016 

**Citation**
Scott, Joe H.; Gilbertson-Day, Julie W.; Moran, Christopher; Dillon, Gregory K.; Short, Karen C.; Vogler, Kevin C. 2020. Wildfire Risk to Communities: Spatial datasets of landscape-wide wildfire risk components for the United States. Fort Collins, CO: Forest Service Research Data Archive. Updated 25 November 2020.

**Link to Documentation**
https://support.climateengine.org/article/92-wrc

### Earth Engine Snippet if dataset already in GEE

```js
// Read in Image Collection and mosaic to single image
var wrc_i = ee.ImageCollection('projects/climate-engine-pro/assets/ce-wrc-static').mosaic()

// Print image to see bands
print(wrc_i)

// Visualize select bands from first image — additional bands are present in the Image Collection
var bp_palette = ["#d53e4f", "#fc8d59", "#fee08b", "#ffffbf", "#e6f598", "#99d594", "#3288bd"].reverse()
var exposure_palette = ["#f6eff7", "#d0d1e6", "#a6bddb", "#67a9cf", "#3690c0", "#02818a", "#016450"].reverse()
var crps_palette = ["#ffffd4", "#fee391", "#fec44f", "#fe9929", "#ec7014", "#cc4c02", "#8c2d04"]
var flep_palette = ["#8c510a", "#d8b365", "#f6e8c3", "#f5f5f5", "#c7eae5", "#5ab4ac", "#01665e"].reverse()
var rps_palette = ["#ffffb2", "#fed976", "#feb24c", "#fd8d3c", "#fc4e2a", "#e31a1c", "#b10026"]
var whp_palette = ["#d73027", "#fc8d59", "#fee08b", "#ffffbf", "#d9ef8b", "#91cf60", "#1a9850"].reverse()
Map.addLayer(wrc_i.select('BP'), {min: 0, max: 0.025, palette: bp_palette}, 'BP')
Map.addLayer(wrc_i.select('CFL').selfMask(), {min: 0, max: 15, palette: flep_palette}, 'CFL')
Map.addLayer(wrc_i.select('CRPS'), {min: 30, max: 80, palette: crps_palette}, 'CRPS')
Map.addLayer(wrc_i.select('Exposure'), {min: 0, max: 1, palette: exposure_palette}, 'Exposure')
Map.addLayer(wrc_i.select('FLEP4'), {min: 0.1, max: 0.9, palette: flep_palette}, 'FLEP4')
Map.addLayer(wrc_i.select('FLEP8'), {min: 0.1, max: 0.9, palette: flep_palette}, 'FLEP8')
Map.addLayer(wrc_i.select('RPS'), {min: 0, max: 1, palette: rps_palette}, 'RPS')
Map.addLayer(wrc_i.select('WHP'), {min: 0, max: 2000, palette: whp_palette}, 'WHP')
```

### Enter license information

CC0 1.0 Universal (CC0 1.0) Public Domain Dedication

### Keywords

Wildfire, CONUS, United States, USDA, Forest Service, LANDFIRE

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
This has now been completed you can find links in the changelog here
https://gee-community-catalog.org/changelog/

Thank you for contributing :)
