### ISSUE TITLE
SNOw Data Assimilation System (SNODAS)

### ISSUE THREAD

**Issue by EricRJensen** [samapriya/awesome-gee-community-datasets#166]
### Contact Details

ClimateEngine.org staff, climateengine@gmail.com

### Dataset description

**Description**
The National Operational Hydrologic Remote Sensing Center (NOHRSC) at NOAA produces the SNOw Data Assimilation System (SNODAS) which is a modeling and data assimilation system developed to provide the best possible estimates of snow cover and associated parameters to support hydrologic modeling and analysis.

**Spatial extent:** Conterminous US
**Spatial resolution:** 1000 m (1/120-deg)
**Temporal resolution:** Daily
**Time span:** 2003-10-01 to present
**Update frequency:** Updated daily with 1 day lag

**Variables**
Snow Water Equivalent (‘SWE’) 

- Units: Meters
- Scale factor: 1.0

Snow Depth (‘Snow_Depth’)

- Units: Meters
- Scale factor: 1.0

**External link**
https://nsidc.org/data/g02158 

**Citation**
Barrett, Andrew. 2003. National Operational Hydrologic Remote Sensing Center Snow Data Assimilation System (SNODAS) Products at NSIDC. NSIDC Special Report 11. Boulder, CO USA: National Snow and Ice Data Center. 19 pp.

**Link to Documentation**
https://support.climateengine.org/article/44-snodas

### Earth Engine Snippet if dataset already in GEE

```js
// Read in Image Collection and get image
var snodas_ic = ee.ImageCollection('projects/earthengine-legacy/assets/projects/climate-engine/snodas/daily')
var snodas_i = snodas_ic.filterDate('2022-01-01', '2022-01-05').first()

// Print first image to see bands
print(snodas_i)

// Visualize select bands from first image
var prec_palette = ["#ffffcc", "#c7e9b4", "#7fcdbb", "#41b6c4", "#1d91c0", "#225ea8", "#0c2c84"]
Map.addLayer(snodas_i.select('Snow_Depth'), {min: 0, max: 1, palette: prec_palette}, 'Snow_Depth')
Map.addLayer(snodas_i.select('SWE'), {min: 0, max: 1, palette: prec_palette}, 'SWE')

```

### Enter license information

NOAA data, information, and products, regardless of the method of delivery, are not subject to copyright and carry no restrictions on their subsequent use by the public. Once obtained, they may be put to any lawful use. The forgoing data is in the public domain and is being provided without restriction on use and distribution. For more information visit the NWS disclaimer site.

### Keywords

snow, climate, near real-time, CONUS, United States, NOAA, daily

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
This has now been completed links in the changelog
https://gee-community-catalog.org/changelog/
