### ISSUE TITLE
USGS MODIS ET

### ISSUE THREAD

**Issue by EricRJensen** [samapriya/awesome-gee-community-datasets#168]
### Contact Details

ClimateEngine.org staff, climateengine@gmail.com

### Dataset description

**Description**
Remote sensing derived evapotranspiration dataset based on MODIS-thermal imagery and global weather datasets. Climate Engine is using version 5 of the global ET product.

Notes:

- Actual ET (ETa) is produced using the operational Simplified Surface Energy Balance (SSEBop) model (Senay et al., 2013) for the period 2003 to present.
- The SSEBop setup is based on the Simplified Surface Energy Balance (SSEB) approach (Senay et al., 2007, 2011) with unique parameterization for operational applications using a principle that is comparable to psychometry. A comprehensive evaluation of the model was conducted by Velpuri et al. (2013).
- The global ET is derived from the integration of MODIS-based (Aqua) land surface temperature, maximum air temperature from WorldClim, and reference ET derived from [global data assimilation systems (GDAS)](https://www.ncdc.noaa.gov/data-access/model-data/model-datasets/global-data-assimilation-system-gdas).

**Spatial extent:** Global
**Spatial resolution:** 1-km grid (1/96-deg)
**Temporal resolution:** Dekadal, monthly, and yearly
**Time span:** 2003 to Present
**Update frequency:** Updated every 10-12 days

**Variables**
Evapotranspiration (ETa) (‘et’)

- Units: Millimeters
- Scale factor: 1.0

**External link**
https://earlywarning.usgs.gov/fews/search/Global

**Citation**

- Senay, G.B., Kagone S., Velpuri N.M., 2020, Operational Global Actual Evapotranspiration using the SSEBop model: U.S. Geological Survey data release, [https://doi.org/10.5066/P9OUVUUI.](https://doi.org/10.5066/P9OUVUUI) Publication: https://www.mdpi.com/1424-8220/20/7/1915
- Senay, G. B., Budde, M. E., & Verdin, J. P. (2011). Enhancing the Simplified Surface Energy Balance (SSEB) approach for estimating landscape ET: Validation with the METRIC model. Agricultural Water Management, 98(4), 606-618.
- Senay, G. B., Budde, M., Verdin, J. P., & Melesse, A. M. (2007). A coupled remote sensing and simplified surface energy balance approach to estimate actual evapotranspiration from irrigated fields. Sensors, 7(6), 979-1000.
- Velpuri, N. M., Senay, G. B., Singh, R. K., Bohms, S., and Verdin, J. P. (2013). A comprehensive evaluation of two MODIS evapotranspiration products over the conterminous United States: Using point and gridded FLUXNET and water balance ET, Remote Sensing of Environment, 139, 35-49, [(Abstract and Article)](http://dx.doi.org/10.1016/j.rse.2013.07.013)

**Link to Documentation**
https://support.climateengine.org/article/110-usgs-modis-et

### Earth Engine Snippet if dataset already in GEE

```js
// Read in dekadal, monthly, and annual Image Collections and get single image from each
var modis_et_d_ic = ee.ImageCollection('projects/earthengine-legacy/assets/projects/usgs-ssebop/modis_et_v5_dekadal')
var modis_et_d_i = modis_et_d_ic.first()
var modis_et_m_ic = ee.ImageCollection('projects/earthengine-legacy/assets/projects/usgs-ssebop/modis_et_v5_monthly')
var modis_et_m_i = modis_et_m_ic.first()
var modis_et_a_ic = ee.ImageCollection('projects/earthengine-legacy/assets/projects/usgs-ssebop/modis_et_v5_annual')
var modis_et_a_i = modis_et_a_ic.first()

// Print first image to see bands
print(modis_et_d_i)
print(modis_et_m_i)
print(modis_et_a_i)

// Visualize select bands from first image 
var et_palette = ['#f5e4a9', '#fff4ad', '#c3e683', '#6bcc5c', '#3bb369', '#20998f', '#1c8691']
Map.addLayer(modis_et_d_i.select('et'), {min: 0, max: 10, palette: et_palette}, 'et, dekadal')
Map.addLayer(modis_et_m_i.select('et'), {min: 0, max: 30, palette: et_palette}, 'et, monthly')
Map.addLayer(modis_et_a_i.select('et'), {min: 0, max: 1000, palette: et_palette}, 'et, annual')
```

### Enter license information

USGS-authored or produced data and information are considered to be in the U.S. Public Domain.

### Keywords

evapotranspiration, MODIS, ETa, SSEBop, global, near real-time, monthly, annual, dekadal

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
This has now been completed links in the changelog
https://gee-community-catalog.org/changelog/
