### ISSUE TITLE
USGS VIIRS ET

### ISSUE THREAD

**Issue by EricRJensen** [samapriya/awesome-gee-community-datasets#169]
### Contact Details

ClimateEngine.org staff, climateengine@gmail.com

### Dataset description

**Description**
Remote sensing derived evapotranspiration dataset based on VIIRS-thermal imagery and global weather datasets. Climate Engine is using version 6 of the global ET product.

Notes:

- The SSEBop setup is based on the Simplified Surface Energy Balance (SSEB) approach (Senay et al., 2007) with unique parameterization for operational applications using a principle of satellite psychrometry (Senay, 2018).
- SSEBop Version 6 is also parameterized using the novel Forcing And Normalizing Operation (FANO) algorithm (Senay et al., 2023) to establish the wet-bulb boundary condition, allowing to robustly model the spatiotemporal dynamics of ETa in all landscapes and all seasons regardless of vegetation cover density.
- A recent evaluation of the global ETa product shows promising performance of ETa Anomaly for drought monitoring purposes while water budget studies, requiring absolute magnitudes, may need to apply a local/region-specific bias correction procedure (Senay et. al, 2020).
- The global ET is derived from the integration of VIIRS-based land surface temperature, maximum air temperature from WorldClim, and reference ET derived from gridded weather datasets such as TerraClimate by Abatzoglou et al. (2018) for the world and Chiew et al., (2002) for Australia.

**Spatial extent:** Global
**Spatial resolution:** 1-km grid (1/96-deg)
**Temporal resolution:** Dekadal, monthly, and yearly
**Time span:** 2012 to Present
**Update frequency:** Updated every 10-12 days

**Variables**
Evapotranspiration (ETa) (‘et’)

- Units: Millimeters
- Scale factor: 1.0

**External link**

- https://earlywarning.usgs.gov/fews/search/Global
- https://earlywarning.usgs.gov/fews/product/461 
- https://earlywarning.usgs.gov/fews/product/460 
- https://earlywarning.usgs.gov/fews/product/458 

**Citation**

- Senay, G.B., Parrish, G.E., Schauer, M., Friedrichs, M., Khand, K., Boiko, O., Kagone, S., Dittmeier, R., Arab, S. and Ji, L., 2023. Improving the Operational Simplified Surface Energy Balance Evapotranspiration Model Using the Forcing and Normalizing Operation. Remote Sensing,15(1), p.260. https://doi.org/10.3390/rs15010260
- Senay, G.B., Kagone S., Velpuri N.M., 2020, Operational Global Actual Evapotranspiration using the SSEBop model: U.S. Geological Survey data release, [https://doi.org/10.5066/P9OUVUUI.](https://doi.org/10.5066/P9OUVUUI) Publication: https://www.mdpi.com/1424-8220/20/7/1915
- Abatzoglou, J., Dobrowski, S., Parks, S. et al. TerraClimate, a high-resolution global dataset of monthly climate and climatic water balance from 1958–2015. Sci Data 5, 170191 (2018). https://doi.org/10.1038/sdata.2017.191
- Senay, G. B. (2018). Satellite psychrometric formulation of the Operational Simplified Surface Energy Balance (SSEBop) model for quantifying and mapping evapotranspiration. Applied Engineering in Agriculture, 34(3), 555-566. https://doi.org/10.13031/aea.12614
- Velpuri, N. M., Senay, G. B., Singh, R. K., Bohms, S., and Verdin, J. P. (2013). A comprehensive evaluation of two MODIS evapotranspiration products over the conterminous United States: Using point and gridded FLUXNET and water balance ET, Remote Sensing of Environment, 139, 35-49, [(Abstract and Article)](http://dx.doi.org/10.1016/j.rse.2013.07.013)
- Senay, G. B., Budde, M., Verdin, J. P., & Melesse, A. M. (2007). A coupled remote sensing and simplified surface energy balance approach to estimate actual evapotranspiration from irrigated fields. Sensors, 7(6), 979-1000.
- Chiew, F, Q.J. Wang, F. McConachy, R. James, W. Wright, and G. deHoedt, (2002). Evapotranspiration maps for Australia. Hydrology and Water Resources Symposium, Melbourne, 20-23, 2002, Institution of Engineers, Australia.

**Link to Documentation**
https://support.climateengine.org/article/115-usgs-viirs-et

### Earth Engine Snippet if dataset already in GEE

```js
// Read in dekadal, monthly, and annual Image Collections and get single image from each
var viirs_et_d_ic = ee.ImageCollection('projects/usgs-ssebop/viirs_et_v6_dekadal')
var viirs_et_d_i = viirs_et_d_ic.first()
var viirs_et_m_ic = ee.ImageCollection('projects/usgs-ssebop/viirs_et_v6_monthly')
var viirs_et_m_i = viirs_et_m_ic.first()
var viirs_et_a_ic = ee.ImageCollection('projects/usgs-ssebop/viirs_et_v6_annual')
var viirs_et_a_i = viirs_et_a_ic.first()

// Print first image to see bands
print(viirs_et_d_i)
print(viirs_et_m_i)
print(viirs_et_a_i)

// Visualize select bands from first image 
var et_palette = ['#f5e4a9', '#fff4ad', '#c3e683', '#6bcc5c', '#3bb369', '#20998f', '#1c8691']
Map.addLayer(viirs_et_d_i.select('et'), {min: 0, max: 10, palette: et_palette}, 'et, dekadal')
Map.addLayer(viirs_et_m_i.select('et'), {min: 0, max: 30, palette: et_palette}, 'et, monthly')
Map.addLayer(viirs_et_a_i.select('et'), {min: 0, max: 1000, palette: et_palette}, 'et, annual')
```

### Enter license information

USGS-authored or produced data and information are considered to be in the U.S. Public Domain.

### Keywords

VIIRS, remote sensing, satellite, evapotranspiration, monthly, yearly, dekadal, USGS, global

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
This has now been completed links in the changelog
https://gee-community-catalog.org/changelog/
