### ISSUE TITLE
[Bug]: UnitedKingdom missing from MS Open Buildings

### ISSUE THREAD

**Issue by spatialthoughts** [samapriya/awesome-gee-community-datasets#173]
### Contact Details

ujaval@spatialthoughts.com

### Provide Dataset Link

https://gee-community-catalog.org/projects/msbuildings/

### Describe the bug

The MS Buildings repository indicates complete coverage for UK
https://github.com/microsoft/GlobalMLBuildingFootprints

The collection does not contain an asset for UK
```
var objects = ee.data.listAssets(
  'projects/sat-io/open-datasets/MSBuildings');
print('Assets in MS Global Buildings Footprint Folder',
  objects['assets']);
```

The dataset links indicate availability for UnitedKingdom
https://minedbuildings.blob.core.windows.net/global-buildings/dataset-links.csv

Could you please take a look and add the mising data?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
Hey @spatialthoughts 
Indeed this dataset needs some love and needs to be updated slowly since I first put it in. I am working on getting UK ingested at least for you. I will update the issue once I am done. I wish they had better file naming and I didn't have to do this in parts because of shapefile filesize limits

**Comment by giswqs** [comment]
@samapriya What is the recommended way to ingest a vector dataset (>2GB) and generate a single FeatureCollection? I am trying to ingest a 3.1 GB Libya building dataset in GPKG format, which exceeds the shapefile filesize limit.

**Comment by samapriya** [comment]
Hey @giswqs 
Unfortunately, that limit is pretty rigid, my recommendation would be to split it by feature count and write it out as sub-sections you can always merge them within earth engine though there are limits to that too. The 2GB shapefile limit is indeed a problem for most things related to feature collections

**Comment by spatialthoughts** [comment]
Thanks for the quick response on this @samapriya!

**Comment by samapriya** [comment]
At about 18.4 million+ features this took a while to split merge convert and churn. But it is in there now and publicly available here projects/sat-io/open-datasets/MSBuildings/United_Kingdom
