### ISSUE TITLE
POMELO Population Density Maps 

### ISSUE THREAD

**Issue by nandometzger** [samapriya/awesome-gee-community-datasets#175]
### Contact Details

nando.metzger@geod.baug.ethz.ch

### Dataset description

This dataset presents a fine-grained population map of Tanzania, Mozambique, Uganda, Zambia, and Rwanda with a resolution of 100 meters for 2020, generated using the POMELO super-resolution technique that is based on deep learning. Please refer to our [Nature Scientific Reports publication](https://www.nature.com/articles/s41598-022-24495-w) for more details. Each pixel contains a floating point number specifying the number of inhabitants of the respective pixel (i.e. [People/100m]).

**Background**
Traditionally, many countries, including those in sub-Saharan Africa, rely on aggregated census data over expansive spatial units, which are not always timely or accurate. The need for detailed population maps is paramount in several sectors, including urban development, environmental supervision, public health, and humanitarian initiatives. Addressing this gap, the POMELO methodology leverages coarse census data in conjunction with open geodata to produce high precision population maps.

**Key Features**
 - Resolution: The map offers a granular view with a 100m ground sampling distance, providing intricate details about population distributions in Rwanda.
 - Data Sources: Utilizing a combination of projected admisistrative census data (UN), and supplementing it with open geodata.
 - Reliability: In comparative experiments conducted in sub-Saharan Africa, POMELO's ability to disaggregate coarse census counts achieved R2 values of 85-89%. Furthermore, its potential to predict population numbers without any census data reached accuracy levels of 48-69%.

### Earth Engine Snippet if dataset already in GEE

```js
// load the population density
var popDensity = ee.Image("projects/ee-nandometzger/assets/POMELOv1");

// Define the inferno color palette
var infernoPalette = [
  '#000004', '#1b0c41', '#4a0c6b', '#781c81', '#a52c7a', '#cf4446',
  '#ed721c', '#fb9b06', '#f7d03c', '#fcffa4'
];

// Define visualization parameters.
var visParams = {
  min: 0,
  max: 450,
  palette: infernoPalette,
  opacity: 0.7 // 70% transparent
};

// Add the population density layer to the map.
Map.addLayer(popDensity, visParams, 'Population Density');

// Center map
Map.setCenter(39.2026, -6.1659, 12); // The third parameter is the zoom level.

```

### Enter license information

Creative Commons Attribution 4.0 International (CC-BY-4.0)

### Keywords

population mapping, developing countires, population density, humanitarian actions

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
This has now been completed https://samapriya.github.io/awesome-gee-community-datasets/projects/pomelo. Thank you for contributing

**Comment by nandometzger** [comment]
Is it possible that you did not yet switch the access right to the dataset? I get this error message  

> Population Density: Layer error: Image.load: Image asset 'projects/sat-io/open-datasets/POMELO/POMELOv1' not found (does not exist or caller does not have access).

when I run

> var popDensity = ee.Image("projects/sat-io/open-datasets/POMELO/POMELOv1");

**Comment by samapriya** [comment]
My bad I just fixed it , try again

**Comment by nandometzger** [comment]
It works now.
Thank you for including the POMELO maps and the nice LinkedIn post :)
