### ISSUE TITLE
[Bug]: swissSURFACE3D Raster (DSM) is not available

### ISSUE THREAD

**Issue by chungkang** [samapriya/awesome-gee-community-datasets#176]
### Contact Details

chungkang.c@gmail.com

### Provide Dataset Link

https://gee-community-catalog.org/projects/swiss3d/?h=water

### Describe the bug

When I excute the sample code, it show the message below.

Number (Error)
ImageCollection.load: ImageCollection asset 'projects/sat-io/open-datasets/swissSURFACE3D' not found (does not exist or caller does not have access).

Sample Code: https://code.earthengine.google.com/?scriptPath=users/sat-io/awesome-gee-catalog-examples:elevation-bathymetry/swiss3D-RASTER

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
Not a bug some datasets are insiders only https://gee-community-catalog.org/insiders/ :) 
If you have contributed a dataset or to this project please fill the google form and I can grant you access. Make sure you provide an issue number/link to the dataset you contributed
