### ISSUE TITLE
Historical Aerial Imagery for Western United States

### ISSUE THREAD

**Issue by smorf-ntsg** [samapriya/awesome-gee-community-datasets#177]
### Contact Details

scott.morford@ntsg.umt.edu

### Dataset description

This dataset contains an imagery base layer representing conditions from the mid-1950s across the western United States. We sourced the imagery from over 160,000 aerial images in the [USGS EROS Archive](https://www.usgs.gov/centers/eros/science/usgs-eros-archive-aerial-photography-aerial-photo-single-frames) taken between 1940 and 1970, with the median acquisition date being 1954. The imagery provides complete coverage for 17 western U.S. states: Arizona, California, Colorado, Idaho, Kansas, Montana, North Dakota, Nebraska, New Mexico, Nevada, Oklahoma, Oregon, South Dakota, Texas, Utah, Washington, and Wyoming.

Explore the dataset visually through our easy-to-use web map application at [LandscapeExplorer.org](https://LandscapeExplorer.org). 

Find alternative methods of downloading and utilizing the imagery on our [data download](https://LandscapeExplorer.org/data) page.

We preprocessed the imagery in MATLAB to reduce image vignetting and improve image contrast. Orthorectification was performed in Metashape. The compiled imagery had varying Ground Sampling Distance values, ranging from 0.6 to 1.7 meters. The GEE dataset was written out at 1 meter GSD. Dive deeper into our data processing methods at our  [LandscapeExplorer.org development page](https://www.landscapeexplorer.org/about-landscape-explorer-faq/development-of-the-landscape-explorer-imagery/).

Scientific applications and citations can reference the follow manuscript:

Morford, S.L., Allred, B.W., Jensen, E.R., Maestas, J.D., Mueller, K.R., Pacholski, C.L., Smith, J.T., Tack, J.D., Tackett, K.N. and Naugle, D.E. (2023), Mapping tree cover expansion in Montana, U.S.A. rangelands using high-resolution historical aerial imagery. Remote Sens Ecol Conserv.[https://doi.org/10.1002/rse2.357]( https://doi.org/10.1002/rse2.357)

### Earth Engine Snippet if dataset already in GEE

```js
var conusWest_imagery = ee.ImageCollection("projects/wlfw-um/assets/historical-imagery/conus-west");
var conusWest_metadata = ee.FeatureCollection("projects/wlfw-um/assets/historical-imagery/conus-west-seamlines");
```

### Enter license information

[Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)

### Keywords

Aerial imagery, United States, Great Plains, Great Basin, Historical, photogrammetry

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
I have processed the feature collection further to standardize the date value and attached it to each feature as epoch time, which filters users to use .filterDate within Earth Engine. I also created an earth engine app that provides users with the date, the Photo ID, and the browse link. You can check the landscape explorer app I built using your raster layer and the new metadata layer I processed here

https://sat-io.earthengine.app/view/landscape-explorer

I should be able to add it to the community catalog this week and publish it out
