### ISSUE TITLE
USGS MODIS Evapotranspiration

### ISSUE THREAD

**Issue by EricRJensen** [samapriya/awesome-gee-community-datasets#179]
### Contact Details

eric.jensen@dri.edu

### Provide Dataset Link

https://gee-community-catalog.org/projects/usgs_modis_et/?h=usgs+mo

### Describe the update

Change timespan from '2003 to Present' to '2003 to 2023'. This product is no longer being produced operationally, now that the VIIRS product is operational. Ultimately, the 2023 data may be removed entirely and if that happens we'll suggest another update to reflect the time span.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
I have updated this, thanks @EricRJensen
