### ISSUE TITLE
Duplicate ids

### ISSUE THREAD

**Issue by lpaolini** [samapriya/awesome-gee-community-datasets#181]
The following ids in [community_datasets.json](https://github.com/samapriya/awesome-gee-community-datasets/blob/master/community_datasets.json) are not unique:

- `projects/sat-io/open-datasets/landfire/fuel/FCCS` (2 occurrencies)
- `projects/sat-io/open-datasets/GHS/GHS_BUILT_S_E2018_GLOBE_R2023A_54009_10_V1_0` (2 occurrencies)

**Comment by samapriya** [comment]
Can you specify which pages or files have these duplicate occurrences?

**Comment by lpaolini** [comment]
Sorry, I've updated the initial message.

**Comment by samapriya** [comment]
Thanks @lpaolini 
Are you guys doing something with this in Sepal or is this just your contributions :smile: I really appreciate your help fixing these so thank you for that

**Comment by lpaolini** [comment]
Yes, we're including the list in SEPAL! :-)
I noticed React complaining about duplicate keys, and that's how I spotted those ids.

I have a question: would it be possible to add a property for each dataset with the link to the documentation page?
That'd be extremely useful for our users. Thanks!

**Comment by samapriya** [comment]
I think you have to be extremely careful because not all licenses allow for use across platforms. We should do a call to talk about this 😁 and also on how you intend to present the community catalog list in SEPAL

**Comment by lpaolini** [comment]
@samapriya Sure, I'll coordinate with Erik and Daniel and get in touch with you. Many thanks!
