### ISSUE TITLE
FABDEM V1-2

### ISSUE THREAD

**Issue by edtrochim** [samapriya/awesome-gee-community-datasets#182]
### Contact Details

edtrochim@alaska.edu

### Provide Dataset Link

https://data.bris.ac.uk/data/dataset/25wfy0f9ukoge2gs7a5mqpq2j7

### Describe the update

The underlying Copernicus DEM has been updated to Copernicus 2021_1. Details on the updates to the Copernicus DEM can be found here.  • Copernicus DEM has variable grid spacing in high latitudes (50°N/S). This results in grids not being aligned across the interface where different resolutions are used. For FABDEM, Copernicus DEM was first resampled to a 1 arcsecond grid, however for V1.0, the alignment of high latitude tiles was not matched to the low latitude tiles. The preprocessing of the Copernicus DEM was updated for FABDEM V1.2 to align all tiles consistently.  • Some tiles in high latitudes had artifacts due to pixel resampling (see Figure 1 for an example). Fixed alignment solved this issue • Format changed to Cloud Optimized Geotiff, with updated compression options (DEFLATE with PREDICTOR=2). This reduces file size by ~40% • AREA_OR_POINT label changed to Point. Previously incorrectly labelled as Area. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
v1.2 link here https://data.bris.ac.uk/data/dataset/s5hqmjcdj8yo2ibzi9b4ew3sn. Wish they had faster downloads at current rate could take over a week to just download data since they have rate limited requesters

**Comment by samapriya** [comment]
This has now been completed v1.2 now replaces v1.0

https://gee-community-catalog.org/projects/fabdem
