### ISSUE TITLE
Biodiversity Intactness

### ISSUE THREAD

**Issue by benbutchart** [samapriya/awesome-gee-community-datasets#183]
### Contact Details

b.butchart@earthblox.io

### Dataset description

The Biodiversity Intactness Index (BII) measures biodiversity change using abundance data on plants, fungi and animals worldwide. The Index shows how local terrestrial biodiversity responds to human pressures such as land use change and intensification. Generated by [Impact Observatory](https://www.impactobservatory.com/), in collaboration with [Vizzuality](https://www.vizzuality.com/), these datasets estimate terrestrial Biodiversity Intactness as 100-meter gridded maps for the years 2017-2020.  Biodiversity Intactness data is based on the [PREDICTS database](https://onlinelibrary.wiley.com/doi/full/10.1002/ece3.2579) of spatially referenced observations of biodiversity across 32,000 sites from over 750 studies

Biodiversity intactness is estimated as a combination of two metrics: Abundance, the quantity of individuals, and Compositional Similarity, how similar the composition of species is to an intact baseline. Linear mixed effects models are fit to estimate the predictive capacity of spatial datasets of human pressures on each of these metrics and project results spatially across the globe. These methods, as well as comparisons to other leading datasets and guidance on interpreting results, are further explained in a methods [white paper](https://ai4edatasetspublicassets.blob.core.windows.net/assets/pdfs/io-biodiversity/Biodiversity_Intactness_whitepaper.pdf) entitled “Global 100m Projections of Biodiversity Intactness for the years 2017-2020.”  authored by Francis Gassert, Joe Mazzarello, Sam Hyde.

[Impact Observatory ](https://www.impactobservatory.com/)(processor, producer, licensor)
[Vizzuality ](https://www.vizzuality.com/)(processor)
[PREDICTS database](https://onlinelibrary.wiley.com/doi/full/10.1002/ece3.2579) 
[Earth Blox] https://www.earthblox.io/ (host)
[Google Earth Engine] https://earthengine.google.com/ (host)

All years are available under a Creative Commons BY-4.0 license.

### Earth Engine Snippet if dataset already in GEE

```
var bdi_ic = ee.ImageCollection("projects/ebx-data/assets/earthblox/IO/BIOINTACT")
var bdi_2017_20_comp = bdi_ic.mean()
var bdi_2017_comp = bdi_ic.filterDate('2017-01-01', '2017-12-31').mean()


var visualization = {
  bands: ['BioIntactness'],
  min: 0,
  max: 1,
  palette: ['e5f5e0', 'a1d99b', '31a354'], 4: ['edf8e9', 'bae4b3', '74c476', '238b45']
};

Map.addLayer(bdi_2017_20_comp, visualization, "composite 2017-20")
Map.addLayer(bdi_2017_comp, visualization, "composite 2017")
```

### Enter license information

[CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)

### Keywords

Biodiversity, Ecology, Human Pressures, Gridded data

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
This will be made available on Monday as discussed
