### ISSUE TITLE
PKU NDVI long term global data set

### ISSUE THREAD

**Issue by GonzaIrisarri** [samapriya/awesome-gee-community-datasets#184]
### Contact Details

gonzalo.irisarri@rothamsted.ac.uk

### Dataset description

Long-term harmonized NDVI time series from 1981 to 2023

Source: https://zenodo.org/record/8253971

### Earth Engine Snippet if dataset already in GEE

for example
```js
var asset_name = ee.ImageCollection("path to your collection")
```
Sample Code: Add a sample code maybe just adding your datasets in the code editor

### Enter license information

Dataset license:
https://creativecommons.org/licenses/by/4.0/legalcode

### Keywords

NDVI NOAA MODIS long-term

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
This request has now been completed you can find the dataset and information here
https://gee-community-catalog.org/projects/gimms_ndvi/
