### ISSUE TITLE
Global Intra-Urban Land Use

### ISSUE THREAD

**Issue by emackres** [samapriya/awesome-gee-community-datasets#188]
### Contact Details

eric.mackres@wri.org

### Dataset description

This dataset provides land use maps for the year 2020 for all 4,000+ cities and metropolitan areas in the world with populations exceeding 100,000. The resulting product is the first freely available, global intra-urban land use maps at 5-meter resolution. The data includes a 4-tier land use taxonomy which at its root distinguishes open-space from built-up area. At the second tier, it subdivides the built-up category into nonresidential and residential areas. The third tier distinguishes formal from informal residential land use, and the fourth tier further subdivides formal and informal residential land uses into more detailed categories. Results of a separate road/street classification model based on the same methods are also provided. 

Journal article: https://doi.org/10.1016/j.compenvurbsys.2022.101917

### Earth Engine Snippet if dataset already in GEE

```js
var ULU = ee.ImageCollection('projects/wri-datalab/cities/urban_land_use/V1')

// Define classes and set color parameters. 
var CLASSES_7=[
  "open_space",
  "nonresidential",
  "atomistic",
  "informal_subdivision",
  "formal_subdivision",
  "housing_project",
  "road"]
var COLORS_7=[
  '33A02C',
  'E31A1C',
  'FB9A99',
  'FFFF99',
  '1F78B4',
  'A6CEE3',
  'bdbdbd']
var CLASSES=CLASSES_7
var colors=COLORS_7
var ULU7Params = {bands: ['lulc'], min: 0, max: 6, opacity: 1, palette: colors};

// Generate image of 6-class land use from the highest probability class at each pixel. 
var ULUimage = ULU.select('lulc').reduce(ee.Reducer.firstNonNull()).rename('lulc')
ULUimage=ULUimage.mask(ULUimage.mask().gt(0))

// Generate image of road areas based on a pixels with greater than 50% probability of being road. 
var roadsImage = ULU.select('road').reduce(ee.Reducer.firstNonNull()).rename('lulc')
var roadProb = 50
var roadsMask = roadsImage.updateMask(roadsImage.gt(roadProb)).where(roadsImage, 1)

// Composite 6-class land use and roads into as single image. 
var ULUandRoads = ULUimage.where(roadsMask,6).select('lulc')

// Map both the 6-class land use and composite images. 
Map.addLayer(ULUimage, ULU7Params, 'Intra-urban land use, 6-class (2020)');
Map.addLayer(ULUandRoads, ULU7Params, 'Intra-urban land use, 7-class (2020)');

```

### Enter license information

Dataset license: [Creative Commons BY-4.0](https://creativecommons.org/licenses/by/4.0/)

### Keywords

Urban land use maps; Land use land cover; Sentinel-2; Neural networks; Computer vision; Supervised classification; Google Earth Engine; Informal settlements

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
This has now been completed and is [online here](https://gee-community-catalog.org/projects/giulu/). Thank you so much for contributing

**Comment by emackres** [comment]
Excellent!  Thank you!
