### ISSUE TITLE
[Bug]: Missing rasters in Global Daily near-surface air temperature (2003-2020)

### ISSUE THREAD

**Issue by TC25** [samapriya/awesome-gee-community-datasets#190]
### Contact Details

tc.chakraborty25@gmail.com

### Provide Dataset Link

https://gee-community-catalog.org/projects/airtemp/

### Describe the bug

I was going through this dataset and it seems there are no files for day 366 of leap years. Additionally, for tmin, the image for 2nd April, 2020 is missing.

Just wanted to confirm if it is an issue with the original dataset, an issue with the ingested version, or my mistake. 

Thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TC25** [comment]
Found any solution to this?

**Comment by samapriya** [comment]
Leap years are still provided with 365 days and doy are coded from the filename so additional days for leap years are not available I just tried the year 2004 as a test. So no fix available there

Tmin seems to be missing only for North America and that file seems to be damaged so unfortunately nothing for me to fix here. Feel free to reach out to the author for a reupload if you want
