### ISSUE TITLE
[Dataset Title/Name]:Employing the Agricultural Classification and Estimation service (ACES) for mapping smallholder rice farms in Bhutan

### ISSUE THREAD

**Issue by MayerT1** [samapriya/awesome-gee-community-datasets#192]
### Contact Details

tjm0042@uah.edu

### Provide Dataset Link

var Bhutan_ACES_Rice_Maps = ee.ImageCollection("projects/servir-sco-assets/assets/Bhutan/Rice_Extent_Mapper/Predicted_Rice_Post_Processed_IC");

### Describe the example

[Employing the Agricultural Classification and Estimation service (ACES) for mapping smallholder rice farms in Bhutan](https://www.frontiersin.org/articles/10.3389/fenvs.2023.1137835/full) | https://doi.org/10.3389/fenvs.2023.1137835

Annual crop type rice maps for 2016-2022 for enabling improved food security decision making has remained a challenge in Bhutan. These maps were developed in collaboration with the Bhutan Department of Agriculture and SERVIR. Through focusing on advancing Science, Technology, Engineering, and Mathematics (STEM) in Bhutan, an effort to co-develop a geospatial application known as the [Agricultural Classification and Estimation Service (ACES)](https://github.com/SERVIR/ag-classification-estimation/tree/main) was created. This dataset and paper focuses on the co-development of an Earth observation informed climate smart crop type framework which incorporates both modeling and training sample collection. The [ACES web application](https://servirglobalnet.users.earthengine.app/view/aces-bhutan) and subsequent ACES modeling software package enables stakeholders to more readily use Earth observation into their decision making process. Additionally, this data set and paper offers a transparent and replicable approach for addressing and combating remote sensing limitations due to topography and cloud cover, a common problem in Bhutan. Lastly, this approach resulted in a Random Forest “LTE 555” model, from a set of 3,600 possible models, with an overall test Accuracy of 85% and F-1 Score of .88 for 2020. The model was independently validated resulting in an independent accuracy of 83% and F-1 Score of .45 for 2020. 

Map.setCenter(90.39712423618803, 27.496515911317108)
var palettes = require('users/gena/packages:palettes');
Map.addLayer(Bhutan_ACES_Rice_Maps,{min: 0,max: 1, palette: palettes.colorbrewer.Oranges[3]},
"ACES Rice Maps 2016-2022 ")
//https://doi.org/10.3389/fenvs.2023.1137835
//Add a grayscale map to help higlight the feature
var SubtleGrayscale
 = 
[
  {
    "featureType": "administrative",
    "elementType": "all",
    "stylers": [
      {
        "saturation": "-100"
      }
    ]
  },
  {
    "featureType": "administrative.province",
    "elementType": "all",
    "stylers": [
      {
        "visibility": "off"
      }
    ]
  },
  {
    "featureType": "landscape",
    "elementType": "all",
    "stylers": [
      {
        "saturation": -100
      },
      {
        "lightness": 65
      },
      {
        "visibility": "on"
      }
    ]
  },
  {
    "featureType": "poi",
    "elementType": "all",
    "stylers": [
      {
        "saturation": -100
      },
      {
        "lightness": "50"
      },
      {
        "visibility": "simplified"
      }
    ]
  },
  {
    "featureType": "road",
    "elementType": "all",
    "stylers": [
      {
        "saturation": "-100"
      }
    ]
  },
  {
    "featureType": "road.highway",
    "elementType": "all",
    "stylers": [
      {
        "visibility": "simplified"
      }
    ]
  },
  {
    "featureType": "road.arterial",
    "elementType": "all",
    "stylers": [
      {
        "lightness": "30"
      }
    ]
  },
  {
    "featureType": "road.local",
    "elementType": "all",
    "stylers": [
      {
        "lightness": "40"
      }
    ]
  },
  {
    "featureType": "transit",
    "elementType": "all",
    "stylers": [
      {
        "saturation": -100
      },
      {
        "visibility": "simplified"
      }
    ]
  },
  {
    "featureType": "water",
    "elementType": "geometry",
    "stylers": [
      {
        "hue": "#ffff00"
      },
      {
        "lightness": -25
      },
      {
        "saturation": -97
      }
    ]
  },
  {
    "featureType": "water",
    "elementType": "labels",
    "stylers": [
      {
        "lightness": -25
      },
      {
        "saturation": -100
      }
    ]
  }
]
Map.setOptions('SubtleGrayscale', {SubtleGrayscale: SubtleGrayscale})

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MayerT1** [comment]
Hey Sam sorry for the delays SERVIR is still pushing to make data in the GEE community catalog | https://doi.org/10.3389/fenvs.2023.1137835

**Comment by samapriya** [comment]
Hey @MayerT1 
Any further clarification on what values 0-1 represent here?

**Comment by samapriya** [comment]
The dataset page is now live and deployed and [can be found here](https://gee-community-catalog.org/projects/aces_bhutan/). Thank you for contributing in the future would be great if you use the Bring Your Own Dataset template rather than an example template. Also, it would be great to have 

- License information
- keywords/tags
- curated by or provided by information 
- 

to make the process easy :)
