### ISSUE TITLE
[GADM]: add a new boundaries dataset in GEE 

### ISSUE THREAD

**Issue by 12rambau** [samapriya/awesome-gee-community-datasets#199]
### Dataset description

GADM wants to map the administrative areas of all [countries](https://gadm.org/country.html), at all levels of sub-division. they provide data at high spatial resolutions that includes an extensive set of attributes. This is a never ending project, but they are happy to share what they have. You can write them with questions and suggestions, using this [contact form](http://rasterra.com/contact/gadm_contact_form).

the downloadable link of the latest version of the dataset: https://gadm.org/download_world.html (multiple format available)  

### Enter license information

The data are freely available for academic use and other non-commercial use. Redistribution or commercial use is not allowed without prior permission.

Using the data to create maps for publishing of academic research articles is allowed. Thus you can use the maps you made with GADM data for figures in articles published by PLoS, Springer Nature, Elsevier, MDPI, etc. You are allowed (but not required) to publish these articles (and the maps they contain) under an open license such as CC-BY as is the case with PLoS journals and may be the case with other open access articles. Data for the following countries is covered by a a different license Austria: Creative Commons Attribution-ShareAlike 2.0 (source: Government of Ausria)

### Keywords

boundaries

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 12rambau** [comment]
As agreed tagging @gena for visibility.

**Comment by samapriya** [comment]
Hi @12rambau and @gena 
The license for GADM does not allow for redistribution. 

As per their license terms

```
Redistribution or commercial use is not allowed without prior permission.
```

So while I would love to add this dataset I am not allowed to do so by the license. I have filled out their contact form to ask for permission so let's wait and watch if they respond. Keeping this ticket open for now

**Comment by samapriya** [comment]
I have had no luck, owing to restrictions in licensing I cannot add to the community catalog. I will reopen this issue if they reply to my email
