### ISSUE TITLE
Global Fire Atlas (2003-2016)

### ISSUE THREAD

**Issue by katieailsa** [samapriya/awesome-gee-community-datasets#20]
Data Set: Global Fire Atlas (2003-2016)
https://samapriya.github.io/awesome-gee-community-datasets/projects/gfa/

Dataset Last updated: 2019-04-24

Relationship to Dataset: User

Dataset link: https://code.earthengine.google.com/20d059ee5819d2fbb7e0de398f70eb90
```js
var day_of_burn = ee.ImageCollection('projects/sat-io/open-datasets/global-fire-atlas/day_of_burn');
var fire_speed = ee.ImageCollection('projects/sat-io/open-datasets/global-fire-atlas/fire_speed');
var fire_line = ee.ImageCollection('projects/sat-io/open-datasets/global-fire-atlas/fire_line');
var fire_direction = ee.ImageCollection('projects/sat-io/open-datasets/global-fire-atlas/fire_direction');

// For 2016:
var perimeter_2016 = ee.FeatureCollection("projects/sat-io/open-datasets/global-fire-atlas/perimeter/Global_fire_atlas_V1_perimeter_2016");
var ignitions_2016 = ee.FeatureCollection("projects/sat-io/open-datasets/global-fire-atlas/ignitions/Global_fire_atlas_V1_ignitions_2016");
```

Reason for update
Currently, the projection of the ignitions and perimeters do not match the projection of the speed, fire line, direction, and day of burn data. Using the Inspector tool, I identified that the projection of the ignitions and perimeters data sets was WGS1984, but the other data sets had an undefined projection and datum. Even though these data layers should match up, they appear to be offset.  This forces me to download the data outside of GEE, define the projection in another software, then re-upload the data. Thanks!

Updated License: N/A

**Comment by samapriya** [comment]
unfortunately the source datasets seem to be unavailable at this point(https://glihtdata.gsfc.nasa.gov/files/fire_atlas/) , however you could use the reproject tool inside GEE to reproject the feature collection to the raster projection. I will try to revisit this in the future but I do not have a solution without the source files being available
