### ISSUE TITLE
[Dataset Title/Name]: Africa tree cover map

### ISSUE THREAD

**Issue by SFrav** [samapriya/awesome-gee-community-datasets#200]
### Dataset description

Using PlanetScope data Reiner et al. (2023) have developed the most detailed tree cover map of Africa. Their "prototype map of 2019 ...  reveals that 29% of tree cover is found outside areas previously classified as tree cover in state-of-the-art maps, such as in croplands and grassland".
This is a 100 m resolution map of % tree canopy cover per pixel for Africa in 2019. Tree cover values range from 0-100 % and nodata areas are masked as -1.

Download link: https://zenodo.org/records/7764460
DOI:[10.5281/zenodo.7764459](https://zenodo.org/doi/10.5281/zenodo.7764459)

### Earth Engine Snippet if dataset already in GEE

for example
```js
var asset_name = ee.ImageCollection("path to your collection")
```
Sample Code: Add a sample code maybe just adding your datasets in the code editor

### Enter license information

This tree cover map is made freely available for non-commercial purposes. All usage of the data must be attributed and should be cited with the paper citation. 

Please see the NICFI license for full terms of usage, available at: https://assets.planet.com/docs/Planet_ParticipantLicenseAgreement_NICFI.pdf

### Keywords

Forest, Africa

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SFrav** [comment]
@samapriya, just following up on this: is this contribution enough to get access to the Insider program? I would like to make use of the MS Bing Mined Roads dataset as a mask in an analysis of agricultural lands. I see that you are the curator of the dataset. I applied for the insider program at the same time as submitting this suggestion.
Thanks.

**Comment by samapriya** [comment]
Hi @SFrav 
You have now been added to the insiders group. Good luck with your research

**Comment by SFrav** [comment]
@samapriya, thank you

**Comment by samapriya** [comment]
This has now been completed and will be available in todays release
