### ISSUE TITLE
[Dataset Title/Name]: Randolph Glacier Inventory version 7.0

### ISSUE THREAD

**Issue by HendrikWulf** [samapriya/awesome-gee-community-datasets#202]
### Contact Details

wulf.hendrik@googlemail.com

### Dataset description

The Randolph Glacier Inventory ([RGI](https://www.glims.org/RGI)) is a globally complete inventory of glacier outlines (excluding the ice sheets in Greenland and Antarctica). It is a subset of the database compiled by the Global Land Ice Measurements from Space ([GLIMS](https://www.glims.org/)) initiative. While GLIMS is a multi-temporal database with an extensive set of attributes, the RGI is intended to be a snapshot of the world’s glaciers at a specific target date, which in RGI 7.0 and all previous versions has been set as close as possible to the year 2000 (although in fact its range of dates can still be substantial in some regions). The RGI includes outlines of all glaciers larger than 0.01 km², which is the recommended minimum of the World Glacier Inventory.

### Earth Engine Snippet if dataset already in GEE

for example
```js
var RGI = ee.FeatureCollection("users/wulf/RGI_v7/")
```
Sample Code: Add a sample code maybe just adding your datasets in the code editor
// Script to display the RGI v7 glacier mask.
// RGI information: http://www.glims.org/rgi_user_guide/welcome.html

// read RGI verson 7 vetor data
var table1 = ee.FeatureCollection("users/wulf/RGI_v7/01_rgi70_alaska"),
    table2 = ee.FeatureCollection("users/wulf/RGI_v7/02_rgi70_western_canada_usa"),
    table3 = ee.FeatureCollection("users/wulf/RGI_v7/03_rgi70_arctic_canada_north"),
    table4 = ee.FeatureCollection("users/wulf/RGI_v7/04_rgi70_arctic_canada_south"),
    table5 = ee.FeatureCollection("users/wulf/RGI_v7/05_rgi70_greenland_periphery"),
    table6 = ee.FeatureCollection("users/wulf/RGI_v7/06_rgi70_iceland"),
    table7 = ee.FeatureCollection("users/wulf/RGI_v7/07_rgi70_svalbard_jan_mayen"),
    table8 = ee.FeatureCollection("users/wulf/RGI_v7/08_rgi70_scandinavia"),
    table9 = ee.FeatureCollection("users/wulf/RGI_v7/09_rgi70_russian_arctic"),
    table10 = ee.FeatureCollection("users/wulf/RGI_v7/10_rgi70_north_asia"),
    table11 = ee.FeatureCollection("users/wulf/RGI_v7/11_rgi70_central_europe"),
    table12 = ee.FeatureCollection("users/wulf/RGI_v7/12_rgi70_caucasus_middle_east"),
    table13 = ee.FeatureCollection("users/wulf/RGI_v7/13_rgi70_central_asia"),
    table14 = ee.FeatureCollection("users/wulf/RGI_v7/14_rgi70_south_asia_west"),
    table15 = ee.FeatureCollection("users/wulf/RGI_v7/15_rgi70_south_asia_east"),
    table16 = ee.FeatureCollection("users/wulf/RGI_v7/16_rgi70_low_latitudes"),
    table17 = ee.FeatureCollection("users/wulf/RGI_v7/17_rgi70_southern_andes"),
    table18 = ee.FeatureCollection("users/wulf/RGI_v7/18_rgi70_new_zealand"),
    table19 = ee.FeatureCollection("users/wulf/RGI_v7/19_rgi70_subantarctic_antarctic_islands");

// merge the regions
var glacier_ft = table1.merge(table2).merge(table3).merge(table4).merge(table5).merge(table6).merge(table7)
                       .merge(table8).merge(table9).merge(table10).merge(table11).merge(table12).merge(table13)
                       .merge(table14).merge(table15).merge(table16).merge(table17).merge(table18).merge(table19);
// Map.addLayer(glacier_ft, {color: 'red'}, 'RGI_v7', false);

// print a feature
// print('first glacier feature', glacier_ft.first());

// Make a raster image out of the land area attribute.
var glacier_img = glacier_ft.reduceToImage({
    properties: ['area_km2'],
    reducer: ee.Reducer.first()
});

// Make a binary mask
var glacier_binary = glacier_img.gt(0).unmask();
Map.addLayer(glacier_binary, {min:0, max:1}, 'glacier mask');

### Enter license information

CC-BY-4.0

### Keywords

glacier outlines

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
I have merged all tables into a single feature collection for ease of use
Let me know if you find any issues in the [sample code here](https://code.earthengine.google.com/90749fd844866ab4cfeca26a552c6a8f)

**Comment by HendrikWulf** [comment]
Hi Samapriya,

Your sample code looks good. Thanks for merging all the regions.
I would recommend also mentioning the current version 7 in the file or path name (e.g. RGI_v7).
There will be other versions in the future that represent other timestamps. This could led to confusions.

Thanks a lot for your help!

best wishes,
Hendrik


---
Hendrik Wulf, Dr.rer.nat.

Remote Sensing Laboratories | Department of Geography | University of Zurich

e-mail: ***@***.******@***.***>
phone: +41 (0) 44 635 5145
mail: Winterthurerstrasse 190 | 8057 Zurich | Switzerland

web: https://www.geo.uzh.ch/en/units/rsl

On 4 Jan 2024, at 16:02, Samapriya Roy ***@***.******@***.***>> wrote:



I have merged all tables into a single feature collection for ease of use
Let me know if you find any issues in the sample code here<https://code.earthengine.google.com/90749fd844866ab4cfeca26a552c6a8f>

**Comment by samapriya** [comment]
Yup got the version included the page should be updated now here will be released with the next release but you can [find it here](https://gee-community-catalog.org/projects/rgi/). Let me know if there are other issues or concerns
