### ISSUE TITLE
[Dataset/Title]: LF 2022 Update

### ISSUE THREAD

**Issue by sbeverlyCtrUsgs** [samapriya/awesome-gee-community-datasets#203]
### Contact Details

sbeverly@contractor.usgs.gov

### Provide Dataset Link

https://gee-community-catalog.org/projects/landfire/?h=landfire

### Describe the update

LANDFIRE (LF), Landscape Fire and Resource Management Planning Tools, is a shared program between the wildland fire management programs of the U.S. Department of Agriculture's Forest Service, U.S. Department of the Interior's Geological Survey, and The Nature Conservancy.

LANDFIRE (LF) layers are created using predictive landscape models based on extensive field-referenced data, satellite imagery and biophysical gradient layers using classification and regression trees. You can read [about the Landfire 2022 updates v2.3.0 here](https://landfire.gov/lf_230.php)

The LANDFIRE (LF) 2022 Update represents another step in moving towards an annual update. This update is the first time in LANDFIRE history in which disturbances from the year before are represented in current year products. LF 2022 includes adjustments to vegetation and fuels in disturbed areas for disturbances recorded in 2021 and 2022. LF 2022 disturbance layers contain comprehensive polygon treatment data (disturbance events) obtained from national and local sources and fire program data including:

* Monitoring Trends in Burn Severity (MTBS)
* Burned Area Reflectance Classification (BARC)
* Rapid Assessment of Vegetation Condition after Wildfire (RAVG)

Disturbances are also identified with LF's remote sensing of landscape change (RSLC), which identifies spectral change in vegetation using automated algorithms and image analyst review of the entire country.

Both vegetation cover and height, as well as fuels, will be 2023 capable in disturbed areas. This means that in mapped disturbances, vegetation and fuels represent current year conditions. Transition rulesets for vegetation account for disturbances from 2017 to 2022 since they were designed to use LF 2016 Remap vegetation data as inputs. Fuel updates utilize 2013–2022 disturbances because fuels transition rules encompass ten years of disturbance and can use pre-disturbance fuel inputs.

Important changes featured in the LF 2022 update include:

* Existing Vegetation Type (EVT) Ecological Systems classifications will remain the same as LF 2020, except in areas where agriculture or urban areas have changed
* LF 2022 contains the first application of the "zero to one" Time Since Disturbance (TSD) rules for vegetation height and cover transition rules
    * New rules for the "zero to one" TSD category were developed for surface fuel transitions and are designed to represent the effects of disturbance on fuels for the growing season immediately following the disturbance
* The years represented in Historical Disturbance (HDist) and Fuel Disturbance (FDist) are now the same

### Relevant additional information

Code samples and screenshots are fine as-is, however the datasets that the code is referencing will need to be changed.  

LF 2022 data can be found here: 

https://landfire.gov/version_download.php 
https://landfire.gov/insular_areas.php

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
Hi @sbeverlyCtrUsgs 
This update has been completed and will be released this week. Thank you for your contribution

**Comment by sbeverlyCtrUsgs** [comment]
Hi @samapriya I noticed that the writeup has not been updated; I pasted the updated text in "Describe the update" and it can replace everything up to the screenshots.  Also the datasets themselves have updated and I'm not sure if Landfire needs to provide GEE with this data or if it can be linked to.  Please advise, and thank you for your help.

**Comment by samapriya** [comment]
Hey @sbeverlyCtrUsgs 
Sorry for missing that I have updated the text now based on your description. Thank you for pointing that out
