### ISSUE TITLE
Global Glacier Elevation change products from Hugonnet et al. (2021)

### ISSUE THREAD

**Issue by lucas-zeller** [samapriya/awesome-gee-community-datasets#205]
### Contact Details

lzeller22@gmail.com

### Dataset description

The global glacier elevation change products from Hugonnet et al. (2021) provide elevation change maps (rasters) for all global glaciers. Elevation change maps (and uncertainties) are provided at 100 m resolution over glaciers and within a 10 km buffer for the 5-year periods of 2000–2004, 2005–2009, 2010–2014 and 2015–2019, the 10-year periods of 2000–2009 and 2010–2019 and the full 20-year period of 2000–2019.

_Manuscript citation_: Hugonnet, R., McNabb, R., Berthier, E. et al. Accelerated global glacier mass loss in the early twenty-first century. Nature 592, 726–731 (2021). https://doi.org/10.1038/s41586-021-03436-z

_Data citation_: https://doi.org/10.6096/13

### Earth Engine Snippet if dataset already in GEE

Sample Code Suggestion:

```js
var asset_name = ee.ImageCollection("path to collection")
                      .filterBounds(geometry)
                      .filter(ee.Filter.eq('PRODUCT', 'dhdt')) // to get the dhdt product, alternatively get the error by 'dhdt_err'
                      .filter(ee.Filter.eq('PERIOD', '1519')) // to get the 2015-2019 product
```

### Enter license information

This work is licensed under a Creative Commons Attribution 4.0 International License.

### Keywords

glacier, elevation, ASTER, DEM, dhdt

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
Switching this to two collections for dhdt and dhdt_err and time_period instead of period as property this is ongoing

**Comment by samapriya** [comment]
This has now been completed and will be released later today you can find the [page here](https://gee-community-catalog.org/projects/glacier) with almost 28,000 assets+. Thank you for contributing
