### ISSUE TITLE
GLC-FCS30D

### ISSUE THREAD

**Issue by davidtheobald8** [samapriya/awesome-gee-community-datasets#206]
### Contact Details

davidtheobald@gmail.com

### Dataset description

GLC_FCS30D is a global 30-m land-cover dynamic monitoring dataset, containing 35 land-cover subcategories and covering the period of 1985–2022 with 26 time-steps (maps updated every five years before 2000 and annually after 2000). GLC_FCS30D has been developed using continuous change detection and all available Landsat imagery based on the Google Earth Engine platform. In specific, we first take advantage of the continuous change-detection model and full time-series Landsat observations to capture the time-points of changed pixels and identify the temporally stable areas. Then, we apply a spatiotemporal refinement method to derive the globally distributed and high-confidence training samples from these temporally stable areas. Next, locally adaptive classification models are used to update the land-cover information for the changed pixels, and a temporal-consistency optimization algorithm is adopted to improve their temporal stability and suppress some false changes. Further, the GLC_FCS30D product is validated using 84,526 globally distributed validation samples in 2020 and achieves an overall accuracy of 80.88 % (±0.27 %) for the basic classification system (10 major land-cover types) and 73.24 % (±0.30 %) for the LCCS level-1 validation system (17 LCCS land-cover types).

Preprint: https://essd.copernicus.org/preprints/essd-2023-320/

### Earth Engine Snippet if dataset already in GEE

for example
```js
var asset_name = ee.ImageCollection("path to your collection")
```
Sample Code: Add a sample code maybe just adding your datasets in the code editor

### Enter license information

Not clear -- still a preprint, so perhaps it is too early to post these. 
Authors request: "If you plan to use our data in a scientific analysis paper, we strongly recommend contacting us in advance to seek opinions and consider our contributions in the acknowledgments or as co-authors."

### Keywords

land cover change, global

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
This has been completed and will be released tomorrow. Since this paper has not been published a disclaimer has been added

**Comment by samapriya** [comment]
Hope you found the link but pasting it here 
https://gee-community-catalog.org/projects/glc_fcs
