### ISSUE TITLE
High-spatial-resolution Thermal-stress Indices over South and East Asia (HiTiSAE) & Yechao Yan; Yangyang Xu; Shuping Yue

### ISSUE THREAD

**Issue by nileshsnshinde** [samapriya/awesome-gee-community-datasets#21]
Follow the underlying template when creating a new dataset issue entry

### Dataset Name
High-spatial-resolution Thermal-stress Indices over South and East Asia (HiTiSAE)

#### Earth Engine Snippet
```js
var asset_name = ee.ImageCollection("path to your collection")

or

var asset_name = ee.Image("path to your image")

or

var asset_name = ee.FeatureCollection("path to your table/feature collection")
```

Sample Code: Add a sample code maybe just adding your datasets in code editor and visualizing or summarizing

Extra Info: This newly developed dataset is a high-spatial-resolution (0.1°×0.1°) gridded product that contains the daily values of the indoor, outdoor shaded and outdoor unshaded UTCI, the MRT and eight other widely adopted human thermal-stress indices (ESI, HI, Humidex, WBGT, WBT, WCT, AT, NET), derived from the newly available ECMWF ERA5-Land and ERA5 reanalysis products, over South and East Asia from Jan 3, 1981 to Dec 31, 2019. The dataset contains 14242 daily NetCDF files which are archived by month and compressed into tar.gz files with a total volume of 450 GB
Article: https://www.nature.com/articles/s41597-021-01010-w.pdf
Figshare: https://springernature.figshare.com/collections/A_High-spatial-resolution_Dataset_of_Human_Thermal_Stress_Indices_over_South_and_East_Asia/5196296

Download Tool/Code snippets if any: If source is specialized or you have an associated tool

#### Required
License Information: Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/).

Curated by: Yechao Yan; Yangyang Xu; Shuping Yue

Keywords: thermal-stress indices, south and southeast asia 

Last updated: 2021-05-20

**Comment by samapriya** [comment]
This is in progress, you can follow the updates here along with decisions regarding change of dataset structure for GEE ingestion and use. Will close the ticket once all datasets are available which may take sometime

**Comment by nileshsnshinde** [comment]
Hello Dr. Roy, 
Thanks for the update. I really appreciate your inputs. 

Best, 
Nilesh

**Comment by samapriya** [comment]
This has finally been completed
12 variables across 39 years for each day there might have been a few days missing but primarily looks good. The page https://samapriya.github.io/awesome-gee-community-datasets/projects/hitisae/ has link to all the image collections. At this point closing the issue as done . Thank you for suggesting the dataset
