### ISSUE TITLE
National Burned Area Composite [SHP] for Canada

### ISSUE THREAD

**Issue by puzhao8** [samapriya/awesome-gee-community-datasets#213]
### Contact Details

puzhao@kth.se

### Dataset description

The National Burned Area Composite (NBAC) is a GIS database and system that calculates the area of forest burned on a national scale for each year since 1986. The data are used to help estimate carbon emissions in Canada. The burned area is determined by evaluating a number of available sources of data, which use different techniques to map any given fire. The system chooses the best available source of data for each burned area and builds a national composite picture.

The NBAC is part of the Fire Monitoring, Accounting and Reporting System (FireMARS), jointly developed by the Canada Centre for Mapping and Earth Observation (formerly the Canada Centre for Remote Sensing) of Natural Resources Canada and the Canadian Forest Service. Initially, FireMARS was developed with funding support from the Canadian Space Agency Government Related Initiatives Program through a collaboration of those in fire research, forest carbon accounting and remote sensing.

Data are provided for NBAC from:
• Natural Resources Canada, and
• Provincial, Territorial, and Parks Canada agencies.

The NBAC can be used for spatial and temporal analyses of landscape-scale fire impacts.

Supplemental Information
NBAC is a national product compiled annually since 1986 by the FireMARS system which tracks forest fires for annual estimates of carbon emissions and to help identify National Forest Inventory plots that may have been disturbed by fire. See the FireMARS website at (http://www.nrcan.gc.ca/forests/fire/13159) and carbon accounting - disturbance monitoring website (http://www.nrcan.gc.ca/forests/climate-change/13109) for additional information.

When using these data for mapping activities and analysis, research, evaluation or display, please acknowledged the source using the following citation:

Canadian Forest Service. National Burned Area Composite (NBAC). Natural Resources Canada, Canadian Forest Service, Northern Forestry Centre, Edmonton, Alberta. https://cwfis.cfs.nrcan.gc.ca/.

References:

Skakun, R.; Castilla, G.; Metsaranta, J.; Whitman, E.; Rodrigue, S.; Little, J.; Groenewegen, K.; Coyle, M. (2022). Extending the National Burned Area Composite Time Series of Wildfires in Canada. Remote Sensing, 14, 3050. DOI: https://doi.org/10.3390/rs14133050

Skakun, R.S.; Whitman, E.; Little, J.M.; and Parisien, M.-A. (2021). Area burned adjustments to historical wildland fires in Canada. Environmental Research Letters 16 064014. DOI: https://doi.org/10.1088/1748-9326/abfb2c

Hall, R.J.; Skakun, R.S.; Metsaranta, J.M.; Landry, R.; Fraser, R.H.; Raymond, D.A.; Gartrell, J.M.; Decker, V. and Little, J.M. (2020). Generating annual estimates of forest fire disturbance in Canada: the National Burned Area Composite. International Journal of Wildland Fire. 10.1071/WF19201. DOI: https://doi.org/10.1071/WF19201

download link: https://cwfis.cfs.nrcan.gc.ca/datamart/metadata/nbac

### Earth Engine Snippet if dataset already in GEE

for example
```js
var asset_name = ee.ImageCollection("path to your collection")
```
Sample Code: Add a sample code maybe just adding your datasets in the code editor

### Enter license information

Open Government Licence - Canada (http://open.canada.ca/en/open-government-licence-canada)

When using these data for mapping activities and analysis, research, evaluation or display, please acknowledged the source using the following citation: Canadian Forest Service. National Burned Area Composite (NBAC). Natural Resources Canada, Canadian Forest Service, Northern Forestry Centre, Edmonton, Alberta. https://cwfis.cfs.nrcan.gc.ca/.

### Keywords

Wildfire, Burned Area

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
This has now been completed and is available in the community catalog. You can find the link in the changelog. Thank you for contributing
