### ISSUE TITLE
Global SWOT River Database (SWORD)

### ISSUE THREAD

**Issue by puzhao8** [samapriya/awesome-gee-community-datasets#214]
### Contact Details

puzhao@kth.se

### Dataset description

1. Summary:

The upcoming Surface Water and Ocean Topography (SWOT) satellite mission, planned to launch in 2022, will vastly expand observations of river water surface elevation (WSE), width, and slope. In order to facilitate a wide range of new analyses with flexibility, the SWOT mission will provide a range of relevant data products. One product the SWOT mission will provide are river vector products stored in shapefile format for each SWOT overpass (JPL Internal Document, 2020b). The SWOT vector data products will be most broadly useful if they allow multitemporal analysis of river nodes and reaches covering the same river areas. Doing so requires defining SWOT reaches and nodes a priori, so that SWOT data can be assigned to them. The SWOt River Database (SWORD) combines multiple global river- and satellite-related datasets to define the nodes and reaches that will constitute SWOT river vector data products. SWORD provides high-resolution river nodes (200 m) and reaches (~10 km) in shapefile and netCDF formats with attached hydrologic variables (WSE, width, slope, etc.) as well as a consistent topological system for global rivers 30 m wide and greater.

2. Data Formats:

The SWORD database is provided in netCDF and shapefile formats. All files start with a two-digit continent identifier (“af” – Africa, “as” – Asia / Siberia, “eu” – Europe / Middle East, “na” – North America, “oc” – Oceania, “sa” – South America). File syntax denotes the regional information for each file and varies slightly between netCDF and shapefile formats.

NetCDF files are structured in 3 groups: centerlines, nodes, and reaches. The centerline group contains location information and associated reach and node ids along the original GRWL 30 m centerlines (Allen and Pavelsky, 2018). Node and reach groups contain hydrologic attributes at the ~200 m node and ~10 km reach locations (see description of attributes below). NetCDFs are distributed at continental scales with a filename convention as follows: [continent]_sword_v2.nc (i.e. na_sword_v2.nc).

SWORD shapefiles consist of four main files (.dbf, .prj, .shp, .shx). There are separate shapefiles for nodes and reaches, where nodes are represented as ~200 m spaced points and reaches are represented as polylines. All shapefiles are in geographic (latitude/longitude) projection, referenced to datum WGS84. Shapefiles are split into HydroBASINS (Lehner and Grill, 2013) Pfafstetter level 2 basins (hbXX) for each continent with a naming convention as follows: [continent]_sword_[nodes/reaches]_hb[XX]_v2.shp (i.e. na_sword_nodes_hb74_v2.shp; na_sword_reaches_hb74_v2.shp).

download link: https://zenodo.org/records/5643392

### Earth Engine Snippet if dataset already in GEE

for example
```js
var asset_name = ee.ImageCollection("path to your collection")
```
Sample Code: Add a sample code maybe just adding your datasets in the code editor

### Enter license information

If you use the SWORD Database in your work, please cite: Altenau et al., (2021) The Surface Water and Ocean Topography (SWOT) Mission River Database (SWORD): A Global River Network for Satellite Data Products. Water Resources Research. [https://doi.org/10.1029/2021WR030054](https://doi.%20org/10.1029/2021WR030054)

### Keywords

River Networks, SWOT, SWORD

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
This has now been completed and will be made available this week. Thank you for contributing

**Comment by puzhao8** [comment]
Thank you very much!
