### ISSUE TITLE
Temporal trends of surface water area across India's rivers and basins

### ISSUE THREAD

**Issue by pskoulgi** [samapriya/awesome-gee-community-datasets#216]
### Contact Details

pradeepkoulgi@gmail.com

### Dataset description

This dataset quantifies the extent and rate of annual change in surface water area (SWA) across India's rivers and basins over 30 years from 1991 to 2020. It does so by season (annual dry, wet and permanent water, based on India's seasons) and at two spatial scales: the river basin scale (1516 level-7 basins from HydroBASINS) and the finer river reach scale (68,367 reaches). This dataset is derived from the historical time series of monthly surface water occurrence by [JRC's Global Surface Water Explorer](https://global-surface-water.appspot.com/). 

These are available as the following GEE assets: 
* Annual rate of change of surface water area, by season:
  * Reaches: `users/pradeepkoulgi/RiverChanges/publishV1/txsTrends`
  * Basins: `users/pradeepkoulgi/RiverChanges/publishV1/basinsTrends`
* Time series of annual surface water area, by season:
  * Reaches: `users/pradeepkoulgi/RiverChanges/publishV1/mainlandIndia_areasTs_txs`
  * Basins: `users/pradeepkoulgi/RiverChanges/publishV1/mainlandIndia_areasTs_basinsL7`
* Time series of annual surface water occurrence, by season: `users/pradeepkoulgi/RiverChanges/publishV1/waterOccSeasComps`

More details and resources:

| Published data repository (excluding the time series of annual surface water occurrence) | https://doi.org/10.5281/zenodo.7803903 |
| ---: | :--- |
| Published Earth Engine code behind the analysis | https://doi.org/10.5281/zenodo.7839588 |
| Published data description | https://doi.org/10.1016/j.dib.2023.109991|
| Interactive visualization, and more | https://sites.google.com/view/surface-water-trends-india/ |

![Screenshot from 2024-01-29 11-06-25](https://github.com/samapriya/awesome-gee-community-datasets/assets/13193943/2d155699-9ed1-4abc-9aca-224617c4fe4b) ![Screenshot from 2024-01-29 11-10-26](https://github.com/samapriya/awesome-gee-community-datasets/assets/13193943/3ead8a36-8fe9-4954-96f7-5af142484690)

### Earth Engine Snippet if dataset already in GEE

```js
var reachTrends = ee.FeatureCollection('users/pradeepkoulgi/RiverChanges/publishV1/txsTrends');
var reachAreaTimeseries = ee.FeatureCollection('users/pradeepkoulgi/RiverChanges/publishV1/mainlandIndia_areasTs_txs');
var basTrends = ee.FeatureCollection('users/pradeepkoulgi/RiverChanges/publishV1/basinsTrends');
var basAreaTimeseries = ee.FeatureCollection('users/pradeepkoulgi/RiverChanges/publishV1/mainlandIndia_areasTs_basinsL7');
var annualWaterOccSeasComps = ee.ImageCollection('users/pradeepkoulgi/RiverChanges/publishV1/waterOccSeasComps');

var brewer7ClPuOr = ['b35806', 'f1a340', 'fee0b6', 'f7f7f7', 'd8daeb', '998ec3', '542788'];
var empty = ee.Image().byte();

var reachTrendsDrySeason = reachTrends.filter(ee.Filter.eq('season', 'dry_fma'));
var fillsreach = empty.paint(reachTrendsDrySeason, 'sl_perYr');
Map.addLayer(fillsreach, {palette: brewer7ClPuOr, min: -0.02, max: 0.02}, 'dry_fma_reach');
Map.setCenter(79.49959, 16.63471, 14);

var basTrendDrySeason = basTrends.filter(ee.Filter.and(ee.Filter.eq('HYBAS_ID', 4071092530), ee.Filter.eq('season', 'dry_fma')));
var fillsBas = empty.paint(basTrendDrySeason, 'sl_perYr');
Map.addLayer(fillsBas, {palette: brewer7ClPuOr, min: -75, max: 75}, 'dry_fma_bas', false);
```

### Enter license information

CC-BY-4.0

### Keywords

surface water, river reaches, river basins, time series

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
This has been processed and will be released within this week. I have also copied over your collections to have consistent path names for the project.

**Comment by samapriya** [comment]
The webpage is now live and will be released tomorrow https://gee-community-catalog.org/projects/india_river_trends/

Thank you so much for contributing your data
