### ISSUE TITLE
GABAM 2020 update

### ISSUE THREAD

**Issue by andrewclelland** [samapriya/awesome-gee-community-datasets#218]
### Contact Details

andell84@bas.ac.uk

### Provide Dataset Link

https://gee-community-catalog.org/projects/gabam/

### Describe the update

Data for 2020 and 2021 are missing in the GEE Community Catalog. Please can they be uploaded.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
This has now been completed and the dataset now includes 2020 and 2021
