### ISSUE TITLE
Satellite-Based Forest Inventory (SBFI) for Canada 2020

### ISSUE THREAD

**Issue by S-Bronson** [samapriya/awesome-gee-community-datasets#219]
### Contact Details

spencer.bronson@nrcan-rncan.gc.ca

### Satellite-Based Forest Inventory (SBFI) for Canada 2020

The Satellite-Based Forest Inventory (SBFI) provides information on Canada’s forested land cover, disturbance recovery, structure, species, and stand age in 2020, as well as stand-replacing disturbances from 1985-2020. The SBFI polygons represent homogeneous forest conditions similar to those of stands delineated in a strategic forest inventory. More than 25 million SBFI polygons were delineated using a multiresolution segmentation algorithm applied to the 2020 Landsat surface-reflectance BAP image composite (30-m spatial resolution), fire year, and harvest year layers derived from Landsat using the C2C approach. A minimum map unit of 0.45 ha (5 pixels) was used to define polygons. The entirety of Canada’s forest ecosystems were mapped using the same data, attributes, and temporal representation, resulting in a common vegetation inventory system of Canada’s ~650 Mha forested ecosystems. Given the large and diverse forest area of Canada, the strength of an SBFI lies in the use of a consistent data source and methodology across jurisdictional boundaries, and managed and unmanaged forest areas, enabling consistently generated synoptic, spatially explicit information outputs. The data included herein are based upon free and open satellite data and information products following established and communicated approaches.

Full descriptions of feature attributes are found within the attached data dictionary or within the downloadable dataset found here,
https://opendata.nfis.org/downloads/forest_change/CA_Forest_Satellite_Based_Inventory_2020.zip

#### Citation

```
Wulder, M.A., Hermosilla, T., White, J.C., Bater, C.W., Hobart, G., Bronson, S.C., 2024. Development and implementation of a stand-level satellite-based forest inventory for Canada. Forestry: An International Journal of Forest Research. https://doi.org/10.1093/forestry/cpad065
```
[DataDictionary_AwesomeGEE_SBFI.pdf](https://github.com/samapriya/awesome-gee-community-datasets/files/14214890/DataDictionary_AwesomeGEE_SBFI.pdf)

### Earth Engine Snippet if dataset already in GEE

Sample Code: 
```js
////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////
// user will need to manually define the tiles they wish to upload into the display

// identify tiles using this naming scheme
// 'Tile_XXX'     where XXX is the tile number
var f_list = ['Tile_434', 'Tile_395', 'Tile_356'];

// pathway to the folder containing all the tile and grid feature collections
var basePath = "users/mesospencer/SBFI_2020/";


////////////////////////////////////////////////////////////////////////////////////////
// center map on a tile

// get the length of the list of tiles to add to the map
var len = f_list.length;

// define the file that will be used to center the map
var fname = basePath.concat("", f_list[Math.round(len/2)-1]);

// load feature collection and add field of random numbers
var bounds = ee.FeatureCollection(fname).randomColumn('random');

// return only half of features
var bounds = bounds.filter(ee.Filter.lt('random', 0.05));

// centre map on tile
Map.centerObject(ee.FeatureCollection(bounds));


////////////////////////////////////////////////////////////////////////////////////////
// add tiles to map

// generate array to contain colours of each tile
var colour_ar = [];

for (var i=0; i < len; i++) {

  // generate pseudo-random colour
  var seed = i+1;
  var aColour = Math.floor((Math.abs(Math.sin(seed) * 16777215))).toString(16);
  while(aColour.length < 6) {
    var aColour = '0' + aColour;
  }
  
  colour_ar.push(aColour)
  
  // import the tiles and assign the colour of the tile
  var fname2 = ee.FeatureCollection(basePath.concat("", f_list[i]));
  Map.addLayer(fname2, {color: aColour}, fname);
}


////////////////////////////////////////////////////////////////////////////////////////
// add grid and labels to identify grid tiles

var grid = ee.FeatureCollection(basePath.concat("", "GRID_forested_ecosystems"));
var grid_labels = ee.Image(basePath.concat("", "Grid_Labels"))

Map.addLayer(grid, {color: "black"}, 'Grid', 1, 0.25);
Map.addLayer(grid_labels, {}, "Grid Labels");


////////////////////////////////////////////////////////////////////////////////////////
// generate the legend

// Create a panel to hold the legend
var legend = ui.Panel({
  style: {
    position: 'bottom-left',
    padding: '8px 15px'
  }
});

// Function to generate the legend
function addCategoricalLegend(panel, dict, title) {

  // Create and add the legend title.
  var legendTitle = ui.Label({
    value: title,
    style: {
      fontWeight: 'bold',
      fontSize: '18px',
      margin: '0 0 4px 0',
      padding: '0'
    }
  });
  panel.add(legendTitle);

  var loading = ui.Label('Loading legend...', {margin: '2px 0 4px 0'});
  panel.add(loading);

  // Creates and styles 1 row of the legend.
  var makeRow = function(color, name) {
    // Create the label that is actually the colored box.
    var colorBox = ui.Label({
      style: {
        backgroundColor: color,
        // Use padding to give the box height and width.
        padding: '8px',
        margin: '0 0 4px 0'
      }
    });

    // Create the label filled with the description text.
    var description = ui.Label({
      value: name,
      style: {margin: '0 0 4px 6px'}
    });

    return ui.Panel({
      widgets: [colorBox, description],
      layout: ui.Panel.Layout.Flow('horizontal')
    });
  };

  loading.style().set('shown', false);

  for (var i = 0; i < f_list.length; i++) {
    panel.add(makeRow(colour_ar[i], f_list[i]));
  }
  Map.add(panel);
}

var dict = {
  "names": f_list,
  "colors": colour_ar
};

// Add the legend to the map
addCategoricalLegend(legend, dict, 'Satellite Based Forest Inventory 2020');



```

### Enter license information

Open Government Licence - Canada (http://open.canada.ca/en/open-government-licence-canada)

Created by: Wulder et al. (2024)

Curated by: Spencer Bronson and Samapriya Roy

Last updated: 2024-02-05

### Keywords

Landsat, forest area, temporally informed forest area, disturbance informed forest area, forest inventory, land cover, change detection, forest structure, biomass, National Forest Inventory

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by S-Bronson** [comment]
i am going to have to share a link to the data that is used in the script i have provided. I changed some of the field names on my local dataset

**Comment by samapriya** [comment]
I don't think you have shared your assets I cannot access users/mesospencer/SBFI_2020

**Comment by S-Bronson** [comment]
https://code.earthengine.google.com/?asset=users/mesospencer/SBFI_2020_edited

I am hoping that this will provide you access (the name of the folder is different in my provided snippet)

**Comment by samapriya** [comment]
you have shared the folder but not the individual assets so they cannot be accessed. Use a tool like geeadd access tool to change permissions for all images in that folder https://geeadd.geetools.xyz/projects/access/

**Comment by samapriya** [comment]
Hey @S-Bronson 
Please let me know if you are able to use the setup I suggested above to share the assets in the folder. In the current state while I can list the folder contents I cannot access them

**Comment by S-Bronson** [comment]
Hi Sam, 
Sorry for the delay, I will rad that article and get to sharing the content of the folder right now


Cheers,
    Spencer

**Comment by S-Bronson** [comment]
All the data should be shared now. Thank you for pointing out your document for sharing recursive assets, I can only imagine that clicking through all ~400 feature collections to share with you would have been a headache.

Will you be creating a local copy of the data on your end? It would be a shame if I lost the data from my account and removed it from all Awesome-GEE users.


Cheers,
    Spencer

**Comment by samapriya** [comment]
Yup I will be copying them over so you won't have to worry about storage issues and maintaining a copy :)

**Comment by S-Bronson** [comment]
Thank you for this. 
I attempted to merge everything, however, I had no luck as it maxed out the number of features being displayed. I will have to check out the final product when its out tomorrow.

**Comment by samapriya** [comment]
Well hope everything seems okay here let me know if the datasets look okay. I used a simpler example showing age max across a single tile but happy to update with an updated example code if you would like
https://gee-community-catalog.org/projects/ca_sbfi/
