### ISSUE TITLE
[Dataset Title/Name]: MSWEP V2 Global 3-Hourly 0.1° Precipitation

### ISSUE THREAD

**Issue by dawsonv** [samapriya/awesome-gee-community-datasets#221]
### Contact Details

dawsonv7@gmail.com

### Dataset description

MSWEP is a global precipitation product with a 3‑hourly 0.1° resolution available from 1979 to ~3 hours from real-time. The product is unique in that it merges gauge, satellite, and reanalysis data to obtain the highest quality precipitation estimates at every location.

Website: https://www.gloh2o.org/mswep/
Paper: https://doi.org/10.1175/BAMS-D-17-0138.1

### Earth Engine Snippet if dataset already in GEE

N/A (dataset is not already in GEE)

### Enter license information

MSWEP is released under the Creative Commons Attribution-NonCommercial 4.0 International ([CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)) license.

### Keywords

precipitation

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
The license for this is confusing while the data is under a CC  by NC license they still require you to fill out the form for the distribution of the data and as such it is not truly open data in any way and redistribution rights belong with the provider. This means even if I can access the data I cannot redistribute it to others. Feel free to reach out to the providers to get any clarity on this

**Comment by dawsonv** [comment]
Thanks for pointing this out. I will reach out to the data provider to clarify their terms of use.
