### ISSUE TITLE
[Bug]: Canopy height: forested ecosystems of Canada - no access

### ISSUE THREAD

**Issue by robitalec** [samapriya/awesome-gee-community-datasets#222]
### Contact Details

robit.alec@gmail.com

### Provide Dataset Link

https://gee-community-catalog.org/projects/ca_canopy_ht

### Describe the bug

The "Canopy height: forested ecosystems of Canada" dataset by Sothe et al 2022 is not accessible. 

Example script: 
https://code.earthengine.google.com/9d510c3f8d1b2db8942d77e7ad8f337d

```js
var ca_forest_dir = ee.data.listAssets('projects/sat-io/open-datasets/CA_FOREST').assets;
print(ca_forest_dir);

print(ee.Image('projects/sat-io/open-datasets/CA_FOREST/GEDI_forest_canopy_height_250m_v1'));
print(ee.Image('projects/sat-io/open-datasets/CA_FOREST/ICESat2_forest_canopy_height_250m_v1'));
```
```
Image (Error)
Image.load: Image asset 'projects/sat-io/open-datasets/CA_FOREST/GEDI_forest_canopy_height_250m_v1' not found (does not exist or caller does not have access).

Image (Error)
Image.load: Image asset 'projects/sat-io/open-datasets/CA_FOREST/ICESat2_forest_canopy_height_250m_v1' not found (does not exist or caller does not have access).
```

This script checks that the path to the two assets listed in the example script and community catalog match the asset in the CA_FOREST directory. 

### Relevant additional information

![image](https://github.com/samapriya/awesome-gee-community-datasets/assets/16324625/b710e08d-3be2-40b7-8248-d68e6affc446)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
This should now be fixed feel free to check and reopen the issue if this doesn't work :) Thanks for reporting
