### ISSUE TITLE
ESA Fire Climate Change Initiative (Fire_cci): AVHRR-LTDR Burned Area Pixel product, version 1.1

### ISSUE THREAD

**Issue by harrybmwells** [samapriya/awesome-gee-community-datasets#224]
### Contact Details

hw6794@princeton.edu

### Dataset description

The ESA Fire Disturbance Climate Change Initiative (CCI) project has produced maps of global burned area derived from satellite observations. The AVHRR - LTDR Pixel v1.1 product described here contains gridded data of global burned area derived from spectral information from the AVHRR (Advanced Very High Resolution Radiometer) Land Long Term Data Record (LTDR) v5 dataset produced by NASA.

The dataset provides monthly information on global burned area at 0.05-degree spatial resolution (the resolution of the AVHRR-LTDR input data) from 1982 to 2018. The year 1994 is omitted as there was not enough input data for this year. The dataset is distributed in monthly GeoTIFF files, packed in annual tar.gz files, and it includes 5 files: date of BA detection (labelled JD), confidence label (CL), burned area in each pixel (BA), number of observations in the month (OB) and a metadata file. For further information on the product and its format see the Product User Guide.

Citable as:  Chuvieco, E.; Pettinari, M.L.; Otón, G. (2020): ESA Fire Climate Change Initiative (Fire_cci): AVHRR-LTDR Burned Area Pixel product, version 1.1. Centre for Environmental Data Analysis, 21 December 2020. doi:10.5285/b1bd715112ca43ab948226d11d72b85e. https://dx.doi.org/10.5285/b1bd715112ca43ab948226d11d72b85e

Download link: https://catalogue.ceda.ac.uk/uuid/b1bd715112ca43ab948226d11d72b85e

### Earth Engine Snippet if dataset already in GEE

NA

### Enter license information

http://licences.ceda.ac.uk/image/data_access_condition/esacci_fire_terms_and_conditions.pdf

### Keywords

ESA, CCI, Pixel, Burned Area, Fire Disturbance, Climate Change, GCOS Essential Climate Variable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
This has now been completed and is available in the community catalog, check the changelog for links. Thank you for contributing
