### ISSUE TITLE
National-Scale Soil Erosion Dataset for Pakistan (2005 and 2025) at 1km Spatial Resolution

### ISSUE THREAD

**Issue by adeelpu** [samapriya/awesome-gee-community-datasets#225]
### Contact Details

adeel.geog@pu.edu.pk; adeal.gis@gmail.com

### Dataset description

Comprehensive assessment of soil erosion dynamics in Pakistan for 2005 and 2015 at 1 km² spatial resolution using the Revised Universal Soil Loss Equation (RUSLE) model and six influencing factors. Soil erosion maps are categorized into four classes: low, medium, high, and very high, revealing an increase from 1.79 to 2.47 ton ha⁻¹ yr⁻¹ on the national level.

The national-scale soil erosion dataset for Pakistan (2005 and 2025) at 1km spatial resolution data is available here:

**Citation:**

Use of these data requires citation of this dataset:

Gilani, Hammad, Ahmad, Adeel, Younes, Isma, & Abbas, Sawaid. (2021). National-scale soil erosion dataset for Pakistan (2005 and 2025) at 1km spatial resolution (1.0) [Dataset]. Zenodo. https://doi.org/10.5281/zenodo.10694225

Original research article:

Gilani, H., Ahmad, A., Younes, I., & Abbas, S. (2021). Impact assessment of land cover and land use changes on soil erosion changes (2005–2015) in Pakistan. Land Degradation & Development, 33(1):204–217. [doi.org/10.1002/ldr.4138](https://doi.org/10.1002/ldr.4138)

### Earth Engine Snippet if dataset already in GEE

for example
```js
var pk_soil_erosion_2005 = ee.Image('users/adeelgeog/Pakistan_soil_erosion_2005_1km')
var pk_soil_erosion_2015 = ee.Image('users/adeelgeog/Pakistan_soil_erosion_2015_1km')
```
Sample Code: Add a sample code maybe just adding your datasets in the code editor

### Enter license information

CC-BY-4.0

### Keywords

soil erosion, soil conservation, RUSLE, Pakistan, temporal soil erosion

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
This has now been completed and will be released today please check the changelog later for links

**Comment by adeelpu** [comment]
Thank you so much, it's online now.
![Capture](https://github.com/samapriya/awesome-gee-community-datasets/assets/104847796/b74bdd78-2263-41fc-b211-a04033675178)
