### ISSUE TITLE
Formatting off for a bulleted point list on the India River Trends page

### ISSUE THREAD

**Issue by pskoulgi** [samapriya/awesome-gee-community-datasets#227]
**Documentation** issue.

In the page for [India river trends](https://gee-community-catalog.org/projects/india_river_trends/), the bulleted point list with EE asset IDs is not rendering right on the site.

![image](https://github.com/samapriya/awesome-gee-community-datasets/assets/13193943/c13e39ee-edfa-4437-8003-a70dd271bba3)

**Comment by samapriya** [comment]
This has been fixed
