### ISSUE TITLE
Attribute tables missing in India river trends page

### ISSUE THREAD

**Issue by pskoulgi** [samapriya/awesome-gee-community-datasets#228]
**Documentation** issue.

In the [India River Trends page](https://gee-community-catalog.org/projects/india_river_trends/), it would be nice to have a table describing the attributes in each of the data assets. Formatting them into separate expandable widgets like the one in the [GLC-FCS30D page](https://gee-community-catalog.org/projects/glc_fcs/) would keep clutter down and be even nicer if possible :).

![image](https://github.com/samapriya/awesome-gee-community-datasets/assets/13193943/351f328d-d0f2-4f33-82ac-4d78f224fc57)

I tried making the additions and submitting a PR, but I couldn't figure out how to build it locally to verify everything works fine after the addition, I am new to HTML and Material for MkDocs. Hence, I am filing an issue including the markdown for the tables, in case it can be picked up from here. Any suggestions for a Material for MkDocs novice like me to do a PR on this is welcome, and I'll try.

---------------------------------------------

Below is the table for the annual rate of change of surface water area feature collections, to be added after [line 15](https://github.com/samapriya/awesome-gee-community-datasets/blob/0efba24cc44a8e2f53ff1bb7233c22cc72cadf7a/docs/projects/india_river_trends.md?plain=1#L15), the markdown code is below

| Attribute | Description |
|----------:|:------------|
| `HYBAS_ID` or `txId` | Feature's unique identifier <ul><li>`HYBAS_ID` is for basins. It is the basin's identifier `HYBAS_ID` in the HydroBASINS dataset</li><li>`txId` is for transects. It is the '_' concatenated string derived from the longitude and latitude values, truncated to 4 decimals, of the transect's median point. Specifically, it is "_xx.xxxx_yy.yyyy_" where _xx.xxxx_ and _yy.yyyy_ are the median's longitude and latitude values truncated to 4 decimals.</li></ul> |
| `season` | Denotes the season, in "_sss_mmm_" format, where <ul><li>"_sss_" denotes the season: "_dry_" for dry, "_wet_" for wet and "_prm_" for permanent </li><li>"_mmm_" denotes the span of the season in calendar months: "_fma_" is for dry season of February-March-April, "_ond_" is for wet (post-monsoon) season of October-November-December and "_DnW_" is for permanent which is dry AND wet season. </li></ul>|
| `sl_perYr` | Regression slope of the surface water area vs. year Sen's slope regression analysis, and "_perYr_" denotes its units, per year. |
| `offset` | Regression offset of the surface water area vs. year Sen's slope regression analysis. |
| `tsPtCount` | Number of time-points included in the Sen's slope regression analysis. |
| `system:index` | GEE system-generated unique identifier. |

```
| Attribute | Description |
|----------:|:------------|
| `HYBAS_ID` or `txId` | Feature's unique identifier <ul><li>`HYBAS_ID` is for basins. It is the basin's identifier `HYBAS_ID` in the HydroBASINS dataset</li><li>`txId` is for transects. It is the '_' concatenated string derived from the longitude and latitude values, truncated to 4 decimals, of the transect's median point. Specifically, it is "_xx.xxxx_yy.yyyy_" where _xx.xxxx_ and _yy.yyyy_ are the median's longitude and latitude values truncated to 4 decimals.</li></ul> |
| `season` | Denotes the season, in "_sss_mmm_" format, where <ul><li>"_sss_" denotes the season: "_dry_" for dry, "_wet_" for wet and "_prm_" for permanent </li><li>"_mmm_" denotes the span of the season in calendar months: "_fma_" is for dry season of February-March-April, "_ond_" is for wet (post-monsoon) season of October-November-December and "_DnW_" is for permanent which is dry AND wet season. </li></ul>|
| `sl_perYr` | Regression slope of the surface water area vs. year Sen's slope regression analysis, and "_perYr_" denotes its units, per year. |
| `offset` | Regression offset of the surface water area vs. year Sen's slope regression analysis. |
| `tsPtCount` | Number of time-points included in the Sen's slope regression analysis. |
| `system:index` | GEE system-generated unique identifier. |
```

Below is the table for the time series of annual surface water area feature collections, to be added after [line 18](https://github.com/samapriya/awesome-gee-community-datasets/blob/0efba24cc44a8e2f53ff1bb7233c22cc72cadf7a/docs/projects/india_river_trends.md?plain=1#L18), the markdown code is below

| Attribute | Description |
|----------:|:------------|
| `HYBAS_ID` or `txId` | Feature's unique identifier <ul><li>`HYBAS_ID` is for basins. It is the basin's identifier `HYBAS_ID` in the HydroBASINS dataset</li><li>`txId` is for transects. It is the '_' concatenated string derived from the longitude and latitude values, truncated to 4 decimals, of the transect's median point. Specifically, it is "_xx.xxxx_yy.yyyy_" where _xx.xxxx_ and _yy.yyyy_ are the median's longitude and latitude values truncated to 4 decimals.</li></ul> |
| `season` | Denotes the season, in "_sss_mmm_" format, where <ul><li>"_sss_" denotes the season: "_dry_" for dry, "_wet_" for wet and "_prm_" for permanent </li><li>"_mmm_" denotes the span of the season in calendar months: "_fma_" is for dry season of February-March-April, "_ond_" is for wet (post-monsoon) season of October-November-December and "_DnW_" is for permanent which is dry AND wet season. </li></ul>|
| `year` | Year. |
| `water_ha` | Area of water pixels in the feature, in hectares. |
| `notwater_ha` | Area of notwater pixels in the feature, in hectares. |
| `nodata_ha` | Area of nodata pixels in the feature, in hectares. |
| `nodataFrac` | Proportion of the feature's area with nodata pixels. |
| `system:index` | GEE system-generated unique identifier. |

```
| Attribute | Description |
|----------:|:------------|
| `HYBAS_ID` or `txId` | Feature's unique identifier <ul><li>`HYBAS_ID` is for basins. It is the basin's identifier `HYBAS_ID` in the HydroBASINS dataset</li><li>`txId` is for transects. It is the '_' concatenated string derived from the longitude and latitude values, truncated to 4 decimals, of the transect's median point. Specifically, it is "_xx.xxxx_yy.yyyy_" where _xx.xxxx_ and _yy.yyyy_ are the median's longitude and latitude values truncated to 4 decimals.</li></ul> |
| `season` | Denotes the season, in "_sss_mmm_" format, where <ul><li>"_sss_" denotes the season: "_dry_" for dry, "_wet_" for wet and "_prm_" for permanent </li><li>"_mmm_" denotes the span of the season in calendar months: "_fma_" is for dry season of February-March-April, "_ond_" is for wet (post-monsoon) season of October-November-December and "_DnW_" is for permanent which is dry AND wet season. </li></ul>|
| `year` | Year. |
| `water_ha` | Area of water pixels in the feature, in hectares. |
| `notwater_ha` | Area of notwater pixels in the feature, in hectares. |
| `nodata_ha` | Area of nodata pixels in the feature, in hectares. |
| `nodataFrac` | Proportion of the feature's area with nodata pixels. |
| `system:index` | GEE system-generated unique identifier. |
```
Below are the tables for the time series of annual surface water occurrence image collection, to be added after [line 19](https://github.com/samapriya/awesome-gee-community-datasets/blob/0efba24cc44a8e2f53ff1bb7233c22cc72cadf7a/docs/projects/india_river_trends.md?plain=1#L19)

| Bands | Description |
|----------:|:------------|
| <ul><li>`drySeasCompos_fma`</li><li>`wetSeasCompos_ond`</li><li>`prmSeasCompos_DnW`</ul> | Each pixel in these bands have one of 3 integer values (following the convention in the JRC water dataset, Pekel et al. 2016): <ul><li>`2`: a pixel with valid data and containing water (denoting a "water" pixel)</li><li>`1`: a pixel with valid data and not containing water (denoting a "notwater" pixel)</li><li>`0`: a pixel with no valid data (denoting a "nodata" pixel)</ul> |

| Properties | Description |
|----------:|:------------|
| `year` | year of the image. |
| `monsoonYearStartMonth` | Number (between 1-12) of the month when monsoon (or, hydrological) year starts. It is 6, indicating June, and is the same for all images. A year is taken to be June to May in this analysis. |
| `drySeasMonthsOffset` | Number of months after `monsoonYearStartMonth` when dry season starts. It is 8, indicating February. |
| `drySeasMonthsTag` | Suffix tag, in names of image bands, table columns, etc., indicating the 3 months of the dry season. |
| `wetSeasMonthsOffset` | Number of months after `monsoonYearStartMonth` when wet season starts. It is 4, indicating October. |
| `wetSeasMonthsTag` | Suffix tag, in names of image bands, table columns, etc., indicating the 3 months of the wet season. |

```
| Bands | Description |
|----------:|:------------|
| <ul><li>`drySeasCompos_fma`</li><li>`wetSeasCompos_ond`</li><li>`prmSeasCompos_DnW`</ul> | Each pixel in these bands have one of 3 integer values (following the convention in the JRC water dataset, Pekel et al. 2016): <ul><li>`2`: a pixel with valid data and containing water (denoting a "water" pixel)</li><li>`1`: a pixel with valid data and not containing water (denoting a "notwater" pixel)</li><li>`0`: a pixel with no valid data (denoting a "nodata" pixel)</ul> |

| Properties | Description |
|----------:|:------------|
| `year` | year of the image. |
| `monsoonYearStartMonth` | Number (between 1-12) of the month when monsoon (or, hydrological) year starts. It is 6, indicating June, and is the same for all images. A year is taken to be June to May in this analysis. |
| `drySeasMonthsOffset` | Number of months after `monsoonYearStartMonth` when dry season starts. It is 8, indicating February. |
| `drySeasMonthsTag` | Suffix tag, in names of image bands, table columns, etc., indicating the 3 months of the dry season. |
| `wetSeasMonthsOffset` | Number of months after `monsoonYearStartMonth` when wet season starts. It is 4, indicating October. |
| `wetSeasMonthsTag` | Suffix tag, in names of image bands, table columns, etc., indicating the 3 months of the wet season. |
```

**Comment by samapriya** [comment]
Thanks @pskoulgi 
I will make this edits next week sometime

**Comment by pskoulgi** [comment]
Thanks, @samapriya !

This one table, at [line 59](https://github.com/samapriya/awesome-gee-community-datasets/blob/27acbb1c2a7f1d4d66e4d481e57161f20578b7b3/docs/projects/india_river_trends.md?plain=1#L59) now, ended up mis-formatted though: what's gotten split over 4 rows should have all appeared in a single row, like below. It says that there are 3 bands, but they all have the same numerical formatting.

It would be great if this formatting can be fixed, when you get a chance. Thanks!

| Bands | Description |
|----------:|:------------|
| <ul><li>`drySeasCompos_fma`</li><li>`wetSeasCompos_ond`</li><li>`prmSeasCompos_DnW`</ul> | Each pixel in these bands have one of 3 integer values (following the convention in the JRC water dataset, Pekel et al. 2016): <ul><li>`2`: a pixel with valid data and containing water (denoting a "water" pixel)</li><li>`1`: a pixel with valid data and not containing water (denoting a "notwater" pixel)</li><li>`0`: a pixel with no valid data (denoting a "nodata" pixel)</ul> |


```
| Bands | Description |
|----------:|:------------|
| <ul><li>`drySeasCompos_fma`</li><li>`wetSeasCompos_ond`</li><li>`prmSeasCompos_DnW`</ul> | Each pixel in these bands have one of 3 integer values (following the convention in the JRC water dataset, Pekel et al. 2016): <ul><li>`2`: a pixel with valid data and containing water (denoting a "water" pixel)</li><li>`1`: a pixel with valid data and not containing water (denoting a "notwater" pixel)</li><li>`0`: a pixel with no valid data (denoting a "nodata" pixel)</ul> |

```
