### ISSUE TITLE
[Bug]: DynQual assets not accesible

### ISSUE THREAD

**Issue by Geethen** [samapriya/awesome-gee-community-datasets#229]
### Contact Details

geethen.singh@gmail.com

### Provide Dataset Link

https://gee-community-catalog.org/projects/dynqual/?h=dyn

### Describe the bug

The routed assets are not accessible. Please check the assets sharing status.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
Please specify which asset has access issues

**Comment by samapriya** [comment]
I have refreshed access to all assets in folder. Feel free to reopen issue if this has not been solved

**Comment by Geethen** [comment]
The error below still persists.
EEException: ImageCollection.load: ImageCollection asset 'projects/sat-io/open-datasets/DYNQUAL/routed_bod' not found (does not exist or caller does not have access).

This error is returned for the three routed assets
routed_fc = ee.ImageCollection("projects/sat-io/open-datasets/DYNQUAL/routed_fc")
routed_tds = ee.ImageCollection("projects/sat-io/open-datasets/DYNQUAL/routed_tds")
routed_bod = ee.ImageCollection("projects/sat-io/open-datasets/DYNQUAL/routed_bod")

**Comment by samapriya** [comment]
Seems like the path in the docs were wrong it is a dash - rather than an underscore _ . Try changing the paths for the routed paths. I changed the docs as well to reflect the change

**Comment by Geethen** [comment]
Thanks for the info.
