### ISSUE TITLE
[Bug]: link is not working, potentially assets not listed on catalog

### ISSUE THREAD

**Issue by Geethen** [samapriya/awesome-gee-community-datasets#230]
### Contact Details

geethen.singh@gmail.com

### Provide Dataset Link

https://gee-community-catalog.org/projects/global_tcc/?h=tree+c

### Describe the bug

With reference to the following statement "The most recent TCC version 2021.4 product suite released in 2023 includes several components, including an annual Science product with maps and data for years 2008-2021. You can find [additional information here](https://gee-community-catalog.org/projects/global_tcc/?h=tree+c) and download the [datasets here](https://e4ftl01.cr.usgs.gov/MEASURES/GFCC30TC.003/)" 

1) I can only access the 2000, 2005, 2010, 2015 files using the asset link: 
var GFCC30TC=  ee.ImageCollection("projects/sat-io/open-datasets/GFCC30TC");

2) when clicking on additional information- it links to the same page (https://gee-community-catalog.org/projects/global_tcc/?h=tree+c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
Seems the page links back to v3 even though it lists v4 and talks about the release. This might need more time to figure out closing this issue for now but adding it to the list to todos 
https://lcluc.umd.edu/metadata/global-30m-landsat-tree-canopy-version-4
