### ISSUE TITLE
 GHAP: Global High-resolution and High-quality Ambient Air Pollutants Dataset over Land

### ISSUE THREAD

**Issue by TC25** [samapriya/awesome-gee-community-datasets#235]
### Dataset description

Bbig data-derived gapless (spatial coverage = 100%) daily, monthy, and annual 1 km (i.e., D1K, M1K, and Y1K) global PM2.5 dataset over land for the years 2017 to 2022.

https://zenodo.org/communities/ghap/records?q=&l=list&p=1&s=10&sort=newest

### Earth Engine Snippet if dataset already in GEE

for example
```js
var asset_name = ee.ImageCollection("path to your collection")
```
Sample Code: Add a sample code maybe just adding your datasets in the code editor

### Enter license information

Creative Commons Attribution 4.0 International

### Keywords

air pollution, PM2.5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
This has been completed and will be added to the catalog soon. Thanks for contributing
