### ISSUE TITLE
[Dataset Title/Name]: S2_SR_HARMONIZED_SWISS

### ISSUE THREAD

**Issue by Tschoun** [samapriya/awesome-gee-community-datasets#239]
### Contact Details

joan.sturm@swisstopo.ch / david.oesch@swisstopo.ch

### Dataset description

The optical satellite data from Sentinel-2 (ESA) fully image Switzerland approximately every three days. The usefulness of the data is depending heavily on meteorological conditions such as clouds, the atmospheric correction, the applied registration of the data, and the data delivery (projection). We've optimized the existing processing steps and added our own post-processing to generate analysis ready surface reflectance data for Switzerland.

## Processing
- The input dataset is the Level 2A (surface reflectance) data from Sentinel-2: [S2_SR_HARMONIZED](https://developers.google.com/earth-engine/datasets/catalog/COPERNICUS_S2_SR_HARMONIZED?hl=en).
- For cloud detection the [CloudScore+](https://developers.google.com/earth-engine/datasets/catalog/GOOGLE_CLOUD_SCORE_PLUS_V1_S2_HARMONIZED?hl=en) dataset is used with a 0.6 threshold for the cs_cdf band to identify clouds. Additionally, a stricter 0.8 threshold is applied in a projection corridor of the clouds derived from the solar and satellite geometries.
- Using the same geometries as above in addition to a digital elevation model (swissALTI3D) terrain shadows are detected and added as a mask.
- The tiles from each overpass are mosaiced.
- Lastly, the mosaics are co-registered by the displacement vectors in relation to the Sentinel Ground Reference Image to achieve sub-pixel location accuracy. All the mosaics are saved in epsg:2056 (CH1903+ / LV95).

## Assets, bands & masks
Each overpass is mosaiced and there are two assets per overpass for the 10m and 20m spatial resolution.
The asset at 10m spatial resolution contains following bands:
- B2 (Blue)
- B3 (Green)
- B4 (Red)
- B8 (NIR)
- terrainShadowMask (binary mask for terrain shadow)
- cloudAndCloudShadowMask (binary mask for clouds and cloud shadows)
- reg_dx (offset in x direction from the co-registration)
- reg_dy (offset in y direction from the co-registration)
- reg_confidence (displacement confidence from the co-registration)
- cloudProbability (percentage of cloud probability)

The asset at 20m spatial resolution contains following bands:
- B8A (NIR 2)
- B11 (SWIR 1)
- B5 (Red Edge 1)

## Documentation & Code
[geocat.ch - the swiss geographic catalogue](https://www.[geocat.ch](https://www.geocat.ch/geonetwork/srv/eng/catalog.search#/metadata/7ae5cd5b-e872-4719-92c0-dc2f86c4d471)/geonetwork/srv/eng/catalog.search#/metadata/7ae5cd5b-e872-4719-92c0-dc2f86c4d471)

Code availability: The full code can be found in the [SATROMO GitHub Repository](https://github.com/swisstopo/topo-satromo).

Provided by: [Federal Office of Topography swisstopo](https://www.swisstopo.admin.ch/en)

### Earth Engine Snippet if dataset already in GEE

```js
var asset_name = ee.ImageCollection("projects/satromo-prod/assets/col/S2_SR_HARMONIZED_SWISS")
```

### 1. Legal basis
The use of free geodata and geoservices from swisstopo is governed by the following legal bases:

- Federal Act on Geoinformation (Geoinformation Act, GeoIA 510.62) Art. 10 ff
- Ordinance on Geoinformation (Geoinformation Ordinance, 510.620) Art. 20 ff
- swisstopo ordinance on fees and charges

### 2. Terms of use
The free geodata and geoservices of swisstopo may be used, distributed and made accessible. Furthermore, they may be enriched and processed and also used commercially.

A reference to the source is mandatory. In the case of digital or analogue representations and publications, as well as in the case of dissemination, one of the following source references must be attached in any case:

- Bundesamt für Landestopografie swisstopo
- Office fédéral de topographie swisstopo
- Ufficio federale di topografia swisstopo
- Uffizi federal da topografia swisstopo
- Federal Office of Topography swisstopo
- ©swisstopo

[Terms of use for free geodata and geoservices (OGD) from swisstopo](https://www.swisstopo.admin.ch/en/terms-of-use-free-geodata-and-geoservices)

Contains modified Copernicus Sentinel data.

### Keywords

BGDI; optical satellite imagery; Sentinel-2; surface reflectance; Analysis ready data

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
Since this is going to be continious improvements project closing this issue and following up on email for final review/data updates and metadata updates
