### ISSUE TITLE
High Resolution 1m Global Canopy Height Maps

### ISSUE THREAD

**Issue by GvdDool** [samapriya/awesome-gee-community-datasets#242]
### Contact Details

gijs.vandendool@gmail.com

### Provide Dataset Link

https://gee-community-catalog.org/projects/meta_trees/?h=1m

### Describe the update

The current description contains an inaccuracy and potential misuse of the data:
Original text:
The Global Canopy Height Maps dataset offers comprehensive insights into tree canopy heights worldwide, facilitating precise monitoring of forest ecosystems, carbon sequestration, and climate change mitigation efforts. Developed through collaboration between Meta and the World Resources Institute, this dataset stands as a cornerstone for understanding forest structure and dynamics.

Issue: the data set is not intended to be used as a monitoring dataset, but more as a snapshot stocktaking over the available data (2009-2020).

Suggested update:
The Global Canopy Height Maps dataset offers comprehensive insights into tree canopy heights worldwide, providing an overview of tree canopy presence and height for the analysed period (2009-2020), with eighty per cent of the data obtained from imagery acquired between 2018 and 2020. This **baseline** can be used as a reference for supplementing field-based measurements of carbon in carbon credit monitoring and verification schema. When newer imagery is available, the publicly shared model can be used to detect changes in canopy heights. Developed through a collaboration between Meta and the World Resources Institute, this dataset stands as a cornerstone for understanding forest structure and dynamics.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
The dataset description has now been fixed based on your ticket. Thank you for contributing and helping improve the community catalog. Closing this issue for now
