### ISSUE TITLE
ERA5 HEAT

### ISSUE THREAD

**Issue by EricRJensen** [samapriya/awesome-gee-community-datasets#243]
### Contact Details

Contact Climate Engine staff at climateengine@gmail.com

### Dataset description

**Description**
This dataset provides a complete historical reconstruction for a set of indices representing human thermal stress and discomfort in outdoor conditions. This dataset, also known as ERA5-HEAT (Human thErmAl comforT) represents the current state-of-the-art for bioclimatology data record production. The dataset is organized around two main variables: 1) the mean radiant temperature (MRT) and 2) the universal thermal climate index (UTCI) These variables describe how the human body experiences atmospheric conditions, specifically air temperature, humidity, ventilation and radiation. 

The dataset is computed using the ERA5 reanalysis from the European Centre for Medium-Range Forecasts (ECMWF). ERA5 combines model data with observations from across the world to provide a globally complete and consistent description of the Earth’s climate and its evolution in recent decades. ERA5 is regarded as a good proxy for observed atmospheric conditions.

**Spatial extent**: Global
**Spatial resolution:** 27.75km (.25 deg)
**Temporal resolution:** Daily
**Time span:** 1940-01-01 to present
**Update frequency:** Updated daily with lag of 2 weeks

**Variables**
Mean Radiant Temperature (‘mrt_mean’, ‘mrt_max’, ‘mrt_min’, ‘mrt_median’)
- Units: Degrees Kelvin
- Scale factor: 1.0
- _Provided in four bands for daily mean, maximum, minimum, and median._
Universal Thermal Climate Index (‘utci_mean’, ‘utci_max’, ‘utci_min’, ‘utci_median’)
- Units: Degrees Kelvin
- Scale factor: 1.0
- _Provided in four bands for daily mean, maximum, minimum, and median._

**External link**
https://cds.climate.copernicus.eu/cdsapp#!/dataset/derived-utci-historical?tab=overview 

**Citation**
Di Napoli C., Barnard C., Prudhomme C., Cloke HL and Pappenberger F. (2020): Thermal comfort indices derived from ERA5 reanalysis. Copernicus Climate Change Service (C3S) Climate Data Store (CDS). DOI: 10.24381/cds.553b7518 (Accessed on DD-MMM-YYYY)

### Earth Engine Snippet if dataset already in GEE

```js
// Read in Image Collection and get first image
var era5_heat_ic = ee.ImageCollection('projects/climate-engine-pro/assets/ce-era5-heat')
var era5_heat_i = era5_heat_ic.first()

// Print first image to see bands
print(era5_heat_i)

// Visualize select bands from first image — additional bands are present in the Image Collection
var temp_palette = ["#b2182b", "#ef8a62", "#fddbc7", "#f7f7f7", "#d1e5f0", "#67a9cf", "#2166ac"].reverse()
Map.addLayer(era5_heat_i.select('mrt_mean').selfMask().subtract(273.15), {min: -10, max: 50, palette: temp_palette}, 'Mean Radiant Temperature, Daily Mean')
Map.addLayer(era5_heat_i.select('utci_mean').selfMask().subtract(273.15), {min: -10, max: 50, palette: temp_palette}, 'Universal Thermal Climate Index, Daily Mean')
```

### Enter license information

ECMWF license agreement available here: https://cds.climate.copernicus.eu/api/v2/terms/static/licence-to-use-copernicus-products.pdf 

### Keywords

heat exposure, climate, reanalysis, global, era5, thermal, public health, climate engine

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
This has now been completed and will be available this week. Thank you for contributing
