### ISSUE TITLE
[Dataset Title/Name]: UKFields

### ISSUE THREAD

**Issue by Spiruel** [samapriya/awesome-gee-community-datasets#245]
### Contact Details

eesjb@leeds.ac.uk

### Dataset description

The ukfields dataset is a publicly accessible Earth Engine asset of automatically delineated field boundaries spanning England, Wales, Scotland, and Northern Ireland.

The ukfields dataset contains field boundaries for the United Kingdom, derived from harmonic composites of Sentinel 2 imagery captured in 2021. The delineation process leveraged the Segment Anything Model (SAM) from Meta, ensuring efficient field segmentation at scale. The segmented fields have been masked to a 2021 Dynamic World composite of cropland.

Bancroft, S., & Wilkins, J. (2024). UKFields (1.0.0) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.11110206

### Earth Engine Snippet if dataset already in GEE

```js
var ukfields = ee.ImageCollection("users/spiruel/ukfields")
```

### Enter license information

CC-BY-4.0

### Keywords

fields, agriculture, UK, england, scotland, wales, northern-ireland

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
Hi @Spiruel 
Couple of things I noticed
* First of all this is a FeatureCollection not an Image Collection
* There is no geometry attached to any of these fields as a result its a table that cannot be added to a map

Can you share the original files/geojson/shapefiles/CSV or whatever you produced. Also is this part of some research work or does it have any citation?

**Comment by samapriya** [comment]
I have reprocessed your feature collection and removed any feature with missing geometry. You can try the example code [here](https://code.earthengine.google.com/128a5903c770db1e754e850e62554a3b)

Let me know if this is part of some research or if it has a citation/DOI

**Comment by samapriya** [comment]
Great I wonder if there is a peer reviewed article this work is related to. Totally fine if not but I wanted to check since most datasets in the catalog relate to a peer reviewed article.

I can also add a note that said this is an implementation of SAM but the output field boundaries have not been validated or there isn't a peer reviewed work attached to this ? Let me know if my assumption is wrong. Happy to work with you on this

**Comment by samapriya** [comment]
This has now been completed and will be available this week. Thank you for contributing. Watch the changelog for links available soon :)

**Comment by samapriya** [comment]
Here is a link to the [page](https://gee-community-catalog.org/projects/fiboa_uk)
