### ISSUE TITLE
Surface Area of Rivers and Lakes (SARL)

### ISSUE THREAD

**Issue by BjornNyberg** [samapriya/awesome-gee-community-datasets#248]
### Contact Details

bjorn.nyberg@uib.no

### Dataset description

The Surface Area of River and Lakes (SARL) dataset by Nyberg et al., show the 38-years of seasonal and permanent water surface area change in rivers and lakes. The raster datasets are available globally between 1984 to 2022 at a 30 m resolution showing 7 classes that represent:

- 0: Background Value
- 1: Permanent River
- 2: Permanent Lake
- 3: Seasonal River
- 4: Seasonal Lake
- 5: No Data Lakes
- 6: No Data Rivers

The open access article published in Hydrology and Earth System Sciences can be found [here](https://hess.copernicus.org/articles/28/1653/2024/). In addition, the datasets are archived in a zenodo repository available at this [url](https://zenodo.org/records/6895820).

### Earth Engine Snippet if dataset already in GEE

var image = ee.Image('users/bjornburrnyberg/SARL');

Map.setOptions('SATELLITE');

var colors = {min:1,max:6, palette:['#0571b0','#d01c8b','#92c5de','#f1b6da','#999999','#ffffff']};

var img = image.select('Y2020');
var mask = img.gt(0);

Map.addLayer(img.mask(mask),colors,'Y2020');

### Enter license information

Creative Commons Attribution 4.0 International

### Keywords

water, water change, rivers, lakes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
This has now been completed and will be made available next week. Thank you for contributing. :) 

The dataset has also been copied over to ee.Image("projects/sat-io/open-datasets/SARL") for consistency in path
