### ISSUE TITLE
High-resolution gridded precipitation dataset for Peruvian and Ecuadorian watersheds

### ISSUE THREAD

**Issue by csaybar** [samapriya/awesome-gee-community-datasets#25]
### Dataset Name

RAIN4PE is a novel daily gridded precipitation dataset obtained by merging multi-source precipitation data (satellite-based Climate Hazards Group InfraRed Precipitation, CHIRP (Funk et al. 2015), reanalysis ERA5 (Hersbach et al. 2020), and ground-based precipitation) with terrain elevation using the random forest regression method. Furthermore, RAIN4PE is hydrologically corrected using streamflow data in catchments with precipitation underestimation through reverse hydrology. Hence, RAIN4PE is the only gridded precipitation product for Peru and Ecuador, which benefits from maximum available in-situ observations, multiple precipitation sources, elevation data, and is supplemented by streamflow data to correct the precipitation underestimation over páramos and montane catchments. 

<center>
<img src="https://user-images.githubusercontent.com/16768318/147897036-960ea777-6bac-436c-9c2f-dbcc773b143e.gif" width=50%>
</center>

Currently included layers are:

#### Earth Engine Snippet: Annual mean

```js
var rain4pe_clim = ee.ImageCollection('users/csaybar/rainpe/annual_mean')
```
Sample Code: https://code.earthengine.google.com/35895dc6b3dda529d308673018cadced

#### Earth Engine Snippet: Monthly climatology

```js
var rain4pe_clim = ee.ImageCollection('users/csaybar/rainpe/monthly_clim')
```

Sample Code: https://code.earthengine.google.com/5f88fb66ff5d9799c0bcd9ab7bccd200

#### Earth Engine Snippet: Monthly data

```js
var rain4pe_clim = ee.ImageCollection('users/csaybar/rainpe/monthly')
```

Sample Code: https://code.earthengine.google.com/3374b08b0eacaf0a4003d9098a4d56b3

#### Earth Engine Snippet: Daily data

```js
var rain4pe_daily01 = ee.ImageCollection('users/csaybar/rainpe/daily') // 1981-2001
var rain4pe_daily02 = ee.ImageCollection('users/ryali93/rainpe/daily') // 2002-2015
var rain4pe_daily = rain4pe_daily01.merge(rain4pe_daily02) 
```

Sample Code: https://code.earthengine.google.com/f62690ab93a65964ce753f080309e9eb

#### citation

**When using the data please cite:**

```
Fernandez-Palomino, C. A.; Hattermann, F. F.; Krysanova, V.; Lobanova, A.; Vega-Jácome, F.; Lavado, W.;
Santini, W.; Aybar, C.; Bronstert, A. (2021). Rain for Peru and Ecuador (RAIN4PE). V. 1.0. GFZ Data
Services. https://doi.org/10.5880/pik.2020.010
```

**The data are supplementary material to:**

```
Fernandez-Palomino, C. A.; Hattermann, F. F.; Krysanova, V.; Lobanova, A.; Vega-Jácome, F.; Lavado, W.;
Santini, W.; Aybar, C.; Bronstert, A. (2021). A novel high-resolution gridded precipitation dataset for
Peruvian and Ecuadorian watersheds – development and hydrological evaluation. Journal of
Hydrometeorology. https://doi.org/10.1175/jhm-d-20-0285.1
```

#### License

This work is licensed under a Creative Commons Attribution 4.0 International License. You are free to copy and redistribute the material in any medium or format, and to transform and build upon the material for any purpose, even commercially. You must give appropriate credit, provide a link to the license, and indicate if changes were made.

Curated by: Cesar Aybar

Keywords: precipitation, streamflow, Peru, Ecuador, random forest, SWAT, reverse hydrology, satellite data, Earth observation, GIS.

**Comment by samapriya** [comment]
Hi @csaybar 
Can I confirm that the daily data users users/ryali93 is also something you are hosting? just want to make sure I wasn't missing out I know users/csaybar is you :) The page is now live and [you can find it here](https://samapriya.github.io/awesome-gee-community-datasets/projects/gridded_ppt/). Let me know if all looks good and feel free to close the issue once confirmed. Thank you so much for contributing

**Comment by csaybar** [comment]
Hi, @samapriya thanks for the super fast reply :)

Yes, unfortunately, the dataset surpasses the GEE asset quota ([the max number of assets is 10k](https://gis.stackexchange.com/questions/401334/google-earth-engine-asset-quota)). Therefore, @ryali93 and I split the dataset and stored it together. Since we both will work with the dataset, there won't be any problem :)

Happy new year :partying_face:

**Comment by samapriya** [comment]
Yeah I understand only new accounts have a limit of 50k older ones like ours had it at 10k, I am copying both of those into a joint collection and I should be able to combine it that way. Let me know if this is useful, if yes that I am happy to update the collection to the joint collection path.

```
projects/sat-io/open-datasets/rainpe/daily
```

Thank you again for contributing. Closing the issue now, will update the ticket when the collection merge is completed

**Comment by csaybar** [comment]
Hi @samapriya yes that would be awesome. Thank you, let me know if I can help with something :100:

**Comment by samapriya** [comment]
This combined asset is now completed @csaybar I can update the code and the description tomorrow to reflect it , hope this helps

projects/sat-io/open-datasets/rainpe/daily ===> 1 GB
Total number of items in collection: 12783

**Comment by samapriya** [comment]
I have updated the collection info, code link and the catalog to reflect the new collection

**Comment by csaybar** [comment]
Thank u so much @samapriya it works perfectly from my side :).
