### ISSUE TITLE
Global Peatland Extent (Peat-ML)

### ISSUE THREAD

**Issue by pinkychow1010** [samapriya/awesome-gee-community-datasets#254]
### Contact Details

pinkychow1010@gmail.com

### Dataset description

**Peatlands**, waterlogged terrestrial wetland ecosystems, store large amounts of soil carbon and freshwater, constituting an important component of the global carbon and hydrologic cycles. Accurate information on the global distribution of peatlands is critically needed to simulate the effects of climate change on the global carbon and hydrologic balance. **Peat-ML** is a spatially continuous **global map of peatland fractional coverage** generated using machine learning techniques, training with **climate, geomorphological and soil data**, along with **remotely-sensed vegetation indices**. Available maps of peatland fractional coverage for 14 relatively extensive regions were used along with mapped ecoregions of non-peatland areas to train the statistical model. The dataset is published on 2021 (https://zenodo.org/records/5794336) in NetCDF format. That approach yielded an average **r squared of 0.73** with a root mean squared error and mean bias error of **9.11%** and **-0.36%**, respectively. the associated paper is published [here](https://gmd.copernicus.org/articles/15/4709/2022/).

<br>

![image](https://github.com/samapriya/awesome-gee-community-datasets/assets/57500332/f2733723-c8ac-44bf-afc7-ad689017e9cb)
*Workflow for dataset generation (Joe R. Melton et al., 2022)*

<br>

![image](https://github.com/samapriya/awesome-gee-community-datasets/assets/57500332/b5245da1-b232-4158-a455-3b475b13f52a)
*Example data visualization of peatland distribution in Indonesia*

### Earth Engine Snippet if dataset already in GEE

Loading Peatland Distribution for Indonesia
```js
// Load administrative boundaries for Indonesia
var admin1 = ee.FeatureCollection("projects/sat-io/open-datasets/geoboundaries/HPSCGS-ADM1");
var geometry = admin1.filter(ee.Filter.eq('shapeGroup', 'IDN'));

Map.centerObject(geometry, 4);
Map.setOptions("Hybrid");

var peat = ee.Image("projects/ee-pinkychow1010/assets/global_peatland_2022") // just an example, not the identical dataset
    .clip(geometry)
    .unmask();

// Display the results
Map.addLayer(peat.clip(geometry), 
  {min: 0, max: 100, palette: ['#f7fcf5', '#c7e9c0', '#74c476', '#238b45', '#00441b']}, 
  'Peatland Distribution', true
  );
```

### Enter license information

This work is distributed under the Creative Commons Attribution 4.0 License.

### Keywords

peatland, soil carbon, wetland, ecosystem

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
This has been completed and will be included in the upcoming release. Check the changelog for links and updates and thank you for contributing
