### ISSUE TITLE
The Global Peatland Map 2.0

### ISSUE THREAD

**Issue by pinkychow1010** [samapriya/awesome-gee-community-datasets#255]
### Contact Details

pinkychow1010@gmail.com

### Dataset description

The **‘Global Peatland Map 2.0’**, launched by the **Global Peatlands Initiative** partners at the Global Peatland Pavilion during UNFCCC COP26, improves the base knowledge on the location and extent of peatlands worldwide. This dataset collates and integrates data on location, extent and drainage status of peatlands and organic soils worldwide and for 268 individual countries and regions. It is a composite map showing global peatlands, organic soils and suitable proxy data, mainly based on external data, supplemented by mapping at **Greifswald Mire Centre**. This dataset was used for map production, statistics and analysis in the **Global Peatland Assessment 2022**.

>Format: GeoTiff 
Projection: WGS 84
Pixel Values: 1= peat dominated, 2= peat in soil mosaic
Spatial Resolution: roughly 1x1 km

**Data Download:** https://nextcloud.uni-greifswald.de/index.php/s/s7Ln5QKxdQG5aaA

**Project Website:** https://greifswaldmoor.de/global-peatland-database-en.html

**Author:** The dataset was compiled by the Greifswald Mire Centre with data of the Global Peatland Database.

**Citation:** Greifswald Mire Centre (2022) Global Peatland Map 2.0. Underlying dataset of the UNEP Global Peatland Assessment - The State of the World’s Peatlands: Evidence for action toward the conservation, restoration, and sustainable management of peatlands, Global Peatlands Initiative, United Nations Environment Programme, Nairobi.

![image](https://github.com/samapriya/awesome-gee-community-datasets/assets/57500332/7f290701-c159-4bee-8d1c-4c856fefba54)

### Earth Engine Snippet if dataset already in GEE

Peatland Distribution in Indonesia
```js

// Load administrative boundaries for Indonesia
var admin1 = ee.FeatureCollection("projects/sat-io/open-datasets/geoboundaries/HPSCGS-ADM1");
var geometry = admin1.filter(ee.Filter.eq('shapeGroup', 'IDN'));

Map.centerObject(geometry, 4);
Map.setOptions("Hybrid");

var peat = ee.Image("projects/ee-pinkychow1010/assets/global_peatland_2022")
    .clip(geometry)
    .unmask();

// Display the results
Map.addLayer(peat.clip(geometry), 
  {min: 0, max: 1, palette: ['#f7fcf5', '#c7e9c0', '#74c476', '#238b45', '#00441b']}, 
  'Peatland Distribution', true
  );

```

### Enter license information

CC BY-NC-SA 4.0
Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International

This license requires that reusers give credit to the creator. It allows reusers to distribute, remix, adapt, and build upon the material in any medium or format, for noncommercial purposes only. If others modify or adapt the material, they must license the modified material under identical terms.

### Keywords

peatland, wetland, organic soil, soil carbon, ecosystem

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
This has been completed and will be added to next release. Check changelog for more details and thank you for contributing
