### ISSUE TITLE
Time-series global 30 m wetland maps from 2000 to 2022

### ISSUE THREAD

**Issue by WalidGharianiEAGLE** [samapriya/awesome-gee-community-datasets#257]
### Dataset description

A novel global 30 m wetland annual dataset with fine classification system is generated, covering the period of 2000-2022 and containing 8 wetland subcategories (permanent water, swamp, marsh, flooded flats, saline, mangrove forest, salt marshes, and tidal flats). 

- Paper: Zhang, X., Liu, L., Zhao, T. et al. Global annual wetland dataset at 30 m with a fine classification system from 2000 to 2022. Sci Data 11, 310 (2024). https://doi.org/10.1038/s41597-024-03143-0 
- Dataset on Zenodo: Liu, L., & Zhang, X. Time-series global 30 m wetland maps from 2000 to 2022, Zenodo, https://doi.org/10.5281/zenodo.10068479 (2023).

### Earth Engine Snippet if dataset already in GEE

for example
```js
var asset_name = ee.ImageCollection("path to your collection")
```
Sample Code: Add a sample code maybe just adding your datasets in the code editor

### Enter license information

Creative Commons Attribution 4.0 International

### Keywords

wetland, classification

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
This has now been completed and will be made available in the next release. Thank you for contributing

**Comment by samapriya** [comment]
Sorry for the delay in getting this to you, here is the link https://gee-community-catalog.org/projects/gwl_fcs
