### ISSUE TITLE
A global database of nature-based carbon offset project boundaries

### ISSUE THREAD

**Issue by FilipeSilveira-N** [samapriya/awesome-gee-community-datasets#259]
### Contact Details

Corresponding author(s): Elias Ayrey (elias@renoster.co)

### Dataset description

Nature-based climate solutions (NBS) have become an important component of  strategies aiming to reduce atmospheric CO2 and mitigate climate change impacts. Carbon offsets have emerged as one of the most widely implemented NBS strategies, however, these projects have also been criticized for exaggerating offsets. Verifying the efficacy of NBS-derived carbon offset is complicated by a lack of readily available geospatial boundary data. Herein, we detail methods and present a database of nature-based offset project boundaries. This database provides the locations of 575 NBS projects distributed across 55 countries. Geospatial boundaries were aggregated using a combination of scraping data from carbon project registries  (n=433, 75.3%) as well as manual georeferencing and digitization (n=127, 22.1%). Database entries include three varieties of carbon projects: avoided deforestation, afforestation, reforestation and re-vegetation, and improved forest management. An accuracy assessment of the georeferencing and digitizing process indicated a high degree of accuracy (intersection over union score of 0.98 +/- 0.015).

Karnik, A., Kilbride, J., Goodbody, T., Rachel, R., & Ayrey, E. (2024). A global database of nature-based carbon offset project boundaries [Data set]. Zenodo. https://doi.org/10.5281/zenodo.11459391 

### Earth Engine Snippet if dataset already in GEE

projects/ee-filipesilveiran/assets/Databases/Carbon_offsets_All_continents_pol

Sample Code: 
//EXISTING CARBON PROJECTS////
    var carbonoffsetscol = ee.FeatureCollection('projects/ee-filipesilveiran/assets/Databases/Carbon_offsets_All_continents_pol');
    
    var visParams = {
      palette: ['#9ab555'],
      min: 0.0,
      max: 1550000.0,
      opacity: 0.8,
    };
    var carbonoffsets = ee.Image().float().paint(carbonoffsetscol, 'REP_AREA');

    Map.addLayer(carbonoffsets, visParams, 'Existing carbon projects area');
   

### Enter license information

Creative Commons Attribution 4.0 International

### Keywords

carbon, carbon offsets, NBS, climate change, Nature-based climate solutions, Carbon offsets, Geospatial boundaries, Georeferencing,Forest carbon

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
Sorry this took a while but this has been completed and added to the next release

**Comment by sander-justdiggit** [comment]
Thanks for the dataset and adding it to this awesome platform!

When using it shows this error:
`Layer error: Collection.loadTable: Collection asset 'projects/sat-io/open-datasets/CARBON-OFFSET-PROJECTS-GLOBAL' not found.`
Perhaps it's not publicly shared, or the path is wrong. The asset as referred to by the submitter does work by the way (projects/ee-filipesilveiran/assets/Databases/Carbon_offsets_All_continents_pol).
