### ISSUE TITLE
Dataset Name

### ISSUE THREAD

**Issue by EricRJensen** [samapriya/awesome-gee-community-datasets#26]
Follow the underlying template when creating an update dataset request

### Dataset Name and Catalog Page
Rangeland Analysis Platform Vegetation Cover and Rangeland Production datasets

### Dataset update , version and release date
RAP v3 was released on 2021-01-01

Primary changes include:
- Use of Landsat Collection 2
- Addition of the National Park Service Northern Colorado Plateau Network (NCPN) monitoring data for cover training
- Identify agriculture, development, and water
- Addition of the eastern states

### Updated dataset link
No change made to the link, still available through apps hosted at https://rangelands.app/

```js
// Vegetation Cover
var RAP_veg = ee.ImageCollection("projects/rangeland-analysis-platform/vegetation-cover-v3")

// Net Primary Production (annual)
var RAP_npp = ee.ImageCollection("projects/rangeland-analysis-platform/npp-partitioned-v3")
```

### Reason for update
Dataset was updated based on specifications provided above. Updated validation statistics provided here: https://rangelands.app/products/rapV3/

### Updated License
N/A

### Relationship to Dataset
Data Applications and Outreach Coordinator for Rangeland Analysis Platform

Sample Code: Link to updated Google Earth Engine scripts for v3 provided here: https://support.rangelands.app/article/61-processing-rap-data-in-google-earth-engine

### Updated image for page
![RAP_v3](https://user-images.githubusercontent.com/33233973/148469528-e8e45e3b-bee6-4c00-907e-4f3b3dfb35c1.JPG)

Last updated: 2021-01-01

**Comment by samapriya** [comment]
Do you mean this was releases 2022-01-01 I am just confirming since you said 2021-01-01 which would make it more than a year old

**Comment by EricRJensen** [comment]
My mistake, yes, 2022-01-01. Haven’t quite caught up with the year change, I guess! Thanks.


Eric

**Comment by EricRJensen** [comment]
Please also replace this paragraph:

 

Vegetation Cover: Rangeland Analysis Platform (RAP) Vegetation Cover, version 2.0 consists of gridded fractional estimates of plant functional groups for rangelands in the western United States. The estimates are produced at 30-meter spatial resolution for each year between 1984–present. The five plant functional groups are Annual Forbs and Grasses, Perennial Forbs and Grasses, Shrubs, Trees, and Bare Ground. Cover values are reported as percentages on a pixel-by-pixel basis. The estimates were produced using a temporal convolutional network using field measures of plant functional groups collected by the Natural Resources Conservation Service Natural Resources Inventory (NRI) program and the Bureau of Land Management Assessment, Inventory, and Monitoring (AIM) program alongside spatially continuous earth observations from Landsat TM, ETM, and OLI.

 

With this:

 

Vegetation Cover: Rangeland Analysis Platform (RAP) Vegetation Cover, version 3.0 consists of gridded fractional estimates of plant functional groups for rangelands in the continental United States. The estimates are produced at 30-meter spatial resolution for each year between 1984–present. The six plant functional groups are Annual Forbs and Grasses, Perennial Forbs and Grasses, Shrubs, Trees, Litter, and Bare Ground. Cover values are reported as percentages on a pixel-by-pixel basis. The estimates were produced using a temporal convolutional network using field measures of plant functional groups collected by the Natural Resources Conservation Service Natural Resources Inventory (NRI) program, the Bureau of Land Management Assessment, Inventory, and Monitoring (AIM) program, and the National Park Service Northern Colorado Plateau Network (NCPN) alongside spatially continuous earth observations from Landsat TM, ETM+, and OLI Collection 2.

 

Thank you

**Comment by samapriya** [comment]
This has now been completed and updated let me know if there is an updated paragraph for Herbaceous Biomass which is still at v1.0 . Feel free to run final checks and close out the issue once okay, I have also updated the catalog JSON and CSV as well as added this to the latest changelog. Thank you for helping push updates :)

**Comment by EricRJensen** [comment]
D’oh! I missed that. Can you update that paragraph from :

 

Herbaceous Biomass: Rangeland Analysis Platform (RAP) Herbaceous Biomass, version 1.0 consists of gridded estimates of herbaceous aboveground biomass, partitioned by annual forbs and grasses and perennial forbs and grasses. The estimates are produced at 30m spatial resolution from 1986-present. Estimates are provided annually and at 16-day intervals. Values are reported in pounds per acre and represent new growth of biomass – estimates do not reflect standing biomass from previous years. Estimates are calculated using a light use efficiency model (to estimate net primary production in terms of carbon) which is then allocated to above ground and below ground pools (based on mean annual temperature) and further converted to biomass using a carbon-to-dry matter ratio.

 

Rangeland Production: Rangeland Analysis Platform (RAP) Rangeland Production, version 3.0 consists of gridded estimates of herbaceous aboveground biomass, partitioned into vegetation types for annual forbs and grasses and perennial forbs and grasses. The estimates are produced at 30m spatial resolution from 1986-present. Estimates are provided annually and at 16-day intervals. Values are reported in terms of net primary productivity which can be converted to pounds per acre of new growth of aboveground biomass using the function in the Google Earth Engine script below– estimates do not reflect standing biomass from previous years. Estimates are calculated using a light use efficiency model (to estimate net primary production in terms of carbon) which is then allocated to aboveground and belowground pools (based on mean annual temperature) and further converted to biomass using a carbon-to-dry matter ratio.

 

Thanks again,

Eric

**Comment by samapriya** [comment]
Thank you this has now been completed :) thank you for the updates

**Comment by EricRJensen** [comment]
Fantastic, it looks great. Much appreciated, Samapriya! 

 

I’ll be directing people to it on Twitter and LinkedIn and highlighting your great work early next week.

 

Eric
