### ISSUE TITLE
High-resolution annual forest land cover maps for Canada's forested ecosystems (1984-2022)

### ISSUE THREAD

**Issue by S-Bronson** [samapriya/awesome-gee-community-datasets#262]
### Contact Details

spencer.bronson@nrcan-rncan.gc.ca

### Provide Dataset Link

https://gee-community-catalog.org/projects/ca_lc/

### Describe the update

Annual rasters have been revised with up-to-date data and will need to be updated in Awesome-GEE. Date range now includes years 2020, 2021, and 2022.

The dataset description will need to be changed to the following,

‘‘‘
High-resolution annual forest land cover maps for Canada's forested ecosystems (1984-2022)

The annual time series of forest land cover maps are national in scope (entire 650 million hectare forested ecosystem) and represent a wall-to-wall land cover characterization yearly from 1984 to 2022. These time-series land cover maps were produced from annual time-series of Landsat image composites, forest change information, and ancillary topographic and hydrologic data following the framework described in Hermosilla et al. (2022), which builds upon the approach introduced in Hermosilla et al. (2018). The methodological innovations included (i) a refined training pool derived from existing land cover products using airborne and spaceborne measures of forest structure; (ii) selection of training samples proportionally to the land cover distribution using a distance=weighted approach; and (iii) generation of regional classification models using a 150x150 km tiling system. Maps are post-processed using disturbance information to ensure logical class transitions over time using a Hidden Markov Model. Hidden Markov Models assess individual year class likelihoods to reduce variability and possible noise in year-on-year class assignments (for instances when class likelihoods are similar).
For an overview on the data, image processing, and time series change detection methods applied, as well as information on independent accuracy assessment of the data, see Hermosilla et al. (2022) No. 112780. DOI: https://doi.org/10.1016/j.rse.2021.112780 and Hermosilla et al. (2018) https://www.tandfonline.com/doi/full/10.1080/07038992.2018.1437719

The data represents annual forest land cover of Canada's forested ecosystems for 1984-2022. An image compositing window of August 1 -30 days was used to generate the best-available-pixel (BAP) image composites used as the source data for land cover classification. The science and methods developed to generate the information outcomes shown here, that track and characterize the history of Canada's forests, were led by Canadian Forest Service of Natural Resources Canada, partnered with the University of British Columbia, with support from the Canadian Space Agency, augmented by processing capacity from WestGrid of Compute Canada.
‘‘‘

### Relevant additional information

The sections that require modifications are the **title**, **description**, and **input dataset**. The dataset (**all years from 1984 – 2022**) has been modified and can be found in this shared folder in GEE.
users/mesospencer/VLCE_1984-2022

or individual rasters for 1984-2022 can be found by modifying the link below.
[https://code.earthengine.google.com/?asset=users/mesospencer/VLCE_1984-2022/CA_forest_VLCE2_<<year>>](https://code.earthengine.google.com/?asset=users/mesospencer/VLCE_1984-2022/CA_forest_VLCE2_%3c%3cyear%3e%3e)
Example:
https://code.earthengine.google.com/?asset=users/mesospencer/VLCE_1984-2022/CA_forest_VLCE2_2021

Alternatively, the dataset can be downloaded from the NFIS webpage at a later date (dataset is actively being updated on the NFIS webpage, it may take a week to be uploaded),
https://opendata.nfis.org/mapserver/nfis-change_eng.html
Found under the titled “Land cover 1984-2022 Version 2”

the following areas do not require any changes,
-	Citation
-	Class schema
-	Earth engine snippet (other than the inclusion of the updated 1984-2022 dataset)
-	License

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by S-Bronson** [comment]
I hope my links to the data in my assets is correct. Please tell me if it is not working :)

Cheers,
    Spencer

**Comment by samapriya** [comment]
This has now been completed and the collection has been completed. Thank you for contributing
