### ISSUE TITLE
Canada 2023 Wildfires

### ISSUE THREAD

**Issue by S-Bronson** [samapriya/awesome-gee-community-datasets#263]
### Contact Details

spencer.bronson@nrcan-rncan.gc.ca

### Canada 2023 Wildfires

Canada’s 2023 wildfire season represented the largest area burned in a single fire season in Canada’s modern history. Using the Tracking Intra- and Inter-year Change (TIIC) algorithm, wildfires occurring within Canada’s forested ecosystems during the 2023 fire season were detected at a 30-m resolution. Time series data used to identify wildfires originated from Sentinel-2A and -2B, and Landsat-8 and -9. Fires have been grouped into two classes based on detection period: summer fires and fall fires. Summer fires were detected between May 30 and September 17, and fall fires were detected between September 17 and October 25. For summer fires, burned pixels were identified by TIIC as changed and typed as fire. For the fall period, TIIC only detected changes within a 4-km buffer of NRCan fire perimeters (https://cwfis.cfs.nrcan.gc.ca/datamart). This approach was used to limit commission errors that can occur due to known limitations of mapping with optical data in the fall due to phenology, snow cover, or low sun angles. For the 2023 fire season, the TIIC algorithm detected 12.74 Mha of burned area in Canada’s forested ecozones, representing 1.8% of the total forest-dominated ecozone area. Of the 12.74 Mha, 11.57 Mha (90.9%) was burned by summer fires and 1.16 Mha (9.1%) by fall fires (Pelletier et al., 2024).

#### Citation
```
Pelletier, F., Cardille, J.A., Wulder, M.A., White, J.C., Hermosilla, T., 2024. Revisiting the 2023 wildfire season in Canada. Science of Remote Sensing. 10, 100145. https://doi.org/10.1016/j.srs.2024.100145

### Earth Engine Snippet if dataset already in GEE

#### Code Snippet: 
```js


// Define a dictionary which will be used to make legend and visualize image on map
var dict = {
  "names":    ["Summer Fire", "Fall Fire"],
    "colors": ["#de2f14", "#dec314"]};

Map.setCenter(-97.61655457157725, 55.6280720462063, 4)


// Add image to the map
Map.addLayer(image, {min:1, max:2, palette:dict['colors']}, 'Summer-Fall 2023 Wildfires')

/////////////////////////////////////////////////////////////////////////

var legend = ui.Panel({
  style: {
    position: 'middle-right',
    padding: '8px 15px'
  }
});

// Create and add the legend title.
var legendTitle = ui.Label({
  value: 'Summer-Fall 2023 Wildfire',
  style: {
    fontWeight: 'bold',
    fontSize: '18px',
    margin: '0 0 4px 0',
    padding: '0'
  }
});
legend.add(legendTitle);

// Creates and styles 1 row of the legend.
var makeRow = function(color, name) {
  // Create the label that is actually the colored box.
  var colorBox = ui.Label({
    style: {
      backgroundColor: color,
      // Use padding to give the box height and width.
      padding: '8px',
      margin: '0 0 4px 0'
    }
  });

// Create the label filled with the description text.
var description = ui.Label({
  value: name,
  style: {margin: '0 0 4px 6px'}
});

return ui.Panel({
  widgets: [colorBox, description],
  layout: ui.Panel.Layout.Flow('horizontal')
});
  
};
var palette = dict['colors'];
var names = dict['names'];

for (var i = 0; i < names.length; i++) {
  legend.add(makeRow(palette[i], names[i]));
}

// Print the panel containing the legend
print(legend);

```

#### Download link: 
https://opendata.nfis.org/downloads/forest_change/CA_Forest_Fires_2023.zip

#### License Information:
Open Government Licence - Canada (http://open.canada.ca/en/open-government-licence-canada)

### Keywords

Wildfire, Tracking Intra- Inter-year Change (TIIC), Landsat, Sentinel, Burned Area, Fire Occurrence, Canada

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by S-Bronson** [comment]
The dataset can should be accessible to you here,
https://code.earthengine.google.com/?asset=users/mesospencer/CA_Forest_Wildfire_2023_Summer_Fall

I will add a link to download the original dataset in the near future, when it is published online.

**Comment by S-Bronson** [comment]
I have added the download link to the body of the original request. Alternatively, it can be found here,

https://opendata.nfis.org/downloads/forest_change/CA_Forest_Fires_2023.zip

**Comment by samapriya** [comment]
This has been completed and the earth engine asset has been copied to make the path simple. Thank you for contributing as always
