### ISSUE TITLE
Global Shoreline Dataset

### ISSUE THREAD

**Issue by spatialthoughts** [samapriya/awesome-gee-community-datasets#265]
### Contact Details

ujaval@spatialthoughts.com

### Provide Dataset Link

https://gee-community-catalog.org/projects/shoreline/

### Describe the example

Creating a Land/Ocean mask
https://code.earthengine.google.co.in/a5cbf2f9d14a545efef050b80e5182d9

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
This has now been completed and I am including this in the beta release for now, will DM you a link
