### ISSUE TITLE
GLC_FCS30D Global 30-meter Land Cover Change Dataset (1985-2022)

### ISSUE THREAD

**Issue by spatialthoughts** [samapriya/awesome-gee-community-datasets#266]
### Provide Dataset Link

https://gee-community-catalog.org/projects/glc_fcs/

### Describe the example

This is a really valuable dataset and I would like to submit 3 code examples for this dataset for the community to work with it better. These are also posted on my blog at https://spatialthoughts.com/2024/06/29/global-landcover-glcfcs30d/

1. Pre-processing the data into a single ImageCollection with global landcover images. This could be the main example that everyone can use as their starting point. https://code.earthengine.google.co.in/1cef2a1741d0a008e19d264ffc8ea73d
2. A split-panel app to visualize and compare any 2 years from the time-series https://code.earthengine.google.co.in/5045485d86bca6127ce1503227dee11d
3. Calculate areas of each class for each year over multiple regions and export the results as a CSV https://code.earthengine.google.co.in/8a00121c510d6920764249b82a839894

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
This has now been completed and I am including this in the beta release for now, will DM you a link
