### ISSUE TITLE
Groundwater-dependent ecosystem map exposes global dryland protection needs

### ISSUE THREAD

**Issue by RSO9192** [samapriya/awesome-gee-community-datasets#272]
### Contact Details

melissa@rohdeenvironmental.com

### Dataset description

Global groundwater-dependent ecosystem map. Results were published in Nature in July 2024 (https://doi.org/10.1038/s41586-024-07702-8) and individual tiles can be downloaded from here (https://zenodo.org/records/11062894)

### Earth Engine Snippet if dataset already in GEE

No

### Enter license information

Creative Commons Attribution 4.0 

### Keywords

water resources, groundwater

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
This has been completed and will be made available in next release. Thank you for contributing
