### ISSUE TITLE
CMS: Global Mangrove Canopy Height Maps Derived from TanDEM-X, 2015

### ISSUE THREAD

**Issue by spatialthoughts** [samapriya/awesome-gee-community-datasets#273]
### Contact Details

ujaval@spatialthoughts.com

## Description 

This dataset characterizes canopy heights of mangrove-forested wetlands globally for 2015 at 12-m resolution. Estimates of maximum canopy height (height of the tallest tree) were derived from the German Space Agency's TanDEM-X data that produced global digital surface models. Also provided are Lidar estimates of canopy height based on the GEDI instrument, which were used for training and validation of the TanDEM-X estimates of forest height. The coverage of these data follows Global Mangrove Watch's mangrove extent maps. These spatially explicit maps of mangrove canopy height can be used to assess local-scale geophysical and environmental conditions that may regulate forest structure and carbon cycle dynamics. Maps revealed a wide range of canopy heights, including maximum values (>60 m) that surpass maximum heights of other forest types,

## Citation

Simard, M., L. Fatoyinbo, N. Thomas, A. Stovall, A. Parra, M.W. Denbina, D. Lagomasino, and I. Hajnsek. 2024. CMS: Global Mangrove Canopy Height Maps Derived from TanDEM-X, 2015. ORNL DAAC, Oak Ridge, Tennessee, USA. https://doi.org/10.3334/ORNLDAAC/2251

## Download Links
https://daac.ornl.gov/cgi-bin/dsviewer.pl?ds_id=2251

### Earth Engine Snippet if dataset already in GEE

n/a

### Enter license information

CC-0. This dataset is openly shared, without restriction, in accordance with the [EOSDIS Data Use Policy](https://earthdata.nasa.gov/earth-observation-data/data-use-policy). 

### Keywords

mangroves, nasa, cms, gedi, tandem-x

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
This has now been completed I will do a release update and changelog update soon. Thanks for contributing
