### ISSUE TITLE
Canadian Satellite-Based Forest Inventory (SBFI)

### ISSUE THREAD

**Issue by S-Bronson** [samapriya/awesome-gee-community-datasets#280]
### Contact Details

spencer.bronson@nrcan-rncan.gc.ca

### Provide Dataset Link

https://gee-community-catalog.org/projects/ca_sbfi/

### Describe the update

Dataset was updated following the identification of erroneous values relating to forest structure (Canopy Height, Canopy Cover, Loreys Height, Basal Area, Above Ground Biomass, and Volume) in a small number of polygons. 

### Relevant additional information

https://code.earthengine.google.com/?asset=users/mesospencer/SBFI_2020_v7

new dataset has been shared with all users having read access (sharing for both this folder, and the contents within it)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
This has been updated as requested. Thank you
