### ISSUE TITLE
[Dataset/Title]: Global Mangrove Watch version 4

### ISSUE THREAD

**Issue by rs9w33** [samapriya/awesome-gee-community-datasets#281]
### Contact Details

robyngwee@u.nus.edu

### Provide Dataset Link

https://zenodo.org/records/12756047

### Describe the update

Global Mangrove Watch has recently released the 2020 version 4 update, featuring higher resolution due to inclusion of Sentinel-2 data.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
This has been completed, find links in changelog. Thank you for contributing
