### ISSUE TITLE
[Dataset/Title]: Global NPP-VIIRS-like nighttime light (2000-2022)

### ISSUE THREAD

**Issue by SpatLyu** [samapriya/awesome-gee-community-datasets#285]
### Contact Details

lyu.geosocial@gmail.com

### Provide Dataset Link

awesome-gee-community-datasets: https://gee-community-catalog.org/projects/npp_viirs_ntl/
updated source data: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/YGIVCD

### Describe the update

The annual NPP-VIIRS-like NTL data of 2023 has been updated. The annual NPP-VIIRS-like NTL data of 2021 and 2022 have been updated. The annual NPP-VIIRS-like NTL data of 2019 and 2020 have been updated. See [here](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/YGIVCD)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SpatLyu** [comment]
@samapriya

**Comment by samapriya** [comment]
Sorry this took so long but 2023 has now been added and will be available in few hours. Thank you for your contribution and taking the time while being patient
