### ISSUE TITLE
[GCI30 Global Cropping Intensity at 30m resolution]: 

### ISSUE THREAD

**Issue by JinsuElhance** [samapriya/awesome-gee-community-datasets#286]
### Contact Details

jelhance@gmail.com

### Dataset description

<html>
<body>

This global cropping intensity product is the first 30m resolution cropping intensity dataset covering global extent. Based on the reconstructed time series of Normalized Difference Vegetation Index (NDVI) from multiple satellite images including Landsat-8, Sentinel-2 and MODIS, 30-m planetary-scale pixel by pixel cropping intensity products were generated by enumerating the total number of valid cropping cycles using a binary crop phenophase profile indicating growing and non-growing periods. The total number of valid cropping cycles were also divided by 3 (three years from 2016 to 2018) to retrieve the average cropping intensity. Based on the Google Earth Engine (GEE) cloud computing platform, we implemented our algorithm across the globe to the global cropping intensity products. (2020-10-10)

https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/86M4PO&version=2.0
--

</body>
</html>

### Earth Engine Snippet if dataset already in GEE

None

### Enter license information

CC0 1.0 Universal

### Keywords

Crop, Agriculture, Intensity, Degradation, Land-use

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by asdsaah** [comment]
@samapriya 
Data Download Link: **Yes**—It is available for download at [Harvard Dataverse](https://doi.org/10.7910/DVN/86M4PO); **No GEE**

Citation: **Yes** -  Not on the data page [Zhang, Miao; Wu, Bingfang; Zeng, Hongwei; He, Guojin; Liu, Chong; Nabil, Mohsen; Tian, Fuyou; Bofana, José; Wang, Zhengdong; Yan, Nana, 2020, "GCI30: Global Cropping Intensity at 30m resolution", https://doi.org/10.7910/DVN/86M4PO, Harvard Dataverse, V2].

License for Use: **Yes** - data is available under [CC0 1.0](http://creativecommons.org/publicdomain/zero/1.0).

**Comment by samapriya** [comment]
This has been completed and will be added to the next release, thank you for contributing
