### ISSUE TITLE
Dataset & Curator Name

### ISSUE THREAD

**Issue by hadijaafar** [samapriya/awesome-gee-community-datasets#29]
### Global Hydrologic Curve Number
The GCN250 is a globally consistent, gridded dataset defining CNs at the 250 m spatial resolution from new global land cover (300 m) and soils data (250 m). GCN250 represents runoff for a combination of the European space agency global land cover dataset for 2015 (ESA CCI-LC) resampled to 250 m and geo-registered with the hydrologic soil group global data product (HYSOGs250m) released in 2018. The potential application of this data includes hydrologic design, land management applications, flood risk assessment, and groundwater recharge modeling.

#### Citation
 Jaafar, H. H., Ahmad, F. A., & El Beyrouthy, N. (2019). GCN250, new global gridded curve numbers for hydrologic modeling and design. Scientific data, 6(1), 1-9. https://www.nature.com/articles/s41597-019-0155-x 
DOI: https://doi.org/10.1038/s41597-019-0155-x

#### Snapshot 
![image](https://user-images.githubusercontent.com/61577441/150480786-4aa5c681-a032-4b48-9a7e-de71c5fd4274.png)

#### Earth Engine Snippet
```js

var GCN250_Average =  ee.Image("users/jaafarhadi/GCN250/GCN250Average")
var GCN250_Dry =  ee.Image("users/jaafarhadi/GCN250/GCN250Dry")
var GCN250_Wet = ee.Image("users/jaafarhadi/GCN250/GCN250Wet")

```

Sample Code: https://code.earthengine.google.com/65fd6cfd746e4a1dc13b1c2b5ed86d40?noload=true

Extra Info: Dataset is also available as an Earth Engine App (Global Hydrologic Curve Number Explorer)
It allows users to visualize the gridded hydrologic curve number dataset at ~250m resolution globally. 
Link to the app: https://jaafarhadi.users.earthengine.app/view/hydrologic-curve-number#GEE

#### Required
License Information: Creative Commons Attribution 4.0 International License

Curated by: Hadi H. Jaafar, Farah A. Ahmad

Keywords: Curve Number, Runoff, Hydrology

Last updated: Last date you updated the dataset (20-06-2019)

**Comment by samapriya** [comment]
Thank you for contributing will work on getting this in the catalog over this weekend. This looks really great just downloaded the paper to read :)

**Comment by hadijaafar** [comment]
Thanks for the superb initiative!


All the best!
H
________________________________

**Comment by samapriya** [comment]
This dataset is now available in the GEE community catalog. you can find it here https://samapriya.github.io/awesome-gee-community-datasets/projects/gcn250/. Thank you for contributing to the catalog, I added the code link for the app and made minor edits at best. Look forward to more contributions :)
