### ISSUE TITLE
[ Global Natural and Planted Forests Mapping at Fine Spatial Resolution of 30 m]:

### ISSUE THREAD

**Issue by astridverhegghen** [samapriya/awesome-gee-community-datasets#292]
### Contact Details

astrid.verhegghen@gmail.com

### Dataset description

Xiao et al. (2024) recently published a paper 'Global Natural and Planted Forests Mapping at Fine Spatial Resolution of 30 m' with an associated datased available on a zenodo repository: https://zenodo.org/records/10701417

It is a global dataset at 30 meter, cut in 910 separated tiles. 

### Earth Engine Snippet if dataset already in GEE

for example
```js
var asset_name = ee.ImageCollection("path to your collection")
```
Sample Code: Add a sample code maybe just adding your datasets in the code editor

### Enter license information

CC-BY-4.0Creative Commons Attribution 4.0 International
The Creative Commons Attribution license allows re-distribution and re-use of a licensed work on the condition that the creator is appropriately credited. [Read more](https://creativecommons.org/licenses/by/4.0/legalcode)

### Keywords

planted forests

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samapriya** [comment]
This has now been completed and will be made available in this weeks release. Check the changelog for links and thank you for contributing
