### ISSUE TITLE
[Dataset Title/Name]: GloUTCI-M: A Global Monthly 1 km Universal Thermal Climate Index Dataset from 2000 to 2022

### ISSUE THREAD

**Issue by wangyuan074** [samapriya/awesome-gee-community-datasets#299]
### Contact Details

wangyuanleo123@outlook.com

### Dataset description

The GloUTCI-M comprises global monthly UTCI data at a spatial resolution of 1km, spanning from March 2000 to October 2022. The dataset is expressed in degrees Celsius (°C) and is stored as an integer type (Int16). To utilize it appropriately, one must divide the values by 100.

link: https://zenodo.org/records/8310513

Citation: Yang, Z., Peng, J., Liu, Y., Jiang, S., Cheng, X., Liu, X., ... & Yu, X. (2024). GloUTCI-M: a global monthly 1 km Universal Thermal Climate Index dataset from 2000 to 2022. Earth System Science Data, 16(5), 2407-2424. doi: https://doi.org/10.5194/essd-16-2407-2024

Dataset Citation: Zhiwei Yang, Jian Peng, & Yanxu Liu. (2023). GloUTCI-M: A Global Monthly 1 km Universal Thermal Climate Index Dataset from 2000 to 2022 [Data set]. Zenodo. https://doi.org/10.5281/zenodo.8310513

### Earth Engine Snippet if dataset already in GEE

for example
```js
var asset_name = ee.ImageCollection("path to your collection")
```
Sample Code: Add a sample code maybe just adding your datasets in the code editor

### Enter license information

CC-BY-4.0

### Keywords

Universal Thermal Climate Index; Heat Stress

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by asdsaah** [comment]
@samapriya 
Data Download Link: **Yes**—It is available for download at [Zenodo](https://zenodo.org/records/8310513); **Not Uploaded to GEE**, this is a monthly dataset for 22 years, so you have 264 individual GeoTiff. 
Citation: **Yes** -  [GloUTCI-M: a global monthly 1 km Universal Thermal Climate Index dataset from 2000 to 2022](https://doi.org/10.5194/essd-16-2407-2024).
License for Use: **Yes/No** - data/paper is available under CC BY 4.0.

**Comment by wangyuan074** [comment]
> @samapriya Data Download Link: **Yes**—It is available for download at [Zenodo](https://zenodo.org/records/8310513); **Not Uploaded to GEE**, this is a monthly dataset for 22 years, so you have 264 individual GeoTiff. Citation: **Yes** - [GloUTCI-M: a global monthly 1 km Universal Thermal Climate Index dataset from 2000 to 2022](https://doi.org/10.5194/essd-16-2407-2024). License for Use: **Yes/No** - data/paper is available under CC BY 4.0.

License for Use: Yes - data is available under Creative Commons Attribution 4.0 International License.

**Comment by samapriya** [comment]
This has now been completed and will be made available in the next release. You can check it out here
https://gee-community-catalog.org/projects/globutci/

Thank you for contributing

**Comment by matamadio** [comment]
The dataset doesn't seem to exist on GEE anymore:

`ImageCollection.load: ImageCollection asset 'projects/sat-io/open-datasets/gloutci-m' not found (does not exist or caller does not have access).`

Could you please check?
