### ISSUE TITLE
Predicted Peat extent across Amazon basin 

### ISSUE THREAD

**Issue by ahastie8** [samapriya/awesome-gee-community-datasets#300]
### Contact Details

adamhastie50@googlemail.com

### Dataset description

Predicted extent of Peat (organic soil of ≥ 30 cm thickness) across the study area (Amazon basin below 500 m and mean annual precipitation >1,390 mm) at 90 m resolution.

Link to GEE code: https://code.earthengine.google.com/7f3dd62e0c04f67ba66e3fdefeb2174a

Link to GEE app: https://adamhastie50.users.earthengine.app/view/predicted-peat-extent-across-amazon-basin

DOI: 10.1088/1748-9326/ad677b

Citation: Hastie, A., Householder, J. E., Coronado, E. N. H., Pizango, C. G. H., Herrera, R., Lähteenoja, O., de Jong, J., Winton, R. S., Corredor, G. A. A., Reyna, J., Montoya, E., Paukku, S., Mitchard, E. T. A., Åkesson, C. M., Baker, T. R., Cole, L. E. S., Oroche, C. J. C., Dávila, N., Águila, J. D., … Lawson, I. T. (2024). A new data-driven map predicts substantial undocumented peatland areas in Amazonia. Environmental Research Letters, 19(9), 094019. https://doi.org/10.1088/1748-9326/ad677b

### Earth Engine Snippet if dataset already in GEE

var Amazon_peat_map = ee.Image("users/adamhastie50/INT_Amazon_peat_map"),
    Simple_AOI = ee.FeatureCollection("users/adamhastie50/Study_area_simplify");

//Predicted extent of peat (organic soil of ≥ 30 cm thickness) 
//across the study area (Amazon basin below 500 m and mean annual precipitation >1,390 mm)
//at 90 m resolution. From Hastie et al., 2024- https://iopscience.iop.org/article/10.1088/1748-9326/ad677b

// Create a legend
// set position of panel

var legend = ui.Panel({
  style: {
    position: 'bottom-left',
    padding: '8px 15px'
  }});
 
// Create legend title
var legendTitle = ui.Label({
  value: 'Legend',
  style: {
    fontWeight: 'bold',
    fontSize: '18px',
    margin: '0 0 4px 4px',
    padding: '0'}});
 
// Add the title to the panel
legend.add(legendTitle);
 
// Creates and styles 1 row of the legend.
var makeRow = function(color, name) {
  //Create the label that is actually the colored box.
      var colorBox = ui.Label({
        style: {
          backgroundColor: '#' + color,
          // Use padding to give the box height and width.
          padding: '8px',
          margin: '0 0 4px 4px'
        }});
 
      // Create the label filled with the description text.
      var description = ui.Label({
        value: name,
        style: {margin: '0 0 4px 4px'}
      });
 
      // return the panel
      return ui.Panel({
        widgets: [colorBox, description],
        layout: ui.Panel.Layout.Flow('horizontal')
      });
      };
 
//  Palette with the colors
var palette =['FFA500'];
 
// name of the legend
var names = ['Peat (Hastie et al., 2024)'];
 
// Add color and and names
for (var i = 0; i < 1; i++) {
  legend.add(makeRow(palette[i], names[i]));
  }  
 
 //add legend to map (alternatively you can also print the legend to the console)
Map.add(legend);
Map.centerObject(Amazon_peat_map, 6); 

Map.addLayer(Amazon_peat_map, {min: 1, max: 1, palette: ['orange']}, 'Peat_map');  

### Enter license information

Enter License information ex: APACHE 2.0, CC-BY-4.0

### Keywords

Peat, Tropical Peat, Amazon basin.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by asdsaah** [comment]
@samapriya 
Data Download Link: **in GEE with an App; working 10/16/24.**/
Citation: **Yes** -  [See Above](https://doi.org/10.1088/1748-9326/ad677b).
License for Use: **~Maybe** - CC BY 4.0. - @ahastie8, would to mind confirming the data is available under this license type?

**Comment by ahastie8** [comment]
Sorry meant to say, yes- Creative Commons Attribution 4.0 International.

The dataset is also available on Zenodo- https://zenodo.org/records/13142590

**Comment by samapriya** [comment]
This has now been completed and will be available this week, you can find the [page here](https://gee-community-catalog.org/projects/amazon_peat). Thank you for contributing

**Comment by ahastie8** [comment]
Many thanks Samapriya,

Best regards,

Adam
