### ISSUE TITLE
POLARIS data: confusion about help page

### ISSUE THREAD

**Issue by MatthieuStigler** [samapriya/awesome-gee-community-datasets#31]
Thanks a lot for all the great work, your project is indeed... awesome!

I am confused about the help page for Polaris (https://samapriya.github.io/awesome-gee-community-datasets/projects/polaris/). It says:

> The dataset is available at varying depth from surface, while the statistics provided include mean, mode , median and percentile values, only **median** values have been included as part of the collection created.

But then the collections are all called `*_mean`, as for example _'projects/sat-io/open-datasets/polaris/bd_mean'_ ? So is it possible it is rather the mean than the median that is included?

Also, is there any chance that a next iteration of the dataset in EE adds a new property `soil_depth`, that basically contains just the `0_5` info instead of say `clay_0_5` (or min/max depth)? It would make it easier to filter later on. Thanks so much!

**Comment by samapriya** [comment]
Hi @MatthieuStigler 
Thank you for reaching out indeed the data was available with p5,p,50,p95, mode and mean as you can see in the example here http://hydrology.cee.duke.edu/POLARIS/PROPERTIES/v1.0/alpha/. However, I had only ingested the mean for my collection and I should have said only mean values have been included as part of the collection and I will make that change.

The collection does have each image named with the depth but I can add that extra metadata property and update this ticket when done.

**Comment by MatthieuStigler** [comment]
Thanks, that would be great indeed!

Just for discoverability, if that can be useful for others, this is how I am currently filtering for depth and then aggregating. If `min_depth` and `max_depth` were available as integers, that would make it even easier :-)

Thanks a lot Samapriya! 

```
var add_prop = function(image) {
  var actual = ee.String(image.get("system:index")).replace("[a-z]+_([a-z]+_)?", "")
  return image.set({'height': actual});
};

//// select horizon, average
var prep_image = function(image, name) {

  // add property, filter
  var image2 = image.map(add_prop).filter(ee.Filter.inList("height", ["0_5", "5_15", "15_30", "30_60"]))
  // average, rename
  return image2.reduce({reducer: ee.Reducer.mean()}).rename(name)
}

```

**Comment by samapriya** [comment]
Thanks, @MatthieuStigler 
All collections now have min_depth and max_depth as properties. Thanks for the input and for sharing the intermediate code you were using. Let me know if there are any further issues or recommendations

**Comment by MatthieuStigler** [comment]
awesome, thanks for all the great work!
