### ISSUE TITLE
ASTER Global DEM (GDEM)

### ISSUE THREAD

**Issue by giswqs** [samapriya/awesome-gee-community-datasets#32]
### Dataset Name
ASTER Global DEM (GDEM),  30-m resolution

![](https://i.imgur.com/nR6O0Si.png)

#### Data Description

- https://asterweb.jpl.nasa.gov/gdem.asp
- https://earthdata.nasa.gov/learn/articles/new-aster-gdem

#### Download

- https://e4ftl01.cr.usgs.gov/ASTT/ (ASTGTM.003)

#### Required
License Information: All LP DAAC current data and products acquired through the LP DAAC have no restrictions on reuse, sale, or redistribution. ([source](https://lpdaac.usgs.gov/data/data-citation-and-policies/))

Keywords: ASTER, DEM, elevation

**Comment by samapriya** [comment]
Hi @giswqs 
Thanks for the tag on this one. This is now complete

https://samapriya.github.io/awesome-gee-community-datasets/projects/aster/


Looking forward to the next one :)

**Comment by giswqs** [comment]
Wow, this is amazing! Thanks a lot for your hard work.
