### ISSUE TITLE
US National Hydrography Dataset

### ISSUE THREAD

**Issue by giswqs** [samapriya/awesome-gee-community-datasets#35]
The NHD dataset would be a great addition to the Awesome GEE Datasets. The national dataset in GeoDatabase format is 26.5 GB. I am not sure if it is feasible to ingest it as a single file. If not, it can be download by state, HU8, or HU4. I can help generate all direct download links if needed. 

### US National Hydrography Dataset
https://www.usgs.gov/national-hydrography/access-national-hydrography-products

**National Map Downloader:**
https://apps.nationalmap.gov/downloader/
![image](https://user-images.githubusercontent.com/5016453/163918315-24dd9306-7931-40fb-869d-aea98e4412c0.png)

**Direct download links:**
National: https://prd-tnm.s3.amazonaws.com/StagedProducts/Hydrography/NHD/National/HighResolution/GDB/NHD_H_National_GDB.zip

By State (e.g., Arizona): https://prd-tnm.s3.amazonaws.com/StagedProducts/Hydrography/NHD/State/Shape/NHD_H_Arizona_State_Shape.zip

By HU4 (e.g., 1008): https://prd-tnm.s3.amazonaws.com/StagedProducts/Hydrography/NHD/HU4/Shape/NHD_H_1008_HU4_Shape.zip

By HU8 (e.g., 01090005): https://prd-tnm.s3.amazonaws.com/StagedProducts/Hydrography/NHD/HU8/HighResolution/Shape/NHD_H_01090005_HU8_Shape.zip

**Comment by samapriya** [comment]
Thanks @giswqs 
I am just getting back time this week. Let me set up sometime to catch up and discuss this one too . Thanks for the dataset request

**Comment by giswqs** [comment]
No rush. Take you time.

**Comment by samapriya** [comment]
Hi @giswqs 
I used your state wide extract just to test run what a state wide feature collection would look like on GEE , could you test out ingested datasets in this folder (projects/sat-io/open-datasets/nhd_az). I think you are right a complete National extract might have lag and ingest issues

here are the feature collections included
projects/sat-io/open-datasets/nhd_az/NHDArea
projects/sat-io/open-datasets/nhd_az/NHDFlowline_0
projects/sat-io/open-datasets/nhd_az/NHDFlowline_1
projects/sat-io/open-datasets/nhd_az/NHDLine
projects/sat-io/open-datasets/nhd_az/NHDPoint
projects/sat-io/open-datasets/nhd_az/NHDPointEventFC
projects/sat-io/open-datasets/nhd_az/NHDWaterbody
projects/sat-io/open-datasets/nhd_az/WBDHU10
projects/sat-io/open-datasets/nhd_az/WBDHU12
projects/sat-io/open-datasets/nhd_az/WBDHU2
projects/sat-io/open-datasets/nhd_az/WBDHU4
projects/sat-io/open-datasets/nhd_az/WBDHU6
projects/sat-io/open-datasets/nhd_az/WBDHU8
projects/sat-io/open-datasets/nhd_az/WBDLine

**Comment by giswqs** [comment]
I can confirm that datasets work well. Thanks a lot for taking on this huge database!

https://code.earthengine.google.com/1a54a401333b989481d332ca4cb17295

**Comment by samapriya** [comment]
Thanks for confirming @giswqs 
Would it be possible for you to generate state links for all states now that we know it works I would like to test if it would break for states for Texas or California . Thanks for the lift, also would be great if you have a description metadata for each vector file to be added to the overall description though we can work on that later

**Comment by giswqs** [comment]
Sure. I will generate the links shortly. We can work on the description later.

**Comment by giswqs** [comment]
Here it is:
https://docs.google.com/spreadsheets/d/1G7k2x6WBcG9kOwYydLgI8x3PHGGZ90iGDXKflYvDrtI/edit?usp=sharing

**Comment by samapriya** [comment]
Hi @giswqs 
I am finally making good progress on some states, wondering if we could get started on description for different filenames? apart from things like citation and license . Trying to understand what NHDFlowline_0, and NHDFlowline_1 and so on mean. Are they simply the flowline part split up in multiple parts? Look forward to your thoughts when you have time

**Comment by giswqs** [comment]
@samapriya I think you are right, NHDFlowline_0 and NHDFlowline_1 are probably just the NHDFlowline being split to multiple parts. Some states have NHDFlowline only, while some states have NHDFlowline_0, NHDFlowline_1, etc. I cannot find anything on the NHD website regarding this. I think you can refer them to just NHDFlowline.

**Comment by giswqs** [comment]
See below the information about the NHD datasets. I extracted some of the information from the book - [GIS for Surface Water: Using the National Hydrography Dataset
](https://www.esri.com/en-us/esri-press/browse/gis-for-surface-water-using-the-national-hydrography-dataset)

**Description**: The National Hydrography Dataset (NHD) represents the water drainage network of the United States with features such as rivers, streams, canals, lakes, ponds, coastline, dams, and streamgages. The National Hydrography Dataset (NHD) is mapped at 1:24,000 or larger scale (1:63,360 or larger scale in Alaska). These data are updated and maintained through [Stewardship](https://www.usgs.gov/national-hydrography/stewardship-and-community) partnerships with states and other collaborative bodies ([source](https://www.usgs.gov/national-hydrography/national-hydrography-dataset))

**Dataset link**: https://www.usgs.gov/national-hydrography

**License**: This dataset is intended for public access and use. No license information was provided ([source](https://catalog.data.gov/dataset/national-hydrography-dataset-nhd)).

**Citation**: see https://www.usgs.gov/faqs/how-should-i-cite-datasets-and-services-national-map

**Datasets**:
- **NHDFlowline**: consists of StreamRiver, CanalDitch, Pipeline, Underground Conduit, Artificial Path, Connector, and Coastline.
- **NHDWaterbody**: consists of LakePond, SwampMarsh, Reservoir, Playa, Ice Mass, and Estuary.
- **NHDArea**: includes Area of Complex Channel, Area To Be Submerged, BayInlet, Bridge, CanalDitch, DamWeir, Flume, Foreshore, Inundation Area, Levee, Lock Chamber, Rapids, SeaOcean, Spillway, StreamRiver, Submerged Stream, Wash, Water Intake/Outflow. Having CanalDitch and StreamRiver in this class seems inconsistent, but there is a good reason for this because we need both polygon and line forms of geography.
- **NHDLine**: includes Area of Complex Channel, Area To Be Submerged, BayInlet, Bridge, CanalDitch, DamWeir, Flume, Foreshore, Inundation Area, Levee, Lock Chamber, Rapids, SeaOcean, Spillway, StreamRiver, Submerged Stream, Wash, Water Intake/Outflow. Having CanalDitch and StreamRiver in this class seems inconsistent, but there is a good reason for this because we need both polygon and line forms of geography.
- **NHDPoint**: includes DamWeir, Gaging Station, Gate, Lock Chamber, Rapids, Reservoir, Rock, SinkRise, SpringSeep, Waterfall, Water Intake/Outflow, and Well.
- **NHDPointEventFC**: point events located on NHDFlowlines.
- **NHDLineEventFC**: line events located on NHDFlowlines.
- **NHDAreaEventFC**: area events located on NHDWaterbody.
- **WBDHU10**: polygon for HU10
- **WBDHU12**: polygon for HU12
- **WBDHU14**: polygon for HU14
- **WBDHU16**: polygon for HU16
- **WBDHU2**: polygon for HU2
- **WBDHU4**: polygon for HU4
- **WBDHU6**: polygon for HU6
- **WBDHU8**: polygon for HU8
- **WBDLine**: individual lines used in WBD polygons

**Comment by samapriya** [comment]
Hey @giswqs 
This request has been completed, I merged all flowlines to create consistent feature layer, you can find it here
https://samapriya.github.io/awesome-gee-community-datasets/projects/nhd/

also tagged you on linkedin. Feel free to reopen issue if needed

**Comment by giswqs** [comment]
@samapriya Awesome work! Thanks a lot for ingesting this huge dataset.

**Comment by samapriya** [comment]
It was a pleasure working together on this one
