### ISSUE TITLE
National Hydrography Dataset (NHD) Properties Update

### ISSUE THREAD

**Issue by SimonTopp** [samapriya/awesome-gee-community-datasets#36]
### Dataset Name and Catalog Page
NHD Hydrography Dataset
https://samapriya.github.io/awesome-gee-community-datasets/projects/nhd/

### Dataset update , version and release date
Same as existing but with Permanent Identifiers for feature tracking and cross-walks to other datasets.

### Reason for update
First off, thanks so much for curating these amazing resources! The community datasets are incredible and it's been fun to watch them grow over time.  I was super excited to see that the National Hydrography Dataset had been added.  I wanted to request that next time it's updated, the Permanent Identifier is added back into the properties of the NHD Waterbodies.  This identifier allows for cross-walks to other datasets and match-ups to existing research that only provide tabular data.  Basically, without the Permanent Identifier it's challenging to export and track summary statistics and whatnot about individual lakes.  This is implied by the description of the Permanent Identifier from the [user guide](https://nhd.usgs.gov/userGuide/Robohelpfiles/NHD_User_Guide/Feature_Catalog/Hydrography_Dataset/NHDWaterbody/NHDWaterbody.htm#:~:text=Permanent%20Identifier,and%20two%2Dway%20geodatabase%20replication.)

> Permanent Identifier | Global ID and GUID data types store registry style strings consisting of 36 characters enclosed in curly brackets. These strings uniquely identify a feature or table row within a geodatabase and across geodatabases. This is how features are tracked in one-way and two-way geodatabase replication.

Unfortunately the identifiers like GNIS ID that are included in the EE dataset are Null for any lake without a name, making it less useful than the Permanent Identifier.  Thanks again for curating and maintaining these resources, really incredible work!

**Comment by samapriya** [comment]
Hi @SimonTopp 
All of the NHD datasets in GEE were uploaded from the shapefiles and not the geodatabases for each state. No properties were modified but this also means that properties that were different between the GDB and the shapefiles could not be ported over. I am open to suggestions but wanted to state the limitations and the methodology used.

**Comment by SimonTopp** [comment]
Thanks for the prompt response @samapriya! Where are you pulling the data from?  When I download the state shapefiles from the USGS [S3 bucket](https://prd-tnm.s3.amazonaws.com/index.html?prefix=StagedProducts/Hydrography/NHD/State/Shape/) and open the NHDWaterbodies shapefile (not GDB) I get 15 properties, the first of which is the permanent identifier.

<img width="747" alt="image" src="https://user-images.githubusercontent.com/33098707/166455816-976e9b9a-890d-4d23-877d-62164eea0d18.png">

**Comment by giswqs** [comment]
Download link here: https://github.com/samapriya/awesome-gee-community-datasets/issues/35#issuecomment-1112214243

**Comment by giswqs** [comment]
Interesting! It seems the `permanent_` attribute indeed gets lost during the ingestion process. The attribute exists in the shapefile. Could the trailing underscore in the attribute name cause the issue?

From GEE Code Editor
![image](https://user-images.githubusercontent.com/5016453/166457647-2bdfd7ea-56a3-41db-b660-734b9337b708.png)

From QGIS
![image](https://user-images.githubusercontent.com/5016453/166457680-f99d4b99-3eca-4d93-9794-9e566cf8e357.png)

**Comment by samapriya** [comment]
I wonder if GEE won't accept special characters or properties that have a { for example there are limits on mixed property type or properties with specific characters maybe

**Comment by giswqs** [comment]
Not all properties have `{`. Some are integer numbers. 

![image](https://user-images.githubusercontent.com/5016453/166458202-299efaf6-5280-4d7d-802b-9f35f7098d45.png)

**Comment by SimonTopp** [comment]
Hmm, very weird!  According to the docs it should just upload it as a string if it's a mixed property type.  I've had similar experiences exporting assets, where it'll skip certain properties, but I've never encountered this while ingesting new assets.  At first glance I don't see anyway to explicitly pass which properties to upload though.  I wonder if you remove the tailing `_` if that would do it like you suggest @giswqs.

> Note: Mixed datatype columns (e.g. numbers and strings) will default to string upon ingestion. This is an important consideration when preparing a table in a spreadsheet application, where it is common to denote missing data as NA, Null, None, --, etc. In the case of missing data, leave the "cell" empty.

**Comment by giswqs** [comment]
I can confirm that the underscore in the attribute name causes the issue. Any attributes with an underscore in the name will be ignored in the `set()` properties function. Removing the underscore solves the issue. 

https://code.earthengine.google.com/f7f748c16c737ab13b848c09be0415cc
![image](https://user-images.githubusercontent.com/5016453/166459011-d2e8487c-7d87-45e0-bc12-65a7217d5a17.png)

**Comment by samapriya** [comment]
Well for me to be able to run this for the waterbodies somebody would have to provide me waterbody shapefiles for all states with Permanent_ changed to Permanent if possible and I am happy to reingest if that works

**Comment by giswqs** [comment]
NHD does not provide individual downloads for just NHDWaterbody. We will have to download the entire NHD datasets by state. 
Do you still have the state shapefiles? I can probably write a script for you to run that if you still have the files.

**Comment by samapriya** [comment]
I do believe I have the shapefiles and haven't deleted them yet :) I also wonder if there is a waterbody1 waterbody 2 issue similar to how flowlines were split but yes happy to run a script to correct and rewrite headers and reingest.

**Comment by SimonTopp** [comment]
Not off the top of my head, but I'll poke around a little bit.  I'm guessing that what happened was permanent_identifier got truncated because it was too long and it's just a coincidence that it got truncated at the "_"

**Comment by samapriya** [comment]
wonder if we should replace it with pid instead thought that might break from nomenclature am not sure of the field length limit @giswqs  I am going to try to run your script to replace permanent_ with permanent_identifier and check if GEE will accept it

**Comment by giswqs** [comment]
I think the new name will be just `permanent` rather than `permanent_identifier`. No underscore.

**Comment by samapriya** [comment]
got it that makes sense I realized that permanent_identifier has the same issue existing underscore :)

**Comment by SimonTopp** [comment]
Also, as an aside, very much appreciate both of you jumping on this! I think maintaining that permanent ID significantly increases the utility of the dataset for the community.

**Comment by samapriya** [comment]
Unfortunately yes it is a big lift not the knocking them out part but reingesting and streamlining everything part, it can be done just will be slow. Also @giswqs I already wrote the script to do the renaming atleast but thank you for offering

**Comment by giswqs** [comment]
@samapriya You are so quick. I am also done with the script. Great to know you already got it before me. 

https://github.com/giswqs/data/blob/main/nhd/nhd_rename.ipynb

**Comment by samapriya** [comment]
Can either or both of you review this one, just ran it for one state as test, haven't merged flowlines or anything fancy yet :) 
https://code.earthengine.google.com/e2d4fe6dfe602a243ebc1d05f33d93cd

**Comment by SimonTopp** [comment]
Everything looks good to me except that for `NHDFlowlines_0` I get `Layer error: Collection.loadTable: Collection asset 'projects/sat-io/open-datasets/nhd_wy/NHDFlowline_0'  not found`.  And that's just looping over the assets returned from the list assets call.
https://code.earthengine.google.com/6cac9a657b9c0ada7e59bd1a86a24cbd

**Comment by samapriya** [comment]
That was just a permissions issues at my end the Flowline_0 file had not been ingested when I granted permission hence I created the script with Flowline_2, it should work now . Glad rest looks good, fingers crossed for a steady update

**Comment by samapriya** [comment]
All datasets have been reprocessed and updated, I have also merged the flowlines and waterbodies as the earlier dataset. Thank you @giswqs and @SimonTopp for starting the issue and working together. I loved our collaboration in helping solve this :)  Feel free to reopen the issue if there are further problems

**Comment by giswqs** [comment]
@samapriya Excellent work! Thank you very much.

**Comment by SimonTopp** [comment]
Thanks @samapriya!
