### ISSUE TITLE
[Data Set - GEBCO: Bug Report]

### ISSUE THREAD

**Issue by Yingjie4Science** [samapriya/awesome-gee-community-datasets#37]
**Describe the bug**

Hi, there is a small error in your example code at https://samapriya.github.io/awesome-gee-community-datasets/projects/gebco/#gebco-type-identifier-tid-grid-coding

The first two layers' names are upside down, see the attached screenshot. 

**Screenshots**
![image](https://user-images.githubusercontent.com/40079217/167426891-131fc23d-582e-4719-9e26-b6609a914a05.png)

**Comment by samapriya** [comment]
Thank you for reporting this, this has now been fixed with a new script link and the site and dataset links have been updated

**Comment by samapriya** [comment]
This is not really a related question :) but the median or mosaic functions can remove CRS for the output image it is important to set CRS and scale so for example you can set the CRS and scale post median to get the same nominal resolution of pixel for the median image. Hope that helps

https://code.earthengine.google.com/42ceac5bb1e2d63ffeae97584e03be0b
