### ISSUE TITLE
Global Power Plant Dataset

### ISSUE THREAD

**Issue by edtrochim** [samapriya/awesome-gee-community-datasets#38]
### Dataset Name and Catalog Page
 Global Power Plant Database https://samapriya.github.io/awesome-gee-community-datasets/projects/pwplants/

### Dataset update , version and release date
Last version of this database is version 1.3.0 released early 2022.

### Updated dataset link
https://github.com/wri/global-power-plant-database/blob/master/output_database/global_power_plant_database.csv

### Reason for update
Update AUS, IND, USA, GBR

### Updated License
N/A

**Comment by samapriya** [comment]
Hey @edtrochim 
The dataset is already v1.3.0 released 2021-06-02 has something changed?
https://datasets.wri.org/dataset/globalpowerplantdatabase

**Comment by samapriya** [comment]
I wonder if this would be called a bleeding-edge version? from their webpage it mentions

```
The bleeding-edge version of the database (which may contain substantial differences 
from the release you are viewing) is available on GitHub as well.
```

**Comment by samapriya** [comment]
Just checked the Bleeding edge and the version I pushed is the same at 34936 features including the same metadata :)  however you can access the bleeding edge dataset below. Closing this issue but feel free to reopen or if I missed anything

```
ee.FeatureCollection("projects/sat-io/open-datasets/global_power_plant_DB_1-3");
```
