### ISSUE TITLE
Rangeland Analysis Platform, Brady Allred

### ISSUE THREAD

**Issue by moonlightbotanist** [samapriya/awesome-gee-community-datasets#4]
### Dataset Name
Rangeland Analysis Platform data products are available as GEE assets and are made publicly available for analysis through the web application at [rangelands.app](https://rangelands.app)

**Vegetation Cover:** Rangeland Analysis Platform (RAP) Vegetation Cover, version 2.0 consists of gridded fractional estimates of plant functional groups for rangelands in the western United States. The estimates are produced at 30-meter spatial resolution for each year between 1984–present. The five plant functional groups are Annual Forbs and Grasses, Perennial Forbs and Grasses, Shrubs, Trees, and Bare Ground. Cover values are reported as percentages on a pixel-by-pixel basis. The estimates were produced using a temporal convolutional network using field measures of plant functional groups collected by the Natural Resources Conservation Service Natural Resources Inventory (NRI) program and the Bureau of Land Management Assessment, Inventory, and Monitoring (AIM) program alongside spatially continuous earth observations from Landsat TM, ETM, and OLI.

**Herbaceous Biomass:** Rangeland Analysis Platform (RAP) Herbaceous Biomass, version 1.0 consists of gridded estimates of herbaceous aboveground biomass, partitioned by annual forbs and grasses and perennial forbs and grasses. The estimates are produced at 30m spatial resolution from 1986-present. Estimates are provided annually and at 16-day intervals. Values are reported in pounds per acre and represent new growth of biomass – estimates do not reflect standing biomass from previous years. Estimates are calculated using a light use efficiency model (to estimate net primary production in terms of carbon) which is then allocated to above ground and below ground pools (based on mean annual temperature) and further converted to biomass using a carbon-to-dry matter ratio.

![Capture](https://user-images.githubusercontent.com/33233973/115937318-eddfb000-a454-11eb-8646-7d220ea19c6b.JPG)

#### Earth Engine Asset Snippets
```js
// Vegetation Cover
var RAP_veg = ee.ImageCollection("projects/rangeland-analysis-platform/vegetation-cover-v2")

// Net Primary Production (annual)
var RAP_npp = ee.ImageCollection("projects/rangeland-analysis-platform/npp-partitioned-v2")

// Net Primary Production (16-day)
var RAP_npp_16d = ee.ImageCollection("projects/rangeland-analysis-platform/npp-partitioned-16day-v2")
```

Sample scripts are available on the [RAP Support Site](https://support.rangelands.app/article/61-processing-rap-data-in-google-earth-engine). 

Extra Info: See any of the three herbaceous biomass scripts for the function to convert from net primary production to biomass. 

Download Tool/Code snippets if any: Analysis can be performed on these datasets for your regions of interest through the GUI at [rangelands.app](https://rangelands.app)

#### Required
License Information: Creative Commons Attribution-NonCommercial 4.0

Curated by: Brady Allred and Matthew Jones, University of Montana, Data producers; Eric Jensen, University of Montana, Point of Contact

Keywords: rangelands, vegetation, time-series, machine learning, landsat

Last updated: 3/31/2021

**Comment by samapriya** [comment]
Hey @moonlightbotanist 
This is great. Could you please confirm that all three collections you shared are under the
 ```
Creative Commons Attribution-NonCommercial 4.0 International License ?
``` 

License information helps users navigate the data better.

**Comment by moonlightbotanist** [comment]
Yes, thank you for clarifying. I've just reviewed our other documentation and confirmed that our products are, in fact, under Creative Commons Attribution-NonCommercial 4.0 and updated the initial issue

**Comment by samapriya** [comment]
RAP has now been added to the community datasets you can find it here, thank you for contributing :) 

https://samapriya.github.io/awesome-gee-community-datasets/projects/rap/

**Comment by moonlightbotanist** [comment]
Thanks very much Samapriya—and thanks for this excellent resource! Also, thanks for tracking down the citations, I must have missed that part. Key point: thanks all around!


Have a great weekend,
Eric
