### ISSUE TITLE
Global Building Footprints

### ISSUE THREAD

**Issue by giswqs** [samapriya/awesome-gee-community-datasets#40]
Microsoft just released the free global building footprints. Huge datasets. I am not sure if it is worth considering. 
https://github.com/microsoft/GlobalMLBuildingFootprints

**Comment by samapriya** [comment]
I agree these might be massive the Brazil GeoJSON alone expands to 20 GB and is a GeoJSONl file which would probably be even larger as a shapefile . I started with Brazil to see complexities with larger datasets. The other idea would be to grid the vector but am not so sure. I am open to ideas

**Comment by samapriya** [comment]
Unfortunately, I agree thank you for the suggestion though, and for the download links. Closing the ticket for now
