### ISSUE TITLE
DEM France (Continental) 5m IGN RGE Alti - Guillaume Attard

### ISSUE THREAD

**Issue by guiattard** [samapriya/awesome-gee-community-datasets#41]
### RGE ALTI® 5m France (Continental)
The DTM RGE ALTI® is a digital terrain model distributed at 1 m and 5 m resolutoin. It describes the elevation of the ground surface. It is designed for use at scales between 1:3,000 and 1:20,000.

Citation : IGN - RGE ALTI®Version 2.0

Open licence:
![image](https://user-images.githubusercontent.com/49778819/170245728-3b9dad48-4463-4a30-8a6e-99e5b9abae90.png)

#### Earth Engine Snippet
See public repo: https://code.earthengine.google.com/?accept_repo=users/guiattard_gei/france_dem

#### Required
License Information: Open licence

Curated by: Guillaume Attard

Keywords: DEM, France

Last updated: 2021

**Comment by samapriya** [comment]
Hi @guiattard 
I need two specific pieces of information that I could not find on the website
* Are there any restrictions on the redistribution of the data?
* Also what kind of open data license is it because there are so many in the world and some are limited while others are not in who can use them (for example here is a list https://spdx.org/licenses/)

Let me know if you have the answer I already have the single asset created for you

**Comment by guiattard** [comment]
Dear Sam,

There is no restrictions on the redistribution of the data. Please find a press release [here](https://www.ign.fr/sites/default/files/2020-12/cp_gratuite_donnees_2020.pdf) from the The National Institute of Geographic and Forest Information (IGN) (France). 

This press release indicates that the RGE Alti dataset is under the open licence [Etalab 2.0](https://www.etalab.gouv.fr/wp-content/uploads/2018/11/open-licence.pdf).

Please let me know if you need further details or help regarding the dataset description (altimetric accuracy, etc.). The full description is available [here](https://geoservices.ign.fr/sites/default/files/2021-07/DC_RGEALTI_2-0.pdf) in french but I can help to translate crucial points.

Regards

**Comment by samapriya** [comment]
Thank you that makes perfect sense I will work on this to get it out either tomorrow or Monday

**Comment by samapriya** [comment]
This is now complete, you can find the page here
https://samapriya.github.io/awesome-gee-community-datasets/projects/france5m/

**Comment by guiattard** [comment]
Very nice! Thanks a lot
