### ISSUE TITLE
[Data Set: Bug Report] Plastic Inputs collection not found

### ISSUE THREAD

**Issue by aazuspan** [samapriya/awesome-gee-community-datasets#42]
**Describe the bug**
Hi @samapriya! I was exploring the community datasets and noticed the [Plastic Inputs](https://samapriya.github.io/awesome-gee-community-datasets/projects/plastic/) layer seems to be missing or possibly not shared. Attempting to load the `FeatureCollection` throws `Collection asset 'projects/sat-io/open-datasets/open-ocean/river_plastic_emissions' not found`.

**Sample Earth Engine Code**
https://code.earthengine.google.com/4b989e2c30899d75f444c38983ac36c9

**Screenshots**
![Earth Engine error](https://user-images.githubusercontent.com/50475791/170590552-09daf44b-d8f4-46f5-8571-bbcddf3911d0.png)

**Additional context**
No rush, just wanted to make you aware of the issue!

**Comment by samapriya** [comment]
Thanks for pointing it out, just fixed permissions and it should work now

**Comment by aazuspan** [comment]
Thanks for the quick fix!
