### ISSUE TITLE
Country missing & minor issues in geoBoundaries dataset

### ISSUE THREAD

**Issue by MeldaS** [samapriya/awesome-gee-community-datasets#43]
**Describe the bug**
Minor - Philippines ISO is showing up under shapeName
Minor - "None" is showing up as the shapeName for CHE, it should be Switzerland
Missing country - State of Palestine / PSE is missing from the CGAZ and SSCGS datasets (I didn't check the rest), but it exists under https://www.geoboundaries.org/. See screenshot below

**Sample Earth Engine Code**
[GEE code showing errors](https://code.earthengine.google.com/47e27a8d1b86b2c635a2d06013139cd5)

**Screenshots**
<img width="509" alt="Screen Shot 2022-06-19 at 10 32 22 PM" src="https://user-images.githubusercontent.com/33935846/174495409-a60764b0-31f4-4c2b-bbd4-404c0b01122a.png">

<img width="815" alt="Screen Shot 2022-06-19 at 10 33 04 PM" src="https://user-images.githubusercontent.com/33935846/174495434-3fad3790-ac33-48c1-9874-77aa098c1881.png">

**Additional context**
Thank you so much for building the awesome-gee-community-datasets repo. It really is awesome and super useful

**Comment by samapriya** [comment]
Wondering if we should wait to [update to v5](https://www.geoboundaries.org/api.html#tabs1-html), seems I hadn't pushed 4.0.0 on this either

**Comment by samapriya** [comment]
These have now been completely updated in the main catalog
https://developers.google.com/earth-engine/datasets/catalog/WM_geoLab_geoBoundaries_600_ADM0

I know this took forever but glad it's all there now
