### ISSUE TITLE
[Data Set: Bug Report]

### ISSUE THREAD

**Issue by schwehr** [samapriya/awesome-gee-community-datasets#44]
**Describe the bug**

The license seems incorrect for open-datasets_GLO-30.json

Where is there a CC-PDDL statement?

I see https://docs.sentinel-hub.com/api/latest/static/files/data/dem/resources/license/License-COPDEM-30.pdf

thanks to https://twitter.com/Keiko_geo/status/1539058250892488704

**Sample Earth Engine Code**
Use the Get link button in GEE to help recreate the error if possible. 

**Screenshots**

**Additional context**

** Important to note that not all catalog datasets are owned and maintained by me so fixing them or updating them requires collaboration and may take longer than expected **

**Comment by samapriya** [comment]
Hi @schwehr 
I believe the STAC catalog that was the assumption made based on the license terms but I did link to the original license in the dataset description if you had looked at the actual catalog page for the dataset. I am happy to have a recommended license in place based on the description , I feel another close one would be CC by SA

https://samapriya.github.io/awesome-gee-community-datasets/projects/glo30/

So at this point, I think that was an assumption made to describe an open license as close as possible Global , Free, Full and Open and 

The Licensor grants to the User the following non-exclusive rights of use regarding the Copernicus WorldDEM-30:
(a) reproduction;
(b) distribution;
(c) communication to the General Public;
(d) adaptation, modification and combination with other data and information.

**Comment by samapriya** [comment]
Thanks @schwehr 
Based on our earlier discussion I will modify the STAC catalog accordingly, thank you for the discussion and ideas around how to handle this

**Comment by samapriya** [comment]
This has been fixed, thanks for the discussion :)
