### ISSUE TITLE
[Global ML Building Footprints: Missing footprints]

### ISSUE THREAD

**Issue by geo-ti** [samapriya/awesome-gee-community-datasets#47]
**Describe the bug**
Mumbai and Pune seems to have larger built-up extent as seen from the Google Base Map, but footprints don't show up in the filtered collection. 

**Sample Earth Engine Code**
[GEE Code Link](https://code.earthengine.google.co.in/bba49353c285245f65f7e3e0b8216cc3)

**Screenshots**
<img width="594" alt="Screenshot 2022-07-03 at 16 05 15" src="https://user-images.githubusercontent.com/84561605/177035809-e845cfb8-d4fd-451c-b9de-48d358250ae3.png">

<img width="773" alt="Screenshot 2022-07-03 at 16 02 54" src="https://user-images.githubusercontent.com/84561605/177035764-50c2d45c-b0be-4f6e-8617-46fa096d3627.png">

**Additional context**
Question - Does MS footprint data not include footprints of villages?

**Comment by samapriya** [comment]
Hi @geo-ti 
The datasets are brought in as-is from Microsoft's global building footprint release, feel free to post the question on that repo
https://github.com/microsoft/GlobalMLBuildingFootprints

Hope that helps for now
