### ISSUE TITLE
[Data Set: Bug Report] C-CAP High Resolution uses wrong sample code link

### ISSUE THREAD

**Issue by aazuspan** [samapriya/awesome-gee-community-datasets#48]
**Describe the bug**
Hi @samapriya, just wanted to give you a heads up that the [sample code link](https://code.earthengine.google.com/2661b87b5fb16598cfdb4b1ba510617d) listed for the [C-CAP High Resolution](https://samapriya.github.io/awesome-gee-community-datasets/projects/ccap_lc/) dataset is actually the sample code for [Urban Watch](https://samapriya.github.io/awesome-gee-community-datasets/projects/urban-watch/).

Thanks for maintaining this awesome project!

**Comment by samapriya** [comment]
Thanks @aazuspan 
I just pushed the correct sample link and should be live in a few minutes. Appreciate the heads-up
