### ISSUE TITLE
GABAM, Long, T et al. ,2019

### ISSUE THREAD

**Issue by WalidGharianiEAGLE** [samapriya/awesome-gee-community-datasets#49]
I come across this dataset and I think it will be very useful to be included in GEE.

### GABAM
30 m resolution global annual burned area maps (GABAM) of 1985-2019.

@article{Long_2019,
    doi = {10.3390/rs11050489},
    url = {https://doi.org/10.3390%2Frs11050489},
    year = 2019,
    month = {feb},
    publisher = {{MDPI} {AG}},
    volume = {11},
    number = {5},
    pages = {489},
    author = {Tengfei Long and Zhaoming Zhang and Guojin He and Weili Jiao and Chao Tang and Bingfang Wu and Xiaomei Zhang and Guizhou Wang and Ranyu Yin},
    title = {30 m Resolution Global Annual Burned Area Mapping Based on Landsat Images and Google Earth Engine},
    journal = {Remote Sensing}
}

![GABAM](https://user-images.githubusercontent.com/57763453/178213444-3528a808-baf0-408d-8afa-3f04130717ce.jpg)

Download Tool/Code snippets if any: [https://vapd.gitlab.io/post/gabam/)](https://vapd.gitlab.io/post/gabam/)

#### Required
License [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/)

Keywords: Global Burned Area, LANDSAT

Last updated: 2021-04-06

**Comment by samapriya** [comment]
Seems the dataset is under an open license which is even better
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/3CTMKP

**Comment by samapriya** [comment]
This has now been completed release information in the changelog 
https://samapriya.github.io/awesome-gee-community-datasets/projects/gabam/
