### ISSUE TITLE
Global Hydrologic Soil Group by wouellette

### ISSUE THREAD

**Issue by wouellette** [samapriya/awesome-gee-community-datasets#5]
### Dataset Name

the Hydrologic Soil Group (HSG) determines the Runoff Curve Number which is often used in hydrological modelling to estimate the direct runoff from rainfall. Four hydrologic soil groups and three dual hydrologic soil groups are  described by the USDA (2009) as follows:
• Group A: Soils in this group have low runoff potential when thoroughly wet. Water is transmitted
freely through the soil.
• Group B: Soils in this group have moderately low runoff potential when thoroughly wet. Water transmission through the soil is unimpeded.
• Group C: Soils in this group have moderately high runoff potential when thoroughly wet. Water
transmission through the soil is somewhat restricted.
• Group D: Soils in this group have high runoff potential when thoroughly wet. Water movement through the soil is restricted or very restricted.
•Dual hydrologic soil groups: Soils having a water table within 60 centimeters of the surface are placed in group D,
even though the saturated hydraulic conductivity may be favorable for water transmission. If these soils can be adequately drained, then they are assigned to dual hydrologic soil groups (A/D, B/D, and C/D) based on their saturated hydraulic conductivity and the water table depth when drained. The first letter applies to the drained condition and the second to the undrained condition.
In this context, adequately drained means that the seasonal high-water table is kept at least 60 centimeters below the surface in a soil, where as it would be higher in a natural state.

HiHydroSoil v2.0 can be used freely. It is required to properly cite HiHydroSoil v2.0 in the publication of any research study or report, by referring to:
[Simons, G.W.H., R. Koster, P. Droogers. 2020. HiHydroSoil v2.0 - A high resolution soil map of global hydraulic properties. FutureWater Report 213.](https://www.futurewater.nl/wp-content/uploads/2020/10/HiHydroSoil-v2.0-High-Resolution-Soil-Maps-of-Global-Hydraulic-Properties.pdf)

No additional licensing information is provided by the authors.

![image](https://user-images.githubusercontent.com/20474036/117018334-64d14000-acc2-11eb-9627-4bfb0f23c80c.png)

#### Earth Engine Snippet
Data Access: 
```js
var hydrologic_soil_group = ee.Image('users/WilliamOuellette/GlobalHydrologicSoilGroup');
```

Visualisation Code Snippet:
```js
var hydrologic_soil_group = ee.Image('users/WilliamOuellette/GlobalHydrologicSoilGroup')
                                              // The dual soil class groups are coded as 14 (A/D), 24 (B/D) and 34 (C/D)
                                              // Remapping them for visualization
                                              .remap([1, 14, 2, 24, 3, 34, 4], [1, 2, 3, 4, 5, 6, 7]); 

var palettes = require('users/gena/packages:palettes');
var palette = palettes.colorbrewer.YlGnBu[7];

Map.addLayer(hydrologic_soil_group, {min:1, max:7, palette: palette}, 'Global Hydrologic Soil Groups');
```
Extra Info: More data layers are made available by the same project [here](https://www.dropbox.com/sh/iaj2ika2t1pr7lr/AADpmMOal6VXModX5HL4aooFa/Layers?dl=0&subfolder_nav_tracking=1).

The community use of these ancillary layers (which are used for the most part to derive the global soil hydrologic group) should be discussed, as it is a lot of information.

#### Required
License Information: HiHydroSoil v2.0 can be used freely. No additional information made available by authors.

Curated by: William Ouellette
For authors, refer to [Simons, G.W.H., R. Koster, P. Droogers. 2020. HiHydroSoil v2.0 - A high resolution soil map of global hydraulic properties. FutureWater Report 213.](https://www.futurewater.nl/wp-content/uploads/2020/10/HiHydroSoil-v2.0-High-Resolution-Soil-Maps-of-Global-Hydraulic-Properties.pdf)

Keywords: Global Hydrologic Soil Group, Hydrology, Hydrological, Soil, Hydraulic, Conductivity, Runoff, Run-off, Water, Water Cycle

Last updated: October 2020

**Comment by samapriya** [comment]
Hi @wouellette 
Thanks for adding this, I see that there are additional layers from HiHydro v2 do you have them as well, also some parameter names from their files don't match Table 5 like there is no Field-WILT but a FIELD-CRIT and some are missing like wilt-perm. Thought you might have insights?

**Comment by wouellette** [comment]
Hi @samapriya, 
just double-checked and the following layers correspond:
`FIELD-CRIT` --> `FIELD-WILT`
`CRIT-WILT`--> `WILT-PERM`

Those layers are redundant however, as they are just the difference between `WCpF2` and `WCpF3`, and `WCpF3` and `WCpF4.2` respectively.

**Comment by samapriya** [comment]
Thanks @wouellette 
I have been in touch with the authors of the dataset too to get clarity on sharing and the additional layers. I am hoping to have your hydrologic soil group along with all 14 layers for varying soil depth. Thank you for double checking and explaining which layers would be valuable to keep. 

Since I am ingesting the other layers would you like me to copy over the layer you shares too so they have a consistent path in GEE. I am obviously attributing you for contributing the layer to the community datasets and even if I host the layers I would like to consider this layer as co curated by you. I appreciate your expertise and your feedback as I finalize it . Let me know

**Comment by wouellette** [comment]
Please host it on your end, it makes much more sense, especially if you are going to upload all layers.

Please reach out if you need any advice or encounter any issues whilst ingesting it. Ingesting it in a similar fashion to [soilgrids](https://code.earthengine.google.com/?asset=projects/soilgrids-isric/bdod_mean) would be the best way to go, with one layer per band. The full soilGrids collection is referenced under the following [project](https://git.wur.nl/isric/soilgrids/soilgrids.notebooks/-/blob/master/markdown/access_on_gee.md).

I am finalizing a GEE App readily using the soil hydrologic group layer, which will end up on github in the coming days. It would provide an additional example on its useability/usefulness.

**Comment by samapriya** [comment]
that's great I would love your advice once I put the dataset out to check for any errors or inconsistencies, I am glad to learn from community members, researchers, and users like you.  And yes I am ingesting it exactly like the SOIL grids data from ISRIC. Would love to see your app once it is out. I will update this ticket once I have the resources and page built out

**Comment by samapriya** [comment]
Dataset and pages updated to have a look when you find time, total at about 319 GB

https://samapriya.github.io/awesome-gee-community-datasets/projects/hihydro_soil/

**Comment by wouellette** [comment]
Looking good! The only thing I would adapt is the unit for the `Hydrologic_Soil_Group`:
`A (low runoff potential when thoroughly wet) water transmitted freely
B (moderately low runoff when thoroughly wet) transmission unimpeded
C (moderately high Runoff when thoroughly wet) transmission somewhat restricted
D (High Runoff potential when thoroughly wet) water movement restricted
Dual hydrologic group soils with 60cm from surface (A/D, B/D and C/D )based on their saturated hydraulic conductivity & water table depth First letter drained condition, second undrained condition`

Since the letters do not relate to a raster value directly, a `Class Table: Hydrologic_Soil_Group` could be added which indicates the value mapping:
```
1: A (low runoff potential when thoroughly wet) water transmitted freely
2: B (moderately low runoff when thoroughly wet) transmission unimpeded
3: C (moderately high Runoff when thoroughly wet) transmission somewhat restricted
4: D (High Runoff potential when thoroughly wet) water movement restricted
14: A/D Dual hydrologic group soils with 60cm from surface. First letter drained condition, second undrained condition
24: B/D Dual hydrologic group soils with 60cm from surface. First letter drained condition, second undrained condition
34: C/D Dual hydrologic group soils with 60cm from surface. First letter drained condition, second undrained condition
```

**Comment by samapriya** [comment]
Done, added a raster value map. Thanks for the help, closing the ticket now :)
