### ISSUE TITLE
LANDFIRE

### ISSUE THREAD

**Issue by lapuma** [samapriya/awesome-gee-community-datasets#50]
Follow the underlying template when creating an update dataset request

### Dataset Name and Catalog Page
Dataset Name and provide a link to the current dataset page.
LANDFIRE 2.0.0
LF2016 Remap
https://samapriya.github.io/awesome-gee-community-datasets/projects/landfire/
https://landfire.gov/getdata.php - viewer, mosaic download and api

### Dataset update , version and release date
Describe updates made to the dataset, including update date, release and/or version number pertaining to it.
LANDFIRE 2.2.0
LF2020
Most vegetation and fuel layers for CONUS AND AK available now. HI, USVI and Puerto Rico in a few weeks. Fire regime layers will be updated in September.
https://landfire.gov/lf_220.php

### Updated dataset link
Link to the update dataset , if the dataset is already an Earth Engine image collection provide the snippet
https://landfire.gov/getdata.php  - viewer, mosaic download and api

```js
var updated_dataset = ee.Image('path to updated dataset')
```

### Reason for update
If you own a particular dataset you should provide a reason for dataset update like reanalysis performed, temporarily removed for assessment and so on
LANDFIRE is moving to annual updates to account for changes in vegetation and fuels for recent disturbances on the landscape.

### Updated License
If the license remains the same just mention N/A
N/A

### Relationship to Dataset
Owner/Maintainer/Curator or any other
LANDFIRE Technical Lead, contractor to the USGS

Sample Code: Add a sample code maybe just adding your datasets in code editor and visualizing or summarizing with the updated dataset

Last updated: Last date you updated the dataset
2019L LANDFIRE 2.1.0 was the last update, released last June. LF2020 REPLACES LF2019L.

**Comment by samapriya** [comment]
This was a little confusing to follow but I am guessing you want the datasets to be updated to LF 2020 [LF 2.2.0] for 2022. Though I do see Hawaii and other insular areas missing but I can get started with CONUS

**Comment by samapriya** [comment]
This has now been completed, with some datasets for v2.2.0 yet to be generated and will be updated as they become available. Leaving the issue open to keep this in the running list

**Comment by lapuma** [comment]
Hi- thanks so much for updating to LFV2.2.0

I noticed you did not change the wording which still refers to Remap- v2.0.0. 

This page describes the v2.2.0 product which is an update to Remap. 

HTTPS://LANDFIRE.gov/lf_220.pho

The fire regime products for 2.2.0 are coming out at the end of this month. 

One thing I was wondering about was whether you would consider having both Remap v2.0.0 AND LF2020 v2.2.0 available to users. Remap was an important revision for us and a lot of people still use it. 

If not- just 2.2.0 is totally fine. 

Thanks for the service you are providing. 


Inga P. La Puma

**Comment by samapriya** [comment]
The page https://landfire.gov/lf_220.pho produces a 404 error it seems. 
![lf_220](https://user-images.githubusercontent.com/6677629/189554627-6d47de5d-76d1-421f-8fd2-5b8adf0d1f3a.PNG)

I am waiting for the remaining datasets to be updated. For now, it seems the following have yet to be updated
1. Fire Regime 
2. Public Events Geodatabase_1999_YEAR
3. Fuel Rulesets Database

About keeping both versions did you mean you want to know if I could keep both v 2.0.0 and 2.2.0? These are in place replacements so usually this means the old versions are deleted to update to new version

**Comment by samapriya** [comment]
Hi @lapuma 
Let me know when you have more updates on this feel free to reach out over email and I look forward to finishing the updates towards end of the week

**Comment by lapuma** [comment]
Good morning Samapriya-
I put the wrong url. I put .pho instead of .php! This is the correct one with information on v2.2.0: https://landfire.gov/lf_220.php <https://landfire.gov/lf_220.php>

Yes-- I WAS wondering if you could keep v2.0.0 as well as host v2.2.0; however, if this is not something that you generally do when data is updated, this is understandable and v2.2.0 is preferred.

You are correct for the layers that are yet to be released for v2.2.0. They should be out within a few weeks to finish out the v2.2.0 datasets. Thank you so much for hosting these public datasets for the GEE community.

Thanks, Inga

**Comment by samapriya** [comment]
sorry I missed this will update it today

**Comment by samapriya** [comment]
Just updated

**Comment by lapuma** [comment]
Yes! Sorry I found the form a bit confusing. But that is correct. HI and USVI/ PR should be out within a week or two. CONUS AND AK are complete. 

Inga P. La Puma
