### ISSUE TITLE
Vertical Optical Depth Climate Archive (VODCA)

### ISSUE THREAD

**Issue by Geethen** [samapriya/awesome-gee-community-datasets#52]
Follow the underlying template when creating new dataset issue entry

### Dataset Name
The Global Long-term Microwave Vegetation Optical Depth Climate Archive VODCA

Link to data: https://zenodo.org/record/2575599

Dataset Description: 
Vegetation optical depth (VOD) describes the attenuation of radiation by plants. VOD a function of frequency as well as vegetation water content, and by extension biomass. VOD has many possible applications in studies of the biosphere, such as biomass monitoring, drought monitoring, phenology analyzes or fire risk management.

We merged VOD observations from various spaceborne sensors (SSM/I, TMI, AMSR-E, AMSR2, WindSat) to create global long-term vod time series. Prior to aggregation the data has been rescaled to AMSR-E, removing systematic differences between them.

There is a product for C-band (~6.9 GHz, 2002 - 2018), X-band (10.7 GHz, 1997 - 2018) and Ku-band (~19 GHz, 1987 - 2017). The data is global sampled on a regular 0.25 degrees grid. Each product is available as daily global netcdf4 files.
Paper with detailed descriptions and methods for derivation/data preparation: https://essd.copernicus.org/articles/12/177/2020/essd-12-177-2020.html

#### Required
License Information: License for files: https://creativecommons.org/licenses/by/4.0/legalcode

Curated by: Moesinger, Leander; Dorigo, Wouter; De Jeu, Richard; Van der Schalie, Robin; Scanlon, Tracy; Teubner, Irene; Forkel, Matthias

Keywords: Biomass, vegetation

Last updated: 27 Feb 2019

**Comment by samapriya** [comment]
This has finally been completed closing the issue
https://gee-community-catalog.org/projects/vodca/
