### ISSUE TITLE
South African National Land Cover (1990, 2013, 2020)

### ISSUE THREAD

**Issue by Geethen** [samapriya/awesome-gee-community-datasets#53]
Follow the underlying template when creating new dataset issue entry

### Dataset Name
South African National Land Cover (1990, 2013, 2020)

72-class land cover dataset for South Africa 
Link to data: https://egis.environment.gov.za/data_egis/data_download/current
There are also change assessments carried out between the datasets available here

#### Required
License Information: Likely a similar license to the 2018 version (already on the community datasets)

Curated by: Department of Environmental affairs

Keywords: Land use land cover

Last updated: Last date you updated the dataset

**Comment by samapriya** [comment]
Can you provide direct link to the files seems the page has a lot of assets

**Comment by Geethen** [comment]
2020 SANLC (geographic): 
ee.Image("projects/ee-geethensingh/assets/SANLC_2020")
https://sfiler.environment.gov.za:8443/ssf/s/readFile/folderEntry/40906/8afbc1c77a484088017a4e8a1abd0052/1624802570000/last/SA_NLC_2020_Geographic.tif.vat.zip


2013 SANLC (geographic): 
ee.Image("users/geethensingh/SANLC__2013_14")
https://sfiler.environment.gov.za:8443/ssf/s/readFile/folderEntry/19341/8afbc1c75aea91ba015bd35f2c0b51b2/1462800851000/last/SALandCover_ReprojectedGEO_2013_GTI_72Classes.zip

1990 SANLC (geographic): 
ee.Image("projects/ee-geethensingh/assets/SANLC_1990")
https://sfiler.environment.gov.za:8443/ssf/s/readFile/folderEntry/14/8afbc1c7547f664c01552a6addf000ea/1462800349000/last/SALandCover_ReprojectedGEO84_1990_GTI_72Classes.zip

**Comment by samapriya** [comment]
Thanks @Geethen 
Can you make sure you shared the 1990 dataset and the path is correct I am unable to access it currently

**Comment by samapriya** [comment]
This has now been completed and the datasets page and datasets have been updated
https://gee-community-catalog.org/projects/sa_nlc/

**Comment by Geethen** [comment]
I have shared the dataset. Apologies for that. Although I see you uploaded it to the project. thanks. Users should note that there have been changes to the classification nomenclature between the various years. details can be found in the reports that are downloaded with the datasets.
