### ISSUE TITLE
docs/projects/gmd.md

### ISSUE THREAD

**Issue by karelvancamp** [samapriya/awesome-gee-community-datasets#55]
**Describe the bug**
datasource no longer available

**Sample Earth Engine Code**
[Using example from gmd.md](https://code.earthengine.google.com/61a2c6295e4ef37ffc17dd5e0dbbd396)

ImageCollection.load: ImageCollection asset 'projects/sat-io/open-datasets/global_mangrove_distribution/agb' not found.
ImageCollection.load: ImageCollection asset 'projects/sat-io/open-datasets/global_mangrove_distribution/hba95' not found.
ImageCollection.load: ImageCollection asset 'projects/sat-io/open-datasets/global_mangrove_distribution/hmax95' not found.
Collection.loadTable: Collection asset 'projects/sat-io/open-datasets/global_mangrove_distribution/americas_tree_measurements' not found.

**Comment by karelvancamp** [comment]
I'm verifying all datasets snippets under docs. Should be able to get full list of broken links.

**Comment by karelvancamp** [comment]
This is a more complete list, only 3 docs affected.

[{'tableId': 'projects/sat-io/open-datasets/global-fire-atlas/perimeter/Global_fire_atlas_V1_perimeter_2016'},
 {'id': 'projects/sat-io/open-datasets/global_mangrove_distribution/agb'},
 {'id': 'projects/sat-io/open-datasets/global_mangrove_distribution/hba95'},
 {'id': 'projects/sat-io/open-datasets/global_mangrove_distribution/hmax95'},
 {'tableId': 'projects/sat-io/open-datasets/global_mangrove_distribution/americas_tree_measurements'},
 {'tableId': 'projects/sat-io/open-datasets/sedac/wacvm-social-vulnerability-indices-paci'},
 {'tableId': 'projects/sat-io/open-datasets/sedac/wacvm-social-vulnerability-indices-pei'},
 {'tableId': 'projects/sat-io/open-datasets/sedac/wacvm-social-vulnerability-indices-svi'}]

**Comment by samapriya** [comment]
Access has now been updated and datasets should now be globally readable
