### ISSUE TITLE
VIIRS-like nighttime light data & Zuoqi Chen

### ISSUE THREAD

**Issue by Bonny-Li** [samapriya/awesome-gee-community-datasets#56]
Follow the underlying template when creating new dataset issue entry

### Dataset Name
Chen, Zuoqi; Yu, Bailang; Yang, Chengshu; Zhou, Yuyu; Yao, Shenjun; Qian, Xingjian; Wang, Congxiao; Wu, Bin; Wu, Jianping, 2020, "An extended time-series (2000-2018) of global NPP-VIIRS-like nighttime light data", https://doi.org/10.7910/DVN/YGIVCD, Harvard Dataverse, V3, UNF:6:qMXz0adYK5q7pFqKgsCFOQ== [fileUNF] 

Thumbnail or Snapshot (Optional)

#### Earth Engine Snippet
```js
var asset_name = ee.ImageCollection("path to your collection")

or

var asset_name = ee.Image("path to your image")

or

var asset_name = ee.FeatureCollection("path to your table/feature collection")
```

Sample Code: Add a sample code maybe just adding your datasets in code editor and visualizing or summarizing

Extra Info: Website link of this dataset : https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/YGIVCD
                  Website link of the paper: https://essd.copernicus.org/articles/13/889/2021/ 

Download Tool/Code snippets if any: If source is specialized or you have an associated tool

#### Required
License Information:This work is distributed under the Creative Commons Attribution 4.0 License.

Curated by: Zuoqi Chen1,2, Bailang Yu3,4, Chengshu Yang3,4, Yuyu Zhou5, Shenjun Yao3,4, Xingjian Qian3,4, Congxiao Wang3,4, Bin Wu3,4, and Jianping Wu3,4

Keywords: Night time light, VIIRS

Last updated: 2022-08-17

**Comment by samapriya** [comment]
This has now been completed you can find the dataset page here 
https://samapriya.github.io/awesome-gee-community-datasets/projects/npp_viirs_ntl

Thank you for submitting a request
