### ISSUE TITLE
Lakes around Asia Water Tower

### ISSUE THREAD

**Issue by RSNuo** [samapriya/awesome-gee-community-datasets#57]
Follow the underlying template when creating new dataset issue entry

### Dataset Name
Dataset description and any detailed citation and DOI and license information.

Thumbnail or Snapshot (Optional)

#### Earth Engine Snippet
```js

var AWTlakes_1977_wet = ee.FeatureCollection("users/201872253/AWTlakes_1977_wet")
var AWTlakes_1990_wet = ee.FeatureCollection("users/201872253/AWTlakes_1990_wet")
var AWTlakes_2000_wet = ee.FeatureCollection("users/201872253/AWTlakes_2000_wet")
var AWTlakes_2010_wet = ee.FeatureCollection("users/201872253/AWTlakes_2010_wet")
var AWTlakes_2020_wet = ee.FeatureCollection("users/201872253/AWTlakes_2020_wet")

var AWTlakes_1977_dry = ee.FeatureCollection("users/201872253/AWTlakes_1977_dry")
var AWTlakes_1990_dry = ee.FeatureCollection("users/201872253/AWTlakes_1990_dry")
var AWTlakes_2000_dry = ee.FeatureCollection("users/201872253/AWTlakes_2000_dry")
var AWTlakes_2010_dry = ee.FeatureCollection("users/201872253/AWTlakes_2010_dry")
var AWTlakes_2020_dry = ee.FeatureCollection("users/201872253/AWTlakes_2020_dry")
```

Recent studies suggest that Asian Water Tower (AWT) are vulnerable to climate change with a detrimental effect on water and food security in the basins it fed. Comprehensive information on the spatio-temporal variability of lakes, an important freshwater resource, is lacking. Therefore, we analyzed 89,480 Landsat images to map the lakes around the AWT between 1977±2 and 2020±2. It was found that from 1977±2 to 2020±2, 84% of the mapped lakes grew during the rainy season, while 81% grew during the dry season. Lakes in the inner TP and Tarim inner basins expanded dramatically. The Helmand, Amu Darya and Yangtze basins are the main position of lake shrinkage. Subsequently, the trends in precipitation, snow water equivalent, glacier mass, and permafrost in each basin were analyzed and found that changes in the size of lakes are closely related to them. Meanwhile, human intervention has caused the shrinkage of some plain lakes. As the AWT retreats and the lakes recharge, we need immediate action to manage risk and adaptation. 

#### Required
License Information: License type and information

Curated by: Nuo Xu, Andre Daccache, Peng Gou, Chong Liu, Jiahua Zhang, Tianyu Zhou, Bo Zhou, Sierra Burkhart, Wei Nie

Keywords: lake, Asian Water Tower, climate change

Last updated: 08/22/2022

**Comment by samapriya** [comment]
Hi @RSNuo 
Could you provide details of the paper and citation details. As well as license information. This will help evaluate and complete the metadata for the dataset.

**Comment by RSNuo** [comment]
> Hi @RSNuo Could you provide details of the paper and citation details. As well as license information. This will help evaluate and complete the metadata for the dataset.

Hi @samapriya The paper is still in review. I'll update these details as soon as it's published. Thanks for your patience!

**Comment by samapriya** [comment]
Since I have had no response closing for now
