### ISSUE TITLE
Annual VNL VIIRS V2.1  & Elvidge et. al (2021)

### ISSUE THREAD

**Issue by cmg777** [samapriya/awesome-gee-community-datasets#58]
Follow the underlying template when creating new dataset issue entry

### Dataset Name

Annual VNL V2.1

A new consistently processed time series of annual global VIIRS nighttime lights has been produced from monthly cloud-free average radiance grids spanning 2012 to 2021. The new methodology (version 2.1) is a modification of the original VNL V1  that is available in the Earth Engine catalogue.  Compared to VNL V1, this improved VNL V2.1 version removes ephemeral lights and background noise.

In both methods there is an initial filtering to remove sunlit, moonlit and cloudy pixels, leading to rough composites that contains lights, fires, aurora and background. In the original method, the rough annual composites are made from a full year of nightly DNB data. In the new method, the rough composites are made on monthly increments and then combined to form rough annual composites. Both methods employ outlier removal to discard biomass burning pixels and isolate the background.

In the original method the outlier removal is performed on scattergrams generated for each 15 arc second grid cell, with outliers clipped off from both the high and low radiance sides of the scattergram. The discard of outlier pixels proceeds until the scattergram’s standard deviation stabilizes. The new method uses the twelve-month median radiance to discard high and low radiance outliers, filtering out most fires and isolating the background. Background areas are zeroed out in both methods using the data range (DR) calculated from 3x3 grid cells. In both methods, the DR threshold for background is indexed to cloud-cover levels, with higher DR thresholds in areas having low numbers of cloud-free coverages. In the new method, particular attention is given to setting a single DR threshold for distinguishing lit grid cells from background for each 15 arc second grid cell. This is achieved by setting the DR threshold from a multiyear maximum median and a corresponding multiyear percent cloud-cover grids. The multiyear approach makes it possible to detect lighting present in each 15 arc second grid cell with a single DR threshold across all the years in the series.

- Website: https://eogdata.mines.edu/products/vnl/#annual_v2
- Download page: https://eogdata.mines.edu/nighttime_light/annual/v21/

Elvidge, C.D, Zhizhin, M., Ghosh T., Hsu FC, Taneja J. Annual time series of global VIIRS nighttime lights derived from monthly averages:2012 to 2019. Remote Sensing 2021, 13(5), p.922, https://doi.org/10.3390/rs13050922

#### Earth Engine Snippet
```js
var asset_name = ee.ImageCollection("path to your collection")

or

var asset_name = ee.Image("path to your image")

or

var asset_name = ee.FeatureCollection("path to your table/feature collection")
```

Sample Code: Add a sample code maybe just adding your datasets in code editor and visualizing or summarizing

Extra Info: Feel free to add any optional details 

Download Tool/Code snippets if any: If source is specialized or you have an associated tool

#### Required
License Information: License type and information

In the website of the data provider (Earth Observation Group), the following usage information is provided:

When using the data please credit the product generation to the Earth Observation Group, Payne Institute for Public Policy, with proper citations as below.

Elvidge, C.D, Zhizhin, M., Ghosh T., Hsu FC, Taneja J. Annual time series of global VIIRS nighttime lights derived from monthly averages:2012 to 2019. Remote Sensing 2021, 13(5), p.922, https://doi.org/10.3390/rs13050922

Curated by: 

Elvidge, C.D, Zhizhin, M., Ghosh T., Hsu FC, Taneja J. Annual time series of global VIIRS nighttime lights derived from monthly averages:2012 to 2019. Remote Sensing 2021, 13(5), p.922, https://doi.org/10.3390/rs13050922

Keywords: 
nighttime lights, VIIRS, annual time series

Last updated: 	
2022-08-08

**Comment by samapriya** [comment]
Hi @cmg777 
Can you help me get more license information on these? I would need to know the license type and whether or not they can be reshared

**Comment by cmg777** [comment]
Hi @samapriya 

Ok, I will send an email to the Earth Observation Group to confirm the license.

**Comment by cmg777** [comment]
Hi @samapriya 

Regarding the license, I found the following statement:

---------------
"Colorado School of Mines data, information, and products, regardless of the method of delivery, are not subject to copyright and carry no restrictions on their subsequent use by the public. Once obtained, they may be put to any lawful use. The forgoing data is in the public domain and is being provided without restriction on use and distribution."
-----------------

Note that the Google Earth Catalog uses the same statement for distributing the version 1 of the VNL product.  So, as version 2 is also product of the Colorado School of Mines,  it also follows the same terms of use:  The data is in the public domain and is being provided without restriction on use and distribution.

**Comment by samapriya** [comment]
Got it thank you for confirming

**Comment by cmg777** [comment]
Any update on the processing of the images?

**Comment by samapriya** [comment]
Unfortunately the file structures were not very clear and needed to be reprocessed . So not a high priority right now in favor of other datasets. I will come back to this in time

**Comment by cmg777** [comment]
Got it. Thank you for the update.

**Comment by samapriya** [comment]
Hi @cmg777 
Seems 2012 is the year with some confusion 18 datasets and 2 subsets which is harder to interpret. This dataset will be added to the insiders program and I can let you know once this is ready so you can apply for the insiders program to get access to the data

**Comment by cmg777** [comment]
OK @samapriya 
Please let me know when the dataset is added to the insiders program.

**Comment by samapriya** [comment]
This will be announced in the next release, but you can find the [page here](https://gee-community-catalog.org/projects/eog_viirs_ntl/) and added onto the insiders program. Once you have applied to the insiders program you will be added to the google group. Use the dataset link I just provided as the dataset you contributed for the insiders application. Thanks for being patient on this one

**Comment by cmg777** [comment]
I tried running the code, but I got an error: "imageCollection asset not found". Here is the screenshot 
<img width="1417" alt="EOG-VNL-V21 - Earth Engine Code Editor 2023-01-29 17-33-33" src="https://user-images.githubusercontent.com/26156651/215314998-8b03c941-483b-41aa-b392-0707d89bda7a.png">

Thank you very much @samapriya.

**Comment by samapriya** [comment]
As I had mentioned earlier apply to the insiders program https://gee-community-catalog.org/insiders/

in the Google form, fill your GEE email address for access.

**Comment by cmg777** [comment]
Done. As indicated, I used  the dataset link you sent me and used my  GEE email address.  
![Monosnap GEE Community Catalog: Insiders Program 2023-01-29 22-20-48](https://user-images.githubusercontent.com/26156651/215329195-2598630d-34e4-470e-93f9-85e130da696b.png)

**Comment by samapriya** [comment]
I just added you to the insiders program google group; please try it now

**Comment by cmg777** [comment]
Thank you very much. I works now. I look forward to contributing to the insiders program.
