### ISSUE TITLE
Global spatio-temporally harmonised population 2000-2020 & Lloyd et al (2019))

### ISSUE THREAD

**Issue by cmg777** [samapriya/awesome-gee-community-datasets#59]
### Dataset Name
Global spatio-temporally harmonised population 2000-2020

Using a random forest-based dasymetric redistribution, this dataset provides a multi-temporal, globally consistent, high-resolution measurement of human population over the 2000-2020 period.  

Data download page:
https://hub.worldpop.org/geodata/listing?id=64

Link to open access paper: https://www.tandfonline.com/doi/full/10.1080/20964471.2019.1625151

Citation: 
Lloyd, C. T., Chamberlain, H., Kerr, D., Yetman, G., Pistolesi, L., Stevens, F. R., ... & Tatem, A. J. (2019). Global spatio-temporally harmonised datasets for producing high-resolution gridded population distribution datasets. Big earth data, 3(2), 108-139.

Thumbnail or Snapshot (Optional)

#### Earth Engine Snippet
```js
var asset_name = ee.ImageCollection("path to your collection")

or

var asset_name = ee.Image("path to your image")

or

var asset_name = ee.FeatureCollection("path to your table/feature collection")
```

Sample Code: Add a sample code maybe just adding your datasets in code editor and visualizing or summarizing

Extra Info: Feel free to add any optional details 

Download Tool/Code snippets if any: If source is specialized or you have an associated tool

#### Required
License Information: Creative Commons Attribution 4.0 International

WorldPop datasets are available under the Creative Commons Attribution 4.0 International License. This means that you are free to share (copy and redistribute the material in any medium or format) and adapt (remix, transform, and build upon the material) for any attribution purpose, even commercially, provided IS included (appropriate credit and a link to the licence).

Curated by: 
Lloyd, C. T., Chamberlain, H., Kerr, D., Yetman, G., Pistolesi, L., Stevens, F. R., ... & Tatem, A. J. (2019). Global spatio-temporally harmonised datasets for producing high-resolution gridded population distribution datasets. Big earth data, 3(2), 108-139.

Keywords: Human population, globally harmonized, temporally harmonized, multi-year, random forest 

Last updated:  Unknown

**Comment by samapriya** [comment]
Did you no longer want me to fetch this one @cmg777

**Comment by cmg777** [comment]
Hi @samapriya 
Thank you very much for your great work!
This collection is not longer needed because I just found it the official catalog: https://developers.google.com/earth-engine/datasets/catalog/WorldPop_GP_100m_pop?hl=en

All the best!

**Comment by samapriya** [comment]
haha Got it thanks for checking :)
