### ISSUE TITLE
Benchmark maps of 33 years of secondary forest age for Brazil & Celso H. L. Silva Junior

### ISSUE THREAD

**Issue by nileshsnshinde** [samapriya/awesome-gee-community-datasets#6]
Follow the underlying template when creating new dataset issue entry

### Dataset Name
Benchmark maps of 33 years of secondary forest age for Brazil

Thumbnail or Snapshot (Optional)

#### Earth Engine Snippet
```js
var asset_name = ee.ImageCollection("path to your collection")

or

var asset_name = ee.Image("path to your image")

or

var asset_name = ee.FeatureCollection("path to your table/feature collection")
```

Sample Code: Add a sample code maybe just adding your datasets in code editor and visualizing or summarizing

Extra Info: Feel free to add any optional details 

Download Tool/Code snippets if any: If source is specialized or you have an associated tool

#### Required
License Information: License type and information

Curated by: Celso H. L. Silva Junior (celsohlsj@gmail.com)

Data repository : https://zenodo.org/record/3928660#.YJxPxbVKiHs

Keywords: secondary growth forest. MapBiomas, Brazil 

Last updated: March 31, 2020

**Comment by samapriya** [comment]
The author had already made this available in GEE but I added the page and citation and code links for ease of use

https://samapriya.github.io/awesome-gee-community-datasets/projects/secondary_forest/

Closing this issue :) thanks for submitting the dataset
