### ISSUE TITLE
Global maps of habitat types

### ISSUE THREAD

**Issue by Geethen** [samapriya/awesome-gee-community-datasets#60]
It is suggested that you can use the updatemask function to update the 2015 habitat data to a later year. While this is useful for identifying the pixels that changed it is more useful to get an updated 2015 habitat layer with the updated habitat data for the year of interest in a single new layer. it may be useful to add an example for that in the docs. I have used the firstNonZero function for that.

## Example

# IUCN habitat classification
# Level 1 and level 2 for the year 2015
var lvl1 = ee.Image("users/Uploads/habitattypes/iucn_habitatclassification_composite_lvl1_ver004")
var lvl2 = ee.Image("users/Uploads/habitattypes/iucn_habitatclassification_composite_lvl2_ver004")

# # Changemask for 2019
var change2019_lvl1 = ee.Image("users/Uploads/habitattypes/changemasks2019/iucn_habitatclassification_2019changemask_lvl1_ver004").select('comp2019').unmask(0)
var change2019_lvl2 = ee.Image("users/Uploads/habitattypes/changemasks2019/iucn_habitatclassification_2019changemask_lvl2_ver004").select('comp2019').unmask(0)

# Level 1 and level 2 for the year 2019
var lvl12019 = change2019_lvl1.firstNonZero(lvl1)
var lvl22019 = change2019_lvl2.firstNonZero(lvl2)

**Comment by samapriya** [comment]
No idea why I took so long to update this. This has been fixed and the page updated. I have also copied the dataset to open datasets collections with sat-io project
