### ISSUE TITLE
Tsinghua FROM-GLC10 global land cover dataset

### ISSUE THREAD

**Issue by xuange92** [samapriya/awesome-gee-community-datasets#61]
Follow the underlying template when creating an update dataset request

### Dataset Name and Catalog Page
Tsinghua FROM-GLC10; Global land use and land cover

### Dataset update , version and release date
Released in 2019

### Updated dataset link
[Link to the update dataset , if the dataset is already an Earth Engine image collection provide the snippet](http://data.ess.tsinghua.edu.cn/fromglc10_2017v01.html)

```js
var updated_dataset = ee.Image('path to updated dataset')
```

### Reason for update
If you own a particular dataset you should provide a reason for dataset update like reanalysis performed, temporarily removed for assessment and so on

### Updated License
If the license remains the same just mention N/A

### Relationship to Dataset
Owner/Maintainer/Curator or any other

Sample Code: Add a sample code maybe just adding your datasets in code editor and visualizing or summarizing with the updated dataset

Last updated: Last date you updated the dataset

**Comment by xuange92** [comment]
http://data.ess.tsinghua.edu.cn/fromglc10_2017v01.html

**Comment by samapriya** [comment]
This has now been completed, thank you for contributing
https://samapriya.github.io/awesome-gee-community-datasets/projects/glc10/
