### ISSUE TITLE
[ESRI Land Cover Time Series: Bug Report]

### ISSUE THREAD

**Issue by giswqs** [samapriya/awesome-gee-community-datasets#62]
**Describe the bug**
The ESRI Land Cover timeseries (2017-2021) no longer has class 3 (Grass) and class 6 (Shrub/scrub). The two classes have been combined as class 11 (Rangeland). The [example code](https://code.earthengine.google.com/59d1cbd7920b683654f91eb3d852169d) you provided on the dataset page has incorrect palette. I have fixed it for you. 

- https://samapriya.github.io/awesome-gee-community-datasets/projects/S2TSLULC/
- https://www.arcgis.com/home/item.html?id=d3da5dd386d140cf93fc9ecbf8da5e31
- https://livingatlas.arcgis.com/landcover/

**Sample Earth Engine Code**
https://code.earthengine.google.com/d5af666f47990b99baacc1373a802390

**Screenshots**

![image](https://user-images.githubusercontent.com/5016453/189510583-5a3abac5-58a4-4d77-9dac-aeae9869a499.png)

![image](https://user-images.githubusercontent.com/5016453/189510518-093d41a3-1fce-429e-b044-95d189d4d079.png)

**Comment by samapriya** [comment]
Than you @giswqs 
I made necessary changes to the doc and the code appreciate the bug report as always :) Let me know if you find something else
