### ISSUE TITLE
CloudSEN12 & Cesar Aybar

### ISSUE THREAD

**Issue by csaybar** [samapriya/awesome-gee-community-datasets#63]
## **CloudSEN12 - a global dataset for semantic understanding of cloud and cloud shadow in Sentinel-2**

CloudSEN12 is a large dataset for cloud semantic understanding that consists of 9880 regions of interest (ROIs). Each ROI has five 5090x5090 meters image patches (IPs) collected on different dates that match one of the following cloud cover groups:

- clear (0%)

- low-cloudy (1% - 25%) 

- almost clear (25% - 45%)

- mid-cloudy (45% - 65%)

- cloudy (65% >)

The dataset is already available here: https://shorturl.at/cgjtz. Check out the website https://cloudsen12.github.io/ for greater detail on CloudSEN12.

<center>
<img src=https://user-images.githubusercontent.com/16768318/190843651-c8182d07-a49e-4524-be16-2eb38fe9cdc8.png>
</center>

Currently included layers are:

#### **Earth Engine Snippet: Hand-crafted labels - high-quality**

```
var cs12_high = ee.ImageCollection("projects/sat-io/open-datasets/cloudsen12/high");
```

[example01](https://github.com/samapriya/awesome-gee-community-datasets/issues/63#issue-1376683105),  [example02](https://code.earthengine.google.com/582596f9dd33ed59c89c06b5a133f672?accept_repo=users%2Fcsaybar%2FcloudSEN12).

#### **Earth Engine Snippet: Hand-crafted labels - scribble**

```
var cs12_scribble = ee.ImageCollection("projects/sat-io/open-datasets/cloudsen12/scribble");
```

[example](https://code.earthengine.google.com/2baf524dd8c91436d32f18a0855f8266?accept_repo=users%2Fcsaybar%2FcloudSEN12).

#### **Earth Engine Snippet: Hand-crafted labels - nolabel**

```
var cs12_nolabel = ee.ImageCollection("projects/sat-io/open-datasets/cloudsen12/nolabel");
```

[example](https://code.earthengine.google.com/73f7ff7e454f88e62d42fdbdd6021275?accept_repo=users%2Fcsaybar%2FcloudSEN12).

#### **Earth Engine Snippet: IPs footprint**

```
var cs12_geom = ee.ImageCollection("projects/sat-io/open-datasets/cloudsen12/footprint");
```

[example](https://code.earthengine.google.com/4566b534db7ed6d5f11ed317c5080ca8?accept_repo=users%2Fcsaybar%2FcloudSEN12).

### **Citation**

When using the data, please cite:

```
Cesar Aybar, Luis Ysuhuaylas, Jhomira Loja, Karen Gonzales, Fernando Herrera,
Lesly Bautista, Roy Yali, Angie Flores, Lissette Diaz, Nicole Cuenca, Wendy 
Espinoza, Fernando Prudencio, Joselyn Inga, Valeria LLactayo, David Montero, 
Martin Sudmanns, Dirk Tiede, Gonzalo Mateo-García, & Luis Gómez-Chova. (2022). 
CloudSEN12 - a global dataset for semantic understanding of cloud and cloud 
shadow in Sentinel-2. https://eartharxiv.org/repository/view/3615/
```

The data are supplementary material to:

```
Cesar Aybar, Luis Ysuhuaylas, Jhomira Loja, Karen Gonzales, Fernando Herrera,
Lesly Bautista, Roy Yali, Angie Flores, Lissette Diaz, Nicole Cuenca, Wendy 
Espinoza, Fernando Prudencio, Joselyn Inga, Valeria LLactayo, David Montero, 
Martin Sudmanns, Dirk Tiede, Gonzalo Mateo-García, & Luis Gómez-Chova. (2022). 
CloudSEN12 - a global dataset for semantic understanding of cloud and cloud 
shadow in Sentinel-2 (1.0) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.
7034410
```

### **License**

This work is licensed under a Creative Commons Attribution 4.0 International License. You are free to copy and redistribute the material in any medium or format, and to transform and build upon the material for any purpose, even commercially. You must give appropriate credit, provide a link to the license, and indicate if changes were made.

<br>

**Keywords:** cloud, deep learning, Sentinel-2, Sentinel-1, U-Net

**Comment by csaybar** [comment]
DataSet link: https://console.cloud.google.com/storage/browser/cs2migration

**Comment by samapriya** [comment]
Hey @csaybar 
Thank you for the sample code absolutely happy to add properties I mostly do if there are existing metadata. The system:time_start will be outside the main property but the rest looks good. I see that there is a collection called footprint in there too is there is a folder for this I could only find high, scribble and no label unless I missed something

**Comment by csaybar** [comment]
Hi @samapriya, Yes, I was thinking of a root folder named "cloudsen12" with three ee.ImageCollection's:

 - /high -> with 10k ee.Image's,
 - /scribble -> with 10k ee.Image's,
 - /nolabel -> with 29k ee.Image's,

and 1 ee.FeatureCollection which is already available in `users/csaybar/cloudsen12`. Resulting in 4 elements

```
var cs12_high = ee.ImageCollection("projects/sat-io/open-datasets/cloudsen12/high");
var cs12_high = ee.ImageCollection("projects/sat-io/open-datasets/cloudsen12/scribble");
var cs12_high = ee.ImageCollection("projects/sat-io/open-datasets/cloudsen12/nolabel");
var cs12_high = ee.ImageCollection("projects/sat-io/open-datasets/cloudsen12/footprint");
```

**Comment by samapriya** [comment]
Got it thank makes sense

**Comment by samapriya** [comment]
Also let me know if you would like me to wait till the paper is actually published I understand that this is currently in preprint and has not been peer reviewed.

**Comment by samapriya** [comment]
Hey @csaybar 
Quick update ingest has been completed will work on the details and get back to you if I have questions. Let me know when you think it is release ready

**Comment by csaybar** [comment]
hi @samapriya 

Thank you so much :bowing_man: , I made some mistakes in the preprint publication (the author's names are not correct :face_with_spiral_eyes:)  I will let you know when it will be fixed, I hope in less than a week, after that, I think we can be released.

**Comment by samapriya** [comment]
This has now been completed. You can find it here https://gee-community-catalog.org/projects/cloudsen12/

Closing issue and thank you for contributing
