### ISSUE TITLE
Global 1 km × 1 km GDP and Electricity consumption 1992-2019 by Chen et al. (2022)

### ISSUE THREAD

**Issue by cmg777** [samapriya/awesome-gee-community-datasets#65]
### Dataset Name

Global 1 km × 1 km gridded revised real gross domestic product and electricity consumption during 1992-2019 based on calibrated nighttime light data

From the abstract of the paper:
"In this study, we employed a series of methods, such as a particle swarm optimization-back propagation (PSO-BP) algorithm, to unify the scales of DMSP/OLS and NPP/VIIRS images and obtain continuous 1 km × 1 km gridded nighttime light data during 1992–2019. Subsequently, from a revised real growth perspective, we employed a top-down method to calculate global 1 km × 1 km gridded revised real GDP and electricity consumption during 1992–2019 based on our calibrated nighttime light data."

Paper citation:
Chen, J., Gao, M., Cheng, S., Hou, W., Song, M., Liu, X., & Liu, Y. (2022). Global 1 km× 1 km gridded revised real gross domestic product and electricity consumption during 1992–2019 based on calibrated nighttime light data. Scientific Data, 9(1), 1-14. https://doi.org/10.1038/s41597-022-01322-5

Data citation:
Chen, Jiandong; Gao, Ming (2021): Global 1 km × 1 km gridded revised real gross domestic product and electricity consumption during 1992-2019 based on calibrated nighttime light data. figshare. Dataset. https://doi.org/10.6084/m9.figshare.17004523.v1 

Download page: https://figshare.com/articles/dataset/Global_1_km_1_km_gridded_revised_real_gross_domestic_product_and_electricity_consumption_during_1992-2019_based_on_calibrated_nighttime_light_data/17004523/1

#### Earth Engine Snippet
```js
var asset_name = ee.ImageCollection("path to your collection")

or

var asset_name = ee.Image("path to your image")

or

var asset_name = ee.FeatureCollection("path to your table/feature collection")
```

Sample Code: Add a sample code maybe just adding your datasets in code editor and visualizing or summarizing

Extra Info: Feel free to add any optional details 

Download Tool/Code snippets if any: If source is specialized or you have an associated tool

#### Required
License Information: 

[CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)

Curated by: 
Chen, J., Gao, M., Cheng, S., Hou, W., Song, M., Liu, X., & Liu, Y. (2022). Global 1 km× 1 km gridded revised real gross domestic product and electricity consumption during 1992–2019 based on calibrated nighttime light data. Scientific Data, 9(1), 1-14. https://doi.org/10.1038/s41597-022-01322-5

Keywords: GDP, electricity consumption, harmonized

Last updated: 13.11.2021

**Comment by samapriya** [comment]
Hi @cmg777 
Can you report  back on the units for both datasets

**Comment by cmg777** [comment]
Hi @samapriya 
Here are the units :

- GDP: Millions of 2017 US dollars
- Electricity consumption: Kilowatt hours

**Comment by samapriya** [comment]
Perfect thank you

**Comment by samapriya** [comment]
This has now been completed you can find the page here. https://gee-community-catalog.org/projects/elc_gdp/

Closing issue and thank you for contributing

**Comment by cmg777** [comment]
Thank you very much.
