### ISSUE TITLE
Global Fire Atlas & Niels Andela 

### ISSUE THREAD

**Issue by nileshsnshinde** [samapriya/awesome-gee-community-datasets#7]
Follow the underlying template when creating new dataset issue entry

### Dataset Name
Dataset description and any detailed citation and DOI and license information.

Thumbnail or Snapshot (Optional)

#### Earth Engine Snippet
```js
var asset_name = ee.ImageCollection("path to your collection")

or

var asset_name = ee.Image("path to your image")

or

var asset_name = ee.FeatureCollection("path to your table/feature collection")
```

Sample Code: Add a sample code maybe just adding your datasets in code editor and visualizing or summarizing

Extra Info: Feel free to add any optional details 

Download Tool/Code snippets if any: If source is specialized or you have an associated tool

#### Required
License Information: Open Source 

Curated by: Niels Andela (niels.andela@nasa.gov).

Keywords: global fire incidence

Last updated: April 24th, 2019

**Comment by samapriya** [comment]
This has been added you can find it here 
https://samapriya.github.io/awesome-gee-community-datasets/projects/gfa/
