### ISSUE TITLE
MODIS LANCE (MODO9GQ) - NASA

### ISSUE THREAD

**Issue by becky-seg** [samapriya/awesome-gee-community-datasets#73]
### Dataset Name
MODIS LANCE: LANCE (Land, Atmosphere Near real-time Capability for EOS) is a collection of near real time data systems available within 3 hours of satellite observation. The near real time data is processed using predictive orbit information as opposed to definitive - allowing for quicker processing at the cost of some of the accuracy. The LANCE MODIS data is processed through the MODAPS processing center and available through the NASA earthdata download portal. 

MODIS is available through LANCE generally within 60 to 125 minutes of a satellite observation. LANCE NRT MODIS data includes land surface temperature, land surface reflectance, radiances, clouds/aerosols, water vapor, active fire, snow cover, and sea ice information. 

We use the following MODIS dataset from LANCE - https://nrt3.modaps.eosdis.nasa.gov/archive/allData/61/MOD09GQ/
---
If it is helpful, we have scripts that can be used to scrape the data into a GCP bucket, and a script that handles the translation and projection of the data. Translation is from HDF4 to COG, so requires GDAL with an HDF driver. We were planning to do this ingestion ourselves and host 10 days of data (from our logging over the last couple years, MODIS LAADS is usually available with 2-3 days, though occasionally with an up to 11 day lag).  If these are useful to you, please email becky.segal [at] arcticeider.com and madeleine.miller [at] arcticeider.com

Thumbnail or Snapshot (Optional)

(Omitted as there are already code samples for MODIS LAADS data)

#### Required
License Information:

https://www.earthdata.nasa.gov/learn/find-data/near-real-time/citation

Keywords: MODIS LANCE, Near real-time

Last updated: Daily

**Comment by becky-seg** [comment]
Any idea if/when you can support this ingestion flow?

@madeleine-miller and I are working to do this ourselves with a subset of the MODIS images (northern Canada) via a framework that will use a scheduled cloud function, with a custom image created using cloud build (that has the version of gdal we need). If you have time to provide advice about efficient ways of completing this processing chain we'd love to talk next week or in the new year. 

Our use case for this imagery is that we want to provide up-to-date imagery on our SIKU platform, which provides information used by Indigenous hunters and travelers. Having only MODIS LAADS on Earth Engine means the imagery is way out of date and not very useful for people making travel decisions - the MODIS LANCE data is much more useful as it is near real-time. I expect there would be broad interest in up-to-date MODIS imagery.

Thanks

**Comment by samapriya** [comment]
Hi @becky-seg 
Sorry for the delay in responding to this ticket. I had a conversation with Simon about this and felt this might be a large enough dataset to be in the primary catalog though I am not sure at what stage of priority this is. I am happy to chat if you are processing a subset of the dataset and would like to ingest that on your own. Let's catch up in the new year if that works for both of you, and I look forward to it :)

**Comment by becky-seg** [comment]
Sounds great, thanks

**Comment by madeleine-miller** [comment]
Hi @samapriya we'd love to schedule a chat about the dataset we've been processing. Is there a time/date that works well for you in the near future?

**Comment by samapriya** [comment]
Hey @madeleine-miller 
Feel free to email me samapriya.roy@gmail.com and I will be happy to set something up. I am in the Central time zone we can coordinate over email if that works

**Comment by samapriya** [comment]
Since this is an ongoing conversation closing issue for now, can be reopened once configured user side
