### ISSUE TITLE
Dataset: Model America – data and models of every U.S. building & Curator Name: Oakridge National Laboratory

### ISSUE THREAD

**Issue by mgaumer** [samapriya/awesome-gee-community-datasets#74]
Follow the underlying template when creating a new dataset request for new datasets. This is then submitted for evaluation and inclusion into the community catalog.  

Please edit the markdown text below as needed.

### Dataset Name: Model America – data and models of every U.S. building
Dataset description and any detailed citation and DOI and license information.
Here is the link for the dataset: https://doi.ccs.ornl.gov/ui/doi/339
On the above site, the following description is given:
'The 5-year goal of the “Model America” concept was to generate a model of every building in the United States. This data repository delivers on that goal. Oak Ridge National Laboratory (ORNL) has developed the Automatic Building Energy Modeling (AutoBEM) software suite to process multiple types of data, extract building-specific descriptors, generate building energy models, and simulate them on High Performance Computing (HPC) resources. For more information, see AutoBEM-related publications (bit.ly/AutoBEM). There were 125,714,640 buildings detected in the United States and this dataset contains 122,930,327 (97.8%) buildings which resulted in a successful simulation. Future, annual updates have been proposed that may include additional buildings, data improvements, or other algorithmic enhancements. This dataset of 122.9 million buildings includes: Models (state_county.zip) – OpenStudio (v3.1.0) and EnergyPlus (v9.4) building energy models. Please note that the download requires the free Globus Connect Personal (https://www.globus.org/globus-connect-personal); Each model has approximately 3,000 building input descriptors that can be extracted. Please see the EnergyPlus (v9.4) 2,784-page Input/Output Reference Guide (https://energyplus.net/sites/all/modules/custom/nrel_custom/pdfs/pdfs_v9.4.0/InputOutputReference.pdf) for everything that can be retrieved or simulated from these models. These models were derived from the following metadata, which is not included in this dataset: 1. ID - unique building ID 2. County - county name 3. State - state name 4. CZ - ASHRAE Climate Zone designation 5. Clim_Zone - text label of climate zone 6. est_year - estimated year of construction 7. est_commercial - estimated building type (0=residential, 1=commercial) 8. Centroid - building center location in latitude/longitude (from Footprint2D) 9. Footprint2D - building polygon of 2D footprint (lat1/lon1_lat2/lon2_...) 10. Height - building height (meters) 11. Area2D - footprint area (ft2) 12. BuildingType - DOE prototype building designation (IECC=residential) as implemented by OpenStudio-standards 13. WWR_surfaces - percent of each facade (pair of points from Footprint2D) covered by fenestration/windows (average 14.5% for residential, 40% for commercial buildings) 14. NumFloors - number of floors (above-grade) 15. Area - estimate of total conditioned floor area (ft2) 16. Standard - building vintage. These models are made free and openly available in hopes of stimulating any simulation-informed use case. Data is provided as-is with no warranties, express or implied, regarding fitness for a particular purpose. We wish to thank our sponsors which include Oak Ridge National Laboratory (ORNL) Laboratory Directed Research and Development (LDRD), U.S. Dept. of Energy’s (DOE) Building Technologies Office (BTO), Office of Electricity (OE), Biological and Environmental Research (BER), and National Nuclear Security Administration (NNSA). This research used resources of the Argonne Leadership Computing Facility, which is a DOE Office of Science User Facility supported under Contract DE-AC02-06CH11357. Please cite as: New, Joshua R., Adams, Mark, Bass, Brett, Berres, Anne, and Clinton, Nicholas (2021). “Model America - data and models of every U.S. building. [Data set].” Constellation, doi.ccs.ornl.gov/ui/doi/339, April 14, 2021'

Extra Info: 
Any papers that site this need to use this text in the acknowledgements:
"Support for DOI 10.13139/ORNLNCCS/1774134 dataset is provided by the U.S. Department of Energy, project Automatic Building Energy Modeling (AutoBEM) under Contract DE-AC05-00OR22725. Project Automatic Building Energy Modeling (AutoBEM) used resources of the Oak Ridge Leadership Computing Facility at Oak Ridge National Laboratory, which is supported by the Office of Science of the U.S. Department of Energy under Contract No. DE-AC05-00OR22725"

Download Tool/Code snippets, if any: 
Zip files to download sections of the data are included on the website here: https://doi.ccs.ornl.gov/ui/doi/339

#### Required
License Information: 
There is no specific license listed on the dataset website. Here is the contact information for the curators:

New, Joshua | newjr@ornl.gov
Adams, Mark | adamsmb@ornl.gov
Berres, Anne | berresas@ornl.gov
Bass, Brett | bbass11@vols.utk.edu
Clinton, Nicholas | nclinton@google.com

Curated by: Uploaders and curators name(s) include all you think helped.

New, Joshua 
Adams, Mark 
Berres, Anne 
Bass, Brett
Clinton, Nicholas

Keywords: The listed keywords on the site are building energy modeling; EnergyPlus; OpenStudio; urban-scale building energy modeling; nation-scale building energy modeling

**Comment by samapriya** [comment]
Hi @mgaumer 
Can you reach out to the authors to confirm the license, this is key to establishing distribution of this dataset

**Comment by samapriya** [comment]
Other complex things are that files are either in .idf or .osm format. The OSM file seems to be invalid and does not render which makes this a challenging import. Might need a conversation with the authors

**Comment by mgaumer** [comment]
Hi,

I also forgot to include this snippet on the license they sent as well:

 'data is provided under permissive UT-Batelle license (variant of MIT)'

Thanks,
Maddie Gaumer

**Comment by samapriya** [comment]
This has been partially completed to include USA structures while work is being done to get the joined data in place. https://gee-community-catalog.org/projects/usa_structures/

Closing this issue till there are new updates
