### ISSUE TITLE
Global projections of future urban land under shared socioeconomic pathways from Chen et al. (2020)

### ISSUE THREAD

**Issue by TC25** [samapriya/awesome-gee-community-datasets#75]
Follow the underlying template when creating a new dataset request for datasets you have created. This is then submitted for evaluation and inclusion into the community catalog.  

Please edit the markdown text below as needed

### Dataset Name
Global projections of future urban land under shared socioeconomic pathways from Chen et al. (2020)

Citation: Chen, G., Li, X., Liu, X. et al. Global projections of future urban land expansion under shared socioeconomic pathways. Nat Commun 11, 537 (2020). https://doi.org/10.1038/s41467-020-14386-x

Thumbnail or Snapshot (Optional)

#### Earth Engine Snippet if dataset already in GEE
```js


var SSP_2020 = ee.Image("projects/ee-tirthankar25/assets/SSP_Data/Chen/global_SSP_2020")
var SSP_2030 = ee.Image("projects/ee-tirthankar25/assets/SSP_Data/Chen/global_SSP_2030")
var SSP_2040 = ee.Image("projects/ee-tirthankar25/assets/SSP_Data/Chen/global_SSP_2040")
var SSP_2050 = ee.Image("projects/ee-tirthankar25/assets/SSP_Data/Chen/global_SSP_2050")
var SSP_2060 = ee.Image("projects/ee-tirthankar25/assets/SSP_Data/Chen/global_SSP_2060")
var SSP_2070 = ee.Image("projects/ee-tirthankar25/assets/SSP_Data/Chen/global_SSP_2070")
var SSP_2080 = ee.Image("projects/ee-tirthankar25/assets/SSP_Data/Chen/global_SSP_2080")
var SSP_2090 = ee.Image("projects/ee-tirthankar25/assets/SSP_Data/Chen/global_SSP_2090")
var SSP_2100 = ee.Image("projects/ee-tirthankar25/assets/SSP_Data/Chen/global_SSP_2100")

```

Sample Code: https://code.earthengine.google.com/c49d60c25f70cad2f9002df577689685

Extra Info: This dataset provides future estimates of urban expansion for all Shared Socioeconomic Pathways (SSPs) every 10 years from 2020 to 2100 (inclusive). The data are at 1 km resolution. Pixels have a value of 2 (for urban) or 1 (for non-urban). Each image corresponds to a date and there are separate bands for each SSP scenario. 

Download Tool/Code snippets if any: If source is specialized or you have an associated tool

#### Required
License Information: Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC-BY-NC-SA-4.0)

Curated by: TC Chakraborty (tc.chakraborty25@gmail.com; tirthankar25@gmail.com)

Keywords: Global Land Use and Land Cover

Last updated: 21/10/2022

**Comment by samapriya** [comment]
Please share permissions for all images inside folder, sharing a folder does not share permissions for assets inside folder. You can use my geeadd tool to simply do 

```
geeadd access --asset "projects/ee-tirthankar25/assets/SSP_Data/Chen" --user "allUsers --role READER
```

**Comment by samapriya** [comment]
This has been completed
