### ISSUE TITLE
Global projections of future urban land under shared socioeconomic pathways from Gao & O'Neill (2020)

### ISSUE THREAD

**Issue by TC25** [samapriya/awesome-gee-community-datasets#76]
Follow the underlying template when creating a new dataset request for datasets you have created. This is then submitted for evaluation and inclusion into the community catalog.  

Please edit the markdown text below as needed

### Dataset Name
Global projections of future urban land under shared socioeconomic pathways from Gao & O'Neill (2020)

Citation: Gao, J., O’Neill, B.C. Mapping global urban land for the 21st century with data-driven simulations and Shared Socioeconomic Pathways. Nat Commun 11, 2302 (2020). https://doi.org/10.1038/s41467-020-15788-7

Thumbnail or Snapshot (Optional)

#### Earth Engine Snippet if dataset already in GEE
```js


var SSP_2020 = ee.Image("projects/ee-tirthankar25/assets/SSP_Data/Gao/global_SSP_2020")
var SSP_2030 = ee.Image("projects/ee-tirthankar25/assets/SSP_Data/Gao/global_SSP_2030")
var SSP_2040 = ee.Image("projects/ee-tirthankar25/assets/SSP_Data/Gao/global_SSP_2040")
var SSP_2050 = ee.Image("projects/ee-tirthankar25/assets/SSP_Data/Gao/global_SSP_2050")
var SSP_2060 = ee.Image("projects/ee-tirthankar25/assets/SSP_Data/Gao/global_SSP_2060")
var SSP_2070 = ee.Image("projects/ee-tirthankar25/assets/SSP_Data/Gao/global_SSP_2070")
var SSP_2080 = ee.Image("projects/ee-tirthankar25/assets/SSP_Data/Gao/global_SSP_2080")
var SSP_2090 = ee.Image("projects/ee-tirthankar25/assets/SSP_Data/Gao/global_SSP_2090")
var SSP_2100 = ee.Image("projects/ee-tirthankar25/assets/SSP_Data/Gao/global_SSP_2100")

```

Sample Code: https://code.earthengine.google.com/1e1e1ec2200fc62b777da766048c8913

Extra Info: This dataset provides future estimates of urban expansion for all Shared Socioeconomic Pathways (SSPs) every 10 years from 2020 to 2100 (inclusive). The data are at 1/8 degree resolution. Probabilities of conversion of entire grid to urban is provided instead of a binary classification. Each image corresponds to a date and there are separate bands for each SSP scenario. 

Download Tool/Code snippets if any: If source is specialized or you have an associated tool

#### Required
License Information: Attribution 4.0 International (CC BY 4.0)

Curated by: TC Chakraborty (tc.chakraborty25@gmail.com; tirthankar25@gmail.com)

Keywords: Global Land Use and Land Cover

Last updated: 21/10/2022

**Comment by samapriya** [comment]
Hi @TC25 
Since these are just different decadal projections would you like me to add this to a single collection hosted at my end with date information so you can filter by date ?

**Comment by TC25** [comment]
That works for me.

**Comment by samapriya** [comment]
Cool will let me know if I have more questions

**Comment by TC25** [comment]
Also noting that these projections are all over the place. See the figure below (also comparing with the Li et al. data you have already ingested). Always good to have a word of caution about these datasets and encourage users to go back to the paper and understand the various assumptions, methodological differences, and what they might mean for use cases. 

![SSPs_compare_Asia](https://user-images.githubusercontent.com/30564889/197263701-a357d3f3-736c-4e5d-9fad-732a856dc4f1.png)

**Comment by samapriya** [comment]
Actually would you mind write a data description paragraph and include the section you just mentioned that way I can include exactly what users should look for

**Comment by TC25** [comment]
Sure! I will get back to you by the end of the day. Have to make sure I don't plagiarize my own preprint.

**Comment by samapriya** [comment]
Please share permissions for all images inside folder, sharing a folder does not share permissions for assets inside the folder. You can use my geeadd tool to simply do 

```
geeadd access --asset "projects/ee-tirthankar25/assets/SSP_Data/Gao" --user "allUsers --role READER
```

**Comment by TC25** [comment]
I have shared all the images. 

Here is a paragraph that you can modify:

This ImageCollection includes two separate global projections of future urban land under shared socioeconomic pathways (SSPs), one from Chen et al. (2020) and the other from Gao & O'Neill (2020). The Chen et al. dataset provides binary classification of urban and non-urban land (pixel value of 2 for urban; 1 otherwise) at 1 km resolution for every 10th year from 2020 to 2100 (inclusive). On the other hand, the Gao & O'Neill (2020) dataset provides continuous values representing probability of full urbanization of each 1/8 degree grid for the same years. 

When using these future projections, it is important to recognize that they are based on different methodologies, different training data, and different assumptions about the future scenarios. For instance, the Gao & O'Neill dataset considers broad urbanization patterns across 375 sub-regions, while the Chen et al. data uses 32 regions. While both of these datasets are trained using the Global Human Settlement Layer (GHSL), the Chen et al. data are further calibrated against the European Space Agency's Climate Change Initiative (ESA CCI) data for 2015.  There are many other differences and users should ideally go through the assumptions and methodology described in the respective papers before using the data. 

As an example of these differences, below is a plot of projected urban percentage over time for Asia for different SSP scenarios from these datasets and the Li et al. (2021) urban extent data, which is also in the community catalog. Note that the Li et al. data are not based on GHSL, but on historical urban extent dataset from nighttime lights:

![image](https://user-images.githubusercontent.com/30564889/197280107-3452c97e-18d1-48d0-8954-063bc56b23fc.png)

References:

1. Chen, G., Li, X., Liu, X. et al. Global projections of future urban land expansion under shared socioeconomic pathways. Nat Commun 11, 537 (2020). https://doi.org/10.1038/s41467-020-14386-x

2. Gao, J., O’Neill, B.C. Mapping global urban land for the 21st century with data-driven simulations and Shared Socioeconomic Pathways. Nat Commun 11, 2302 (2020). https://doi.org/10.1038/s41467-020-15788-7

3. Li, X., Zhou, Y., Hejazi, M. et al. Global urban growth between 1870 and 2100 from integrated high resolution mapped data and urban dynamic modeling. Commun Earth Environ 2, 201 (2021). https://doi.org/10.1038/s43247-021-00273-w

**Comment by samapriya** [comment]
Making progress here could you check if this collection makes sense including start and end dates for each image in the collection

projects/sat-io/open-datasets/FUTURE-URBAN-LAND/GAO_2020_2100
projects/sat-io/open-datasets/FUTURE-URBAN-LAND/CHEN_2020_2100

**Comment by TC25** [comment]
I would shift all the times by 5 years; so the 2020 image can be selected between 2015 and 2024 and so on. 

Currently, the 2020 image ranges from 2010-01-01 to 2020-12-31 and then the 2030 image starts from 2020-01-01.

Would be better if it were 2015-01-01 to 2025-01-01 (or 2024-12-31) for the 2020 image (start from 2025-01-01 for the 2030 image). The end date in filterDate is excluded; so shouldn't lead to any overlaps even if you use the same end date as the start date for the next image?

Also, when I use print(CHEN.filterDate('2013-01-01','2021-01-01')), I get the image for 2030, which is confusing. 

https://code.earthengine.google.com/ed85917190cb411bc4e86198f2fcfdc9
