### ISSUE TITLE
High-resolution global map of smallholder and industrial closed-canopy oil palm plantations

### ISSUE THREAD

**Issue by KendallJones** [samapriya/awesome-gee-community-datasets#77]
### High-resolution global map of smallholder and industrial closed-canopy oil palm plantations
These data provide 10m resolution maps of both smallholder and industrial oil palm plantations for the second-half of 2019. 

Data available @ https://zenodo.org/record/4473715#.Y1j-3XbMK5c 

Citation: Descals, Adrià, et al. "High-resolution global map of smallholder and industrial closed-canopy oil palm plantations." Earth System Science Data 13.3 (2021): 1211-1231.

<img width="382" alt="image" src="https://user-images.githubusercontent.com/17837197/197992229-3a777987-7572-4623-839c-4302c84d87a5.png">

#### Earth Engine Snippet if dataset already in GEE
Not in GEE

#### Required
License Information: Creative Commons Attribution 4.0 International (view dataset @ https://zenodo.org/record/4473715#.Y1j-3XbMK5c)

Curated by: Kendall Jones

Keywords: Oil Palm, Plantation, Sentinel
Last updated: 2019

**Comment by samapriya** [comment]
This is already part of the catalog, hope that helps :) 
https://gee-community-catalog.org/projects/oil-palm/#2-high-resolution-global-industrial-and-smallholder-oil-palm-map-for-2019
