### ISSUE TITLE
keywords - spaces and duplicates

### ISSUE THREAD

**Issue by schwehr** [samapriya/awesome-gee-community-datasets#78]
Spaces and repeats in keywords.  For example [CSRL_soil_properties_land_use_hydrologic_group.json](https://github.com/samapriya/awesome-gee-community-datasets/blob/1a6d68e63db284920c3b1f8ded3008493b2786f9/catalog/CSRL_soil_properties_land_use_hydrologic_group.json#L63)

```
    "keywords": [
        "Soil grid",
        " USDA",
        " CSRL",
        " UCANR",
        "USDA",
        " Soil",
        " Coarse"
    ],
```

There are extra leading spaces and repeats.  e.g. `USDA` is in their 2x if the leading spaces are stripped.

Questions:

1. Is there a special meaning to the leading empty space? 
2. If there isn't a special meaning are you up for a pr to remove the spaces
3. and up for a dedup and sort pr?

**Comment by samapriya** [comment]
Hey @schwehr 
Thanks for the issue let's try to answer your questions
* No special meaning to the extra spaces, when the keywords were split and rejoined it is possible that space was added during the ",".join operation and I can check on that if this is consistent across all datasets. If not then this might simply be a human error as we type up the keywords initially for the master list
* I am more than happy to have a PR to remove spaces but I think I need to check the code that generates this STAC catalog from the objects I have to make sure this is not repeated
* and yes up for  a dedup pr as well to get rid of repeating keywords

I might add you to a meeting to discuss standardized keywords soon to discuss these even further. Thank you for raising the issue

**Comment by samapriya** [comment]
Thank you for your PR I have merged it, closing this issue for now and I will work on the long-term fix in my stac generator code
