### ISSUE TITLE
Enforce units reporting

### ISSUE THREAD

**Issue by jonschwenk** [samapriya/awesome-gee-community-datasets#81]
Awesome resource you're curating here. I might be missing something obvious, but I'm finding it very difficult to ascertain units for many of the provided datasets. Many descriptions do not mention the data's units, leaving users to dig around for the source datasets and hope they're noted there. Could this be a piece of required metadata for submission to this collection?

**Comment by samapriya** [comment]
Agreed and I will happily accept PRs too to highlight units for the ones you might have already found :) 

Updating the remaining might take a bit

**Comment by samapriya** [comment]
Since this is going to be an ongoing improvement closing this ticket for now
