### ISSUE TITLE
High Resolution Digital Elevation Model (HRDEM) - CanElevation Series & Natural Resources Canada

### ISSUE THREAD

**Issue by icrichmond** [samapriya/awesome-gee-community-datasets#84]
### High Resolution Digital Elevation Model (HRDEM) - CanElevation Series
Dataset description:   

The High Resolution Digital Elevation Model (HRDEM) product is derived from airborne LiDAR data (mainly in the south) and satellite images in the north. The complete coverage of the Canadian territory is gradually being established. It includes a Digital Terrain Model (DTM), a Digital Surface Model (DSM) and other derived data. For DTM datasets, derived data available are slope, aspect, shaded relief, color relief and color shaded relief maps and for DSM datasets, derived data available are shaded relief, color relief and color shaded relief maps.

The productive forest line is used to separate the northern and the southern parts of the country. This line is approximate and may change based on requirements. In the southern part of the country (south of the productive forest line), DTM and DSM datasets are generated from airborne LiDAR data. They are offered at a 1 m or 2 m resolution and projected to the UTM NAD83 (CSRS) coordinate system and the corresponding zones. The datasets at a 1 m resolution cover an area of 10 km x 10 km while datasets at a 2 m resolution cover an area of 20 km by 20 km. In the northern part of the country (north of the productive forest line), due to the low density of vegetation and infrastructure, only DSM datasets are generally generated. Most of these datasets have optical digital images as their source data. They are generated at a 2 m resolution using the Polar Stereographic North coordinate system referenced to WGS84 horizontal datum or UTM NAD83 (CSRS) coordinate system. Each dataset covers an area of 50 km by 50 km. For some locations in the north, DSM and DTM datasets can also be generated from airborne LiDAR data. In this case, these products will be generated with the same specifications as those generated from airborne LiDAR in the southern part of the country.

The HRDEM product is referenced to the Canadian Geodetic Vertical Datum of 2013 (CGVD2013), which is now the reference standard for heights across Canada.

Source data for HRDEM datasets is acquired through multiple projects with different partners. Since data is being acquired by project, there is no integration or edgematching done between projects. The tiles are aligned within each project.

The product High Resolution Digital Elevation Model (HRDEM) is part of the CanElevation Series created in support to the National Elevation Data Strategy implemented by NRCan. Collaboration is a key factor to the success of the National Elevation Data Strategy. Refer to the “Supporting Document” section to access the list of the different partners including links to their respective data.
  
Detailed citation and DOI:  

License information: [Open Government License Canada](https://open.canada.ca/en/open-government-licence-canada)

Thumbnail: ![image](https://user-images.githubusercontent.com/52459005/205149232-0c51f650-a06b-49cc-baf2-c0b9e51a09b6.png)

#### Earth Engine Snippet if dataset already in GEE: N/A

Extra Info:
- [Homepage](https://open.canada.ca/data/en/dataset/957782bf-847c-4644-a757-e383c0057995)
- [Product Specs](https://ftp.maps.canada.ca/pub/elevation/dem_mne/highresolution_hauteresolution/HRDEM_Product_Specification.pdf)
- [Metadata English](https://ftp.maps.canada.ca/pub/elevation/dem_mne/highresolution_hauteresolution/HRDEM_Metadata_Model.html)

Download Tool/Code snippets, if any:  
- [FTP](https://ftp.maps.canada.ca/pub/elevation/dem_mne/highresolution_hauteresolution/)
- [Open Maps Data Viewer](https://search.open.canada.ca/openmap/957782bf-847c-4644-a757-e383c0057995)
- [Download Directory](https://open.canada.ca/data/en/dataset/957782bf-847c-4644-a757-e383c0057995/resource/e09f91df-9a22-43b4-8027-25309afaa138)

#### Required
License Information: [Open Government License Canada](https://open.canada.ca/en/open-government-licence-canada)

Curated by: Government of Canada; Natural Resources Canada; Strategic Policy and Innovation Sector

Keywords: Digital Elevation Model, Digital Surface Model, Digital Terrain Model, LiDAR, Shaded Relief, Aspect Map, Color Shaded Relief, Slope Map, ArcticSDI_DEM, Digital elevation data

Last updated: 2022-06-25

**Comment by samapriya** [comment]
Hi @icrichmond 
So quite a few tiles overlap, not just spatially but temporally. What's the strategy to combine them? Some of these also have spatial overlaps within the same timeframe. What's the recommendation in these situations for example, in the folder BC look at Riverine_Floodplain_UTM09_2019. It contains a folder called UTM10, and similarly, there is Riverine_Floodplain_UTM10_2019 which has a similar problem which has UTM9, UTM10, and UTM11. Any recommendations here

**Comment by samapriya** [comment]
Hi @icrichmond 
Could you apply for the [insider's program](https://gee-community-catalog.org/insiders/)? I will be able to give your email access to the collection early before I make final checks and make it available globally. It is completely free and open to those who contributed datasets

**Comment by samapriya** [comment]
Hi @icrichmond 
This has been completed and made available to the [insiders program](https://gee-community-catalog.org/insiders/) users for now. Please apply to the [insiders program](https://gee-community-catalog.org/insiders/) and I can grant you access to it and I will release it generally for all in early Feb

https://gee-community-catalog.org/projects/hrdem/

Thank you for contributing and closing this issue for now

**Comment by samapriya** [comment]
Hi @icrichmond 
You have now been added to the insiders program and your email should now be able to access the dataset

**Comment by icrichmond** [comment]
> Hi @icrichmond You have now been added to the insiders program and your email should now be able to access the dataset

Thank you SO much!! Will check this out next week!

**Comment by icrichmond** [comment]
Hey @samapriya , 

Just wanted to thank you again for this dataset! I used it with the Microsoft building footprints layer to calculate building heights across the country for my PhD thesis. Code [here](https://code.earthengine.google.com/31fe928b524d7417d665ece32534115c) in case you are interested (thanks to @robitalec for help with the code).

Thank you again!!
