### ISSUE TITLE
Global Daily near-surface air temperature (2003-2020)

### ISSUE THREAD

**Issue by ElliotYIN** [samapriya/awesome-gee-community-datasets#87]
Follow the underlying template when creating a bug request for an existing dataset in the the community catalog.  

Please edit the markdown text below as needed

#### Describe the bug

Link to the dataset page: https://gee-community-catalog.org/projects/airtemp/

Two days of air temperature data are missing. Specifically, 
1. "projects/sat-io/open-datasets/global-daily-air-temp/north_america/NorthAmerica_Ta_SVCMsp_2020TMIN_092" cannot be found.
2. "projects/sat-io/open-datasets/global-daily-air-temp/europe_asia/EuropeanAsia_Ta_SVCMsp_2010TMIN_180" cannot be found.
A clear and concise description of what the bug is and include the link to the dataset page.

**Comment by samapriya** [comment]
Same here waiting on author to respond to the data request

**Comment by samapriya** [comment]
Those two files have file size 0, and the author would need to fix that error for me to process those two files. Closing it for now till there is a response form author

**Comment by ElliotYIN** [comment]
> Those two files have file size 0, and the author would need to fix that error for me to process those two files. Closing it for now till there is a response form author

Thank you for helping me with this.
