### ISSUE TITLE
LANDFIRE full release history

### ISSUE THREAD

**Issue by zyliu2020** [samapriya/awesome-gee-community-datasets#89]
### LANDFIRE full release history of vegetation species, biomass, and canopy height

LANDFIRE is a shared program between the wildland fire management programs of the U.S. Department of Agriculture's Forest Service, U.S. Department of the Interior's Geological Survey, and The Nature Conservancy.

LANDFIRE (LF) layers are created using predictive landscape models based on extensive field-referenced data, satellite imagery and biophysical gradient layers using classification and regression trees. 

#### Required
License Information: LANDFIRE data are public domain data with no use restrictions. If modifications or derivatives of the product(s) are created, then please add some descriptive modifiers to the data set to avoid confusion.

### Version history

LANDFIRE had multiple releases, documenting forest inventory, biomass, canopy heights, tree species in the US, and disturbance history over the past decades. [https://landfire.gov/lf_schedule.php](url)

Such a tracked history of forest vegetation changes is a powerful tool for people to study fire patterns and design better forest management and fuel reduction strategies in the U.S. West --- Existing academic works have shown that biomass/fuel-loading has a strong predictive power for fire activities. However, some recent papers have used static biomass conditions from one or two years for data calibration due to limitations in data access. Having the entire LANDFIRE release history on our community catalog provides extremely valuable material for researchers doing fire modeling and forest eco-science studies, as it allows people to investigate how vegetation conditions dynamically interact with fire (it is interesting to put the MTBS dataset together with a dynamic tracking on LANDFIRE, for example).

**Comment by samapriya** [comment]
Hi @zyliu2020 
Landfire 2.2.0 already exists here https://gee-community-catalog.org/projects/landfire/ have a look
