### ISSUE TITLE
GWRPM25->Global->Monthly & Dr. Aaron van Donkelaar

### ISSUE THREAD

**Issue by poonamtajanpure** [samapriya/awesome-gee-community-datasets#90]
### Dataset Name
Global/Regional Estimates (V5.GL.03):
We estimate annual and monthly ground-level fine particulate matter (PM2.5) for 1998-2021 by combining Aerosol Optical Depth (AOD) retrievals from the NASA MODIS, MISR, and SeaWIFS instruments with the GEOS-Chem chemical transport model, and subsequently calibrating to global ground-based observations using a Geographically Weighted Regression (GWR), as detailed in the below reference for V5.GL.01. V5.GL.03 follows the methodology of V5.GL.01, but updates the ground-based observations used to calibrate the geophysical PM2.5 estimates for the entire time series, and extends temporal coverage through 2021.

Note that these estimates are primarily intended to aid in large-scale studies. Annual and coarse-resolution averages correspond to a simple mean of within-grid values. Gridded datasets are provided to allow users to agglomerate data as best meets their particular needs. High resolution (0.01° × 0.01°) datasets are gridded at the finest resolution of the information sources that were incorporated, but are unlikely to fully resolve PM2.5 gradients at the gridded resolution due to influence by information sources at coarser resolution.

Data name:
Annual and monthly mean PM2.5 [ug/m3] at 0.01° × 0.01°:
[[https://wustl.box.com/v/ACAG-V5GL03-GWRPM25]](https://wustl.box.com/v/ACAG-V5GL03-GWRPM25)

There are five parts of output netcdf files in the above folder. We should work with the "Global" folder, as it includes estimates for all the countries. 

Data link:
https://wustl.app.box.com/v/ACAG-V5GL03-GWRPM25/folder/176283878461

Data info paper:
Aaron van Donkelaar, Melanie S. Hammer, Liam Bindle, Michael Brauer, Jeffery R. Brook, Michael J. Garay, N. Christina Hsu, Olga V. Kalashnikova, Ralph A. Kahn, Colin Lee, Robert C. Levy, Alexei Lyapustin, Andrew M. Sayer and Randall V. Martin (2021). Monthly Global Estimates of Fine Particulate Matter and Their Uncertainty Environmental Science & Technology, 2021, doi:10.1021/acs.est.1c05309. [[Link]](https://pubs.acs.org/doi/abs/10.1021/acs.est.1c05309)

#### Required
License Information: Please include license information. If you don't have a license, please include any license document(s) with additional details and contact information for the original dataset creators

Curated by: Dr. Aaron van Donkelaar, 

Keywords: Air pollution, Monthly PM 2.5, Global, and High resolution (~1km)

Last updated: Oct 13, 2022, 12:48 PM (from box.com info)

**Comment by samapriya** [comment]
Hi @poonamtajanpure 
Can you please provide the license for this dataset? And any/all units of measurement for the data. Any converted file or NC file structure would be helpful as well

**Comment by samapriya** [comment]
I also need information on the transform and affine for the files

**Comment by samapriya** [comment]
Since I am unable to get a response closing this issue for now
