### ISSUE TITLE
RADD Forest Disturbance Alert - Dr Johannes Reiche et al.

### ISSUE THREAD

**Issue by jakenotjay** [samapriya/awesome-gee-community-datasets#95]
### RADD Forest Disturbance Alert
RADD - RAdar for Detecting Deforestation - Near real-time disturbances in humid tropical forest based on Sentinel-1 at 10m spatial scale. 

**Website**
[University of Wageningen](https://www.wur.nl/en/research-results/chair-groups/environmental-sciences/laboratory-of-geo-information-science-and-remote-sensing/research/sensing-measuring/radd-forest-disturbance-alert.htm)

**Coverage**
Primary humid tropical forest of South America (13 countries), Central America (6 countries), Africa (25 countries), insular Southeast Asia (5 countries) and Pacific (1 country).

**Dataset Reference**
Reiche J, Mullissa A, Slagter B, Gou Y, Tsendbazar N, Odongo-Braun C, Vollrath A, Weisse M, Stolle F, Pickens A, Donchyts G, Clinton N, Gorelick N & Herold M, (2021), Forest disturbance alerts for the Congo Basin using Sentinel-1, Environmental Research Letters, https://doi.org/10.1088/1748-9326/abd0a8.

**Data Availability**
Earth Engine - `ee.ImageCollection('projects/radar-wur/raddalert/v1')`
Global Forest Watch - [Open Data Portal](https://data.globalforestwatch.org/datasets/gfw::deforestation-alerts-radd/about)
[Sepal.io](https://sepal.io/)
[EarthMap](https://earthmap.org/)

#### Earth Engine Snippet 
```js
var radd = ee.ImageCollection('projects/radar-wur/raddalert/v1');
var geography = 'sa';

// forest baseline mask
var forest_baseline = ee.Image(radd.filterMetadata('layer','contains','forest_baseline')
                            .filterMetadata('geography','equals',geography).first())

Map.addLayer(forest_baseline, {palette:['black'], opacity: 0.3},'Forest baseline')

var latest_radd_alert =  ee.Image(radd.filterMetadata('layer','contains','alert')
                            .filterMetadata('geography','equals',geography)
                            .sort('system:time_end', false).first());

Map.addLayer(latest_radd_alert.select('Alert'), {min:2,max:3,palette:['blue','coral']}, 'RADD alert')
```

#### EE Examples provided by creators:
[Access latest RADD Alerts](https://code.earthengine.google.com/47857aee8cc93a6b2506a02cb78026c9)
[Download RADD Alerts as GeoTIFF to Google Drive](https://code.earthengine.google.com/6be36b448b13aeed914b4aff7d1510dd)

#### Required
License Information: The data is licensed under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/) and may be used by anyone, anywhere, anytime without permission or royalty payment. Attribution using the recommended citation is requested.

Curated by: J Reiche, J Balling, M Herold, B Slagter, NE Tsendbazar

Keywords: Forest, Deforestation, Alerts, NBS

Last updated: 2023-01-08 (updates with S1)

**Comment by samapriya** [comment]
Thank you for contributing your dataset is now available here. I made some minor edits here and there and reformatted some text. Let me know if all looks good

https://gee-community-catalog.org/projects/radd/

**Comment by jakenotjay** [comment]
Looks good to me - thanks for doing that so quickly @samapriya!
