### ISSUE TITLE
Add Code example for GeoBoundaries

### ISSUE THREAD

**Issue by spatialthoughts** [samapriya/awesome-gee-community-datasets#96]
Follow the underlying template when creating a code example for an existing dataset in the awesome-gee-community-catalog.

Please edit the markdown text below as needed

### Dataset Name and Catalog Page
[geoBoundaries Global Database of Political Administrative Boundaries](https://gee-community-catalog.org/projects/geoboundary/#geoboundaries-global-database-of-political-administrative-boundaries)

### Code link
https://code.earthengine.google.co.in/84eec36755763ec6de4cdb125596bda9

#### Attribution
Ujaval Gandhi. www.spatialthoughts.com

**Comment by samapriya** [comment]
Thank you for contributing @spatialthoughts 
I have updated the example code and added code attribution on the dataset page
