### ISSUE TITLE
Global Electric Consumption revised GDP

### ISSUE THREAD

**Issue by cmg777** [samapriya/awesome-gee-community-datasets#97]
#### Describe the bug
Image '1992GDP' does not have a 'system:time_start' property

#### Sample Earth Engine Code
https://code.earthengine.google.com/b117c8298124d9078aeea821a6bd3371

#### Screenshots

<img width="892" alt="*GRIDDED-ELECTRICITY-CONSUMPTION-GDP - Earth Engine Code Editor 2023-01-17 11-34-53" src="https://user-images.githubusercontent.com/26156651/212797806-d765c812-832c-4aa2-bf0f-3e4b06af03d5.png">

**Comment by samapriya** [comment]
This has been fixed
