### ISSUE TITLE
Global Mangrove Watch

### ISSUE THREAD

**Issue by dadr94** [samapriya/awesome-gee-community-datasets#99]
#### Describe the bug

Global Mangrove Watch documentation is inconsistent. In the Earth Engine Snippet's the variable names do not match the featureCollection names. https://gee-community-catalog.org/projects/mangrove/

e.g. `var extent_2016 = ee.FeatureCollection("projects/earthengine-legacy/assets/projects/sat-io/open-datasets/GMW/extent/gmw_v3_2020_vec");`

Here, the variable is appened `_2016`, but the feature collection implies the data is from `2020`.

**Comment by samapriya** [comment]
Thank you for the bug request, just fixed it
